/*
* SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
* SPDX-License-Identifier: GPL-2.0-only OR Apache-2.0
*/

#ifndef NVMEIBC_RAID_RECOVERY
#define NVMEIBC_RAID_RECOVERY

#include "../../nvmeibc_block.h"		/* external API of the block */
#include "nvmeibc_raid_recov_itr.h"
#include "block/nvmeibc_topology.h"
#include "../../../toma/clnt/nvmeibt_client_protocol.h"
#include "block/datapath_utils_generic/operation/nvmeibc_block_dp_operation_async_mode.h"

struct nvmeibc_recovery;

struct nvmeibc_recovery_hooks{
	void (*on_finish_one_sync)(     struct nvmeibc_recovery_hooks* self, struct nvmeibc_recovery* recov);
	void (*on_launch)(              struct nvmeibc_recovery_hooks* self, struct nvmeibc_recovery* recov);
	void (*on_finish)( 		        struct nvmeibc_recovery_hooks* self, struct nvmeibc_recovery* recov);
	void (*on_dummy_get_next_batch)(struct nvmeibc_recovery_hooks* self, struct nvmeibc_recovery* recov, const u8**arr, u64 *n_elem);
};

/********************* Recovery object: Internal API **************************/
/* When Toma X requests recovery of raid1, Toma X or Y can cancel it, client
   reports completion of recovery to X. If the toma X is not reachable (disk is
   paused - the recovery canceled and Toma knows that implicitly).*/
struct nvmeibc_recovery_args {  // recovery arguments, stay unchanged for the whole recovery process
	u64  task_id;				// Unique id of task (per-toma), generated by Toma
	struct nvmeibc_subscription_ctx *tr; 		// toma that originated the recovery of raid, will receive ACK, stats, etc
	int praid_version; 			// topo-version on which recovery was started. Upon change will abort
	bool silent_mode;			// For debug. If true, will not update/reply to Toma. This is regardless of whether Toma launched recovery or other recovery launched it
	bool do_only_owners;		// Process only blocksets of which 'tr' is primary owner
	bool is_mandatory;			// If blockset fix failed, can we skip it or retry until success
	u64 r_start;				// recovery start rlba[units of locks] (first batch should start     here)
	u64 r_end;					// recovery end   rlba[units of locks] (last  batch should terminate here)
	union {											// Generic payload for recovery start
		struct {
			u16 w_is_dirty_segs_bmp; 	// Bitmap of W- segs: Just caching it from relevant praid to be able to access it even without holding reference to topology.
		} dconv;
		struct {
			u16 surviving_ram_bmp; // Cold recovery: bitmap for segments, which segs maintained RAM and which lost their RAM. if all lost their ram then this is true cold recovery of 100% of praid
		} cold;
	};

	// Aux struct which allows recovery to call auxilliary recovery (DBITS calls DCONVICT)
	struct nvmeibc_recovery_chaining {				// Caller (recovery) gives context and cb function to callee. const means 'dont touch!' other than pasing to function below
		void *ctx;									// Loose typing: In future allow ioctl mechanism to call recovery via this mechanism and not jsut recovery calling recovery.
		void (*on_finish)(void *ctx, int err);		// Typically: do_next_work_batch_cb(). Allow flexibily of wrapping this function for summation of process, status analysis, etc
	} notify_caller;
};

struct nvmeibc_recovery {		// holds information about recovery in process
	/*status of recovery:
	  INIT -> start message -> PROCESS -> finished all work -> INIT.
	  PROCESS -> cancel -> CANCELING -> wait for in air syncs to finish -> INIT.*/
	enum e_recov_status {RCVR_READY = 0, RCVR_INIT, RCVR_PROCESS, RCVR_CANCELING} status;

	enum NVMEIBT_RECOVERY_TYPE type; // since we have multiple recoveries, implemented as tuple tuple is "multiple types, single instance per type" this variable is initialized in nvmeibc_recovery constructor and should not changed ever; it also means that the recovery instance will only run the specific type of recovery
	spinlock_t guard;				 /* guards status and completion, serialize cancel recovery / start recovery / sync complete events */
	struct nvmeibc_recovery_args args;

	struct nvmeibc_recov_stats {		// Statistics about recovery tasks
		u64 n_total_tasks;		// N launched tasks
		u64 n_success; // N successfully finished tasks
		u64 n_delayed_jobs; // N jobs that were delayed because of ineffectivness
	} stats;
	struct /* current recov_task */ {
		struct nvmeibc_recov_sync_worker *sw;	// Recovery can fix a few blocksets in parallel. Array of workers
		atomic_t n_sw_running; 					// number of workers in air, state can change only when all worker finish
		u32	n_sw_to_use;						// [1..10] amount of workers to be used. This variable throttles recovery
		u32 max_batch_size;						// In units of locks
		void (*do_next_work_batch_cb)(struct nvmeibc_recovery *recov); // Get the next batch of work, handles failure internally, so no 'rv'
		struct {								// Progress reporting to toma (Not periodic, but based on progress)
			u32 n_attempts_since_msg; 			// Total amount of attempts to fix locks since the last update to Toma (used to schedule next update message)
			u32 threshold;						// Amount of syncs that pass this threshold require report message
		} report;
		bool has_appendix_task; // After all requested blocksets fixed, some recoveries need appendix
		bool is_ec_raid;			// Just a caching var, to know if 'ec' without topology. Toma request recovery on 'ec' protection raid
	};

	/* The recovery task may be divided into serveral batches of recoveries,
	in each we call the locks channel to get information about the locks.
	this member helps to know whether we need to run additional cycle of
	recovery after the current cycle ends */
	struct /*recov_work_batch*/ { // Daniel Todo: Move this inside an iterator. It is heavily coupled with iterators inner states
		u64 b_start;		// Current work batch start rlba[units of locks]. This is not disk lba!
		u64 b_length;		// Length of current work batch (upper bound on the amount of work items). When last batch ends b_start + b_length == r_end
	};

	struct nvmeibc_recovery_itr_t itr;
	union {/* can hold private data of specific recovery */
		struct {
			void *priv;								// C++ inheritance for specific recovery
			void (*priv_destructor)(void* priv);	// Destructor which is called when recovery finishes, on success / error
		};
		struct delayed_work	dwork;	// Move allocation to thread context
	};
	BLKCMP_SO_DEFINE_BLOCKING_CONTEXT;
};

int  recovery_get_topo(                    struct nvmeibc_recovery *recov);	// Aquire and hold
void recovery_put_topo(                    struct nvmeibc_recovery *recov);	// Done using topo
struct nvmeibc_raid1 *recovery_topo_pr_ptr(struct nvmeibc_recovery *recov);	// Call after acquisition to get ptr to protection raid

/* Order of functions:
   while has batches to do:
	   1. Generic function: on recovery_on_batch_request()
	   2. ... virtual function to bring the batch information (get dbits/read jmdc/etc)
	   3. Generic function: recovery_on_batch_req_comp_calc_upper_bound()
	   4. ... virtual function: recov->itr.reinit()
	   5. recovery_on_batch_start()
	   6. ... virtual functions: Iterators run... do syncs ...
	   7. recovery_on_batch_finish() */
int  recovery_on_batch_request(struct nvmeibc_recovery *recov);
void recovery_on_batch_req_comp_calc_upper_bound(struct nvmeibc_recovery *recov, u64 n_problems, u64 batch_size); 	// Needed for correct/monotonic display of progress and report to toma
void recovery_on_batch_start(struct nvmeibc_recovery *recov);			// Failure in this func is handled by calling finish internally
void recovery_on_batch_finish(struct nvmeibc_recovery *recov, int err);	// 'err' == 0 means success

/**************************** Printing functions ******************************/
#define WARN_RR(cond, fmt, ...) WARN(cond, DMESG_PREFIX("%s: ") "(%d,%d,%d)[%d(0x%llx)] bug!: " fmt   , recov->args.tr->nt->device_name, recov->args.tr->ch, recov->args.tr->r1, recov->args.tr->seg, recov->type, recov->args.task_id, ##__VA_ARGS__)

#define RECOV_FMT "[@TR_RECOV_TYPE(@TASK_ID)]"
#define __NLVL_RECOV_ARGS(LVL, name, tr, recov_type, recov_task_id, format, ...) LVL(name, recovery /*Scope*/, "@DEV_NAME" SEGMENT_FMT RECOV_FMT ": " format, tr->nt->device_name, tr->ch, tr->r1, tr->seg, recov_type, recov_task_id, ##__VA_ARGS__)
#define __NLVL_RECOV(LVL, name, format, ...) __NLVL_RECOV_ARGS(LVL, name, recov->args.tr, recov->type, recov->args.task_id, format, ##__VA_ARGS__)

#define _NDRR(name, format, ...) __NLVL_RECOV(_ND_SCOPE, name, format, ##__VA_ARGS__)
#define _NTRR(name, format, ...) __NLVL_RECOV(_NT_SCOPE, name, format, ##__VA_ARGS__)
#define _NIRR(name, format, ...) __NLVL_RECOV(_NI_SCOPE, name, format, ##__VA_ARGS__)
#define _NTRR_ARGS(name, tr, recov_type, recov_task_id, format, ...) __NLVL_RECOV_ARGS(_NT_SCOPE, name, tr, recov_type, recov_task_id, format, ##__VA_ARGS__)
#define _NIRR_ARGS(name, tr, recov_type, recov_task_id, format, ...) __NLVL_RECOV_ARGS(_NI_SCOPE, name, tr, recov_type, recov_task_id, format, ##__VA_ARGS__)

/************************** Recovery External API *****************************/
/* Allocate and create new recovery persistent data (one for each raid) */
int  nvmeibc_recoveries_create(struct nvmeibc_raid_topo_persistent *hdr);
void nvmeibc_recoveries_destroy(struct nvmeibc_raid_topo_persistent *hdr);

/* Start recovery of protection raid described in Toma message. Start and end are in blocksets units (rlba/LOCKSET_SLICES units). Note: This function runs in atomic context. No vmallocs! */
// Sources of recovery start: Toma / ioctl / chained recovery / DPlib caller
int nvmeibc_recovery_start(      struct nvmeibc_subscription_ctx *tr, struct nvmeibc_raid1 *r1, struct nvmeibt_client_recovery_start_pl *rpl, int praid_version, bool is_silent);
int nvmeibc_recovery_start_ioctl(struct nvmeibc_subscription_ctx *tr, struct nvmeibc_raid1 *r1, struct nvmeibt_client_recovery_start_pl *rpl);
int nvmeibc_recovery_start_ext(  struct nvmeibc_subscription_ctx *tr, struct nvmeibc_raid1 *r1, struct nvmeibt_client_recovery_start_pl *rpl);

/* Handles a single request (PING/ABORT) to concrete task */
void nvmeibc_recovery_handle_request(        const struct nvmeibc_subscription_ctx *tr, enum NVMEIBT_CLIENT_MSG_TYPES msg_type, const struct nvmeibt_client_recovery_taskid_pl *ri);

// Handles a single request (PING/ABORT) to a 'ri task or all tasks (ri == NULL).
void nvmeibc_recoveries_handle_ioctl_request(const struct nvmeibc_subscription_ctx *tr, enum NVMEIBT_CLIENT_MSG_TYPES msg_type, const struct nvmeibt_client_recovery_taskid_pl *ri);
void nvmeibc_recoveries_cancel(              struct nvmeibc_raid_topo_persistent *hdr); /* Externally cancels all running recoveries */

//helper fuction to print recovery information to buffer
int nvmeibc_recovery_info_to_str(struct nvmeibc_recovery *recov, bool with_stats, char *buf, int len);
int nvmeibc_recovery_stats_to_str(struct nvmeibc_recovery *recov, char *buf, int len);

void nvmeibc_recovery_stats_clear(struct nvmeibc_recovery *recov);
void nvmeibc_recovery_set_num_sw(        struct nvmeibc_recovery *recov, u32 n);	// n==0 means default value
void nvmeibc_recovery_set_max_batch_size(struct nvmeibc_recovery *recov, u32 n);	// n==0 means default value

#endif // NVMEIBC_RAID_RECOVERY
