#ifndef NVMEIBT_TOPOLOGY_H
#define NVMEIBT_TOPOLOGY_H
/* Simulator of the appropriate toma file which stores the configuration and
   topology of all the volumes, inside real toma's structs */
#include <pthread.h>
#include "./../nvmeib_common_all.h"						// Must be first include
#include "../toma/clnt/nvmeibt_client_protocol.h"		// Use real Toma structures (as encoded in clnt-toma messaging protocol)
#include "./../mgmt/nvmeibm_conf_db.h"					// Points to mongo-db

/******************************************************************************/
// Additional methods for topology of raid1, used by unitest environment
#define r1uuid(r1) ((r1)->header.uuid)
void tTopoOfPraid_init(   struct tTopoOfPraid* R, int praid_version, int nMirroring, const char *praidUUID, const char*segsUUIDs[/*nMirroring*/], const int segsDiskIDs[/*nMirroring*/], lock_server_type_e type, int max_n_owners);	// Constructor for the above: 'nMirroring' typically 2, 'segsUUIDs' is array of UUID's of the segments participating in the raid and their disk (node) id's
void tTopoOfPraid_incVer( struct tTopoOfPraid* R);		// When topology changes, raid version monotonically increases
bool tTopoOfPraid_verify_identical_locks(const struct tTopoOfPraid* R);	// Verify that both segments are registered with identical lock id (even though they are registered with different tomas)
int  tTopoOfPraid_gen_num_non_readble_segs(const struct tTopoOfPraid* R);
int  tTopoOfPraid_get_size(const struct tTopoOfPraid* R);	// Size of the payload in the message to store the topology
void tTopoOfPraid_force_lock_on_read(struct tTopoOfPraid* R, bool should_lock);	// Todo: unify with switch topo's (this is a private case of one of switch topos
void tTopoOfPraid_getdisks_by_order(const struct tTopoOfPraid* r1, int disk_ids[N_MAX_RAID_SLICE_LEN]); /* For each seg in raid return its disk ID*/
/* Get the indices of segments and indicies of disks participating in Raid-1, according to their status - dead/alive */
void tTopoOfPraid_getdisks_by_status(const struct tTopoOfPraid* r1, int liveSegInd[N_MAX_RAID_SLICE_LEN+1], int deadSegInd[N_MAX_RAID_SLICE_LEN+1],
																    int liveDskInd[N_MAX_RAID_SLICE_LEN+1], int deadDskInd[N_MAX_RAID_SLICE_LEN+1]);
void tTopoOfPraid_update_segs_by_access_mode(struct tTopoOfPraid* r1, const struct nvmeibc_locks_scheme_conf *vol_locks_scheme);

/******************************************************************************/
struct tTopoOfRaid0Chunk{  								// Toma topology of RaidX+0 (10, 40, 50, 60 : stripped array of protection raids)
	int stripeWidth;									// Amount of 'tTopoOfPraidSegment'. Raid1 has stripeWidth=1, 2-mirroring, bunch of disks has width-1 1-mirroring
	struct tTopoOfPraid *raids;							// Array of raid1's.
};

struct tTopoOfVolume{  									// Toma topology (state of the configuration) of block device / a signle volume
	int nChunks;										// Amount of 'chunks'
	struct tTopoOfRaid0Chunk *chunks;					// Array of chunks's.
	u64 reservation_version;							// Reservation version given by client if > toma update toma to client and return toma, if client == -1 ignore and return toma
	int	version;										// Each time management updates the volume this number grows
	const struct disk_range *segs;						// Original configuration comming from the management mongo-db. Toma cannot change it
	int n_segs;											// Amount of segments in the volume (sum of all segments in all raind1's)
	const char* uuid;									// UUID of volume, from original configuration comming from the management. Toma cannot change it
	const struct nvmeibc_locks_scheme_conf*locks_scheme;// How client, does the locking. Pointer to mongo-db simulator
};
void tTopoOfVolume_destroy(	  struct tTopoOfVolume* V);	// Destructor
void tTopoOfVolume_incVer(	  struct tTopoOfVolume* V);	// Increase the version of all raid1s in the volume. As If client was down and missed updated tomas topologies on all the segments
bool tTopoOfVolume_isMirrored(const struct tTopoOfVolume* V);	// True if Raid1 or 10, False for Raid0 or Jbod
bool tTopoOfVolume_isStriped( const struct tTopoOfVolume* V);	// True if Raid0 or 10, False for Raid1 or Jbod
struct tTopoOfPraid* tTopoOfVolume_getRaid1(struct tTopoOfVolume* V, int i);	// Get the i'th raid-stripe of the volume (takes into account amount of chunks and stripes). On illegal index returns NULL

struct tTopoOfNVMesh { 									// Global topology of all the system (NVMesh) as generated by Toma leader
	int nVolumes;										// Amount of volumes and thin volumes
	struct tTopoOfVolume vols[MAX_VOLUMES_IN_NVMESH];	// Array  of volumes
	pthread_mutex_t lock;									// Lock to change topology atomically. Todo: make it per-protection-raid
};

void tTopoOfNVMesh_incVer(struct tTopoOfNVMesh* gTopo);
const struct tTopoOfPraid* tTopoOfNVMesh_find_r1_by_seg_uuid( const struct tTopoOfNVMesh *gTopo, const char* seg_uuid, const struct tTopoOfVolume **tv_ptr, int*segInd);
const struct tTopoOfPraid* tTopoOfNVMesh_find_r1_by_praid_uuid( const struct tTopoOfNVMesh *gTopo, const char* praid_uuid, const struct tTopoOfVolume **tv_ptr);
     struct tTopoOfVolume* tTopoOfNVMesh_find_carrier_by_uuid(const struct tTopoOfNVMesh *gTopo, const char* vol_uuid);
const struct tTopoOfVolume*tTopoOfNVMesh_find_vol_by_praid(   const struct tTopoOfNVMesh *gTopo, const struct tTopoOfPraid *pr);

struct disk_sgmnts{
	const struct disk_range* sgmnts[NVMESH_MAX_SEG_PER_VOLUME];
};

struct disk_sgmnts tTopoOfNVMesh_list_disk_sgmnts(const struct tTopoOfNVMesh* gtopo, u32 disk_id, bool ec_sgmnts_only); //returns disk segments which belongs to the disk_id

#endif // NVMEIBT_TOPOLOGY_H


