// For documentation, see Header in H file
/*****************************************************************************/
// Includes
#include "nvmeibm_mgmt_simu.h"
#include "nvmeibm_mcs_simu.h"			// Send msg to client through mcs

/******************** Simulator of management alerts log **********************/
void mgmt_alerts_log_simu_insert(struct mgmt_alerts_log_simu* s, char *level, char *header, char *message) {
	s->expected_header  = header;
	s->expected_level   = level;
	s->expected_message = message;
	s->expector_set = true;
}

void mgmt_alerts_log_simu_verify_msg(struct mgmt_alerts_log_simu* s, struct nvmeib_mcs_log *msg) {
	// All expectors must be set to values before verifying ("" is valid)
	// Sent messages must have a '\0' in the last char
	BUG_ON(strncmp(msg->level  , s->expected_level  , sizeof(msg->level  )-1));
	BUG_ON(strncmp(msg->header , s->expected_header , sizeof(msg->header )-1));
	BUG_ON(strncmp(msg->message, s->expected_message, sizeof(msg->message)-1));
	mgmt_alerts_log_simu_insert(s, NULL, NULL, NULL);
	s->expector_set = false;
	s->msg_counter++;
}

/********************* Simulated message queue in mgmt ************************/
void mcs_message_queue_init(struct mcs_message_queue* mq)
{
	spin_lock_init(&mq->guard);
	mq->should_store = false;
	mq->message = NULL;
	mq->len = 0;
}

// Called before destroy and after flushing a message
static void __free_mcs_message_queue(struct mcs_message_queue* mq)
{
	sim_kfree(mq->message);
	mq->message = NULL;
	mq->len = 0;
}

void mcs_message_queue_destroy(struct mcs_message_queue* mq)
{
	__free_mcs_message_queue(mq);
}

void mcs_message_queue_activate(struct mcs_message_queue* mq, bool allow_override)
{
	BUG_ON(mq->message);			// Coz we support only 1 message
	spin_lock(&mq->guard);
	mq->should_store = (allow_override ? 3 : 1);
	spin_unlock(&mq->guard);
}

int mcs_message_queue_flush_n_stop(struct mcs_message_queue* mq)
{
	int rv = -EINVAL;
	if (mq) {
		spin_lock(&mq->guard);
		if (mq->message) {
			rv = mcs_send_raw_msg_buf_unsafe(mq->mcs, mq->message, mq->len);
			__free_mcs_message_queue(mq);
		} else {
			_NE_dmesg(error_mgmt_simu_mcs_message_queue_flush_n_stop, "No message stored in the queue, releasing mechanizm");
			rv = -ENODEV;
		}
		mq->should_store = false;
		spin_unlock(&mq->guard);
	} else
		_NE_dmesg(error_1_mgmt_simu_mcs_message_queue_flush_n_stop, "mcs_message_queue is uninitialized");
	return rv;
}

bool mcs_message_queue_try_insert(struct mcs_message_queue *mq, char *buf, unsigned len)
{
	bool rv = false;
	spin_lock(&mq->guard);
	if (!mq->should_store)
		goto _out;
	if (mq->should_store > 2) {			// Allow override
		sim_kfree(mq->message);
	} else {
		BUG_ON(mq->message); 			// We support only one
	}
	mq->message = sim_kzalloc(len, GFP_KERNEL);
	memcpy(mq->message, buf, len);
	mq->len = len;
	rv = true;
_out:
	spin_unlock(&mq->guard);
	return rv;
}

/********************* Simulator of management component **********************/
void mgmt_simu_verify_num_alerts(struct mcs_simu* mcs, int i) {
	struct mgmt_alerts_log_simu* s = &mcs->s;
	BUG_ON(i != s->msg_counter);
}

void mgmt_simu_expect_alert(struct mcs_simu* mcs, char *level, char *header, char *message) {
	struct mgmt_alerts_log_simu* s = &mcs->s;
	BUG_ON(s->expected_header || s->expected_message || s->expected_level);
	mgmt_alerts_log_simu_insert(s, level, header, message);
}

void mgmt_simu_init(struct mgmt_simu* mgmt, const struct mongo_db_simu *mdb) {
	int i;
	memset(mgmt, 0, sizeof(*mgmt));
	for (i = 0; i < NVMESH_N_MAX_CLIENTS; ++i) {
		mcs_message_queue_init(&mgmt->mcs[i].mq);
		mgmt->mcs[i].inst_id = i;
	}
	mgmt->mdb = mdb;
}

void mgmt_simu_destroy(struct mgmt_simu* mgmt) {
	int i;
	for (i = 0; i < NVMESH_N_MAX_CLIENTS; ++i) {
		mcs_message_queue_destroy(&mgmt->mcs[i].mq);
	}
	mgmt->mdb = NULL;
}

void mgmt_init_expected_counters(struct mcs_simu* mcs)
{
	//AK: TODO - make the dafault value generated by the schema builder
	mcs->expected_messageTypeVersion = 1;
	mcs->expected_reportID = -1;
	mcs->expected_sequence_num = -1;
	mcs->expected_client_token = -1;
	mcs->expected_keepalive_interval = 5;
	mgmt_clear_ka_callback(mcs);
}

void mgmt_set_ka_callback(struct mcs_simu* mgmt, mgmt_cb_func on_ka_cb, void* ctx)
{
	mgmt->on_ka_cb = on_ka_cb;
	mgmt->ka_cb_ctx = ctx;
}

void mgmt_clear_ka_callback(struct mcs_simu* mgmt)
{
	mgmt_set_ka_callback(mgmt, NULL, NULL);
}
/*****************************************************************************/
// EOF.
