/*
* SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
* SPDX-License-Identifier: Apache-2.0
*/

#ifndef NVMEIBT_PARAMS
#define NVMEIBT_PARAMS

// Misc compile-time parameters
#define NVMEIBT_MAX_N_NODES 256
#define NVMEIBT_MAX_N_BLOCK_DEVICES 20*1000
#define NVMEIBT_MAX_N_NICS_PER_NODE 10
#define NVMEIBT_MAX_N_NICS (NVMEIBT_MAX_N_NODES * NVMEIBT_MAX_N_NICS_PER_NODE)

#define NVMEIBT_MAX_N_DISKS_PER_NODE 60
#define NVMEIBT_MAX_N_DISKS ((NVMEIBT_MAX_N_NODES * NVMEIBT_MAX_N_DISKS_PER_NODE) / 2)

#define NVMEIBT_MAX_N_SEGMENTS_IN_PRAID 12
#define NVMEIBT_MAX_N_DISK_SEGMENTS (NVMEIBT_MAX_N_BLOCK_DEVICES * NVMEIBT_MAX_N_SEGMENTS_IN_PRAID * 2)

#define NVMEIBT_MAX_STRIPE_WIDTH_PER_CHUNK 300
#define NVMEIBT_MAX_N_CHUNK_PER_BLOCK_DEVICE NVMEIBT_MAX_N_NODES

#define NVMEIBT_MAX_N_CHUNKS NVMEIBT_MAX_N_DISK_SEGMENTS

#define NVMEIBT_MAX_N_CLIENTS_PER_NODE 30000
#define NVMEIBT_MAX_N_CLIENTS_PER_DISK_SEGMENT 10000
#define NVMEIBT_MAX_N_PRAIDS (NVMEIBT_MAX_N_DISK_SEGMENTS / 4)
#define NVMEIBT_MAX_N_PORTS_PER_NIC 16
#define NVMEIBT_MAX_N_GIDS_PER_PORT 16

#define MAX_N_RUNNING_COLD_RECOVERY_PER_NODE 5	// They should be short, and quickly start the seg/praid life-cycle

#ifndef TOMA_SIMULATOR_SANDBOX
	#define MAX_TIME_BETWEEN_CHANGED_SEGMENT_REPORTS_NSECS  SEC_TO_NSEC(1)
	#define MIN_NSEC_BETWEEN_REBUILD_PROGRESS_REPORTS_NSECS SEC_TO_NSEC(2)
#else
	#define MAX_TIME_BETWEEN_CHANGED_SEGMENT_REPORTS_NSECS  MSEC_TO_NSEC(100)	// Todo: make a constant sandbox factor to run everything xN times faster
	#define MIN_NSEC_BETWEEN_REBUILD_PROGRESS_REPORTS_NSECS MSEC_TO_NSEC(200)
#endif
#define MAX_WAIT_FOR_CLIENT_REGISTRANT_TIMEOUT_SEC   6
#define MAX_WAIT_FOR_CLIENT_REGISTRANT_TIMEOUT_NSEC  SEC_TO_NSEC(MAX_WAIT_FOR_CLIENT_REGISTRANT_TIMEOUT_SEC)

/********** GPT **************/
#define GPT_SIGNATURE 								(uint64_t)0x5452415020494645        /*"EFI PART"*/
#define DISK_METADATA_SIGNATURE 					(uint64_t)0x1234567898765432
#define DISK_METADATA_PARTITION_NAME 				"Disk_Metadata"
#define NVMESH_JOURNAL_PARTITION_NAME				"excelero_journal_data"
#define NVMESH_SERJIO_DB_PARTITION_NAME			"excelero_serjio_db"
#define NVMESH_METADATA_PARTITION_NAME			"excelero_metadata"

#define GPT_MAX_PARTITION_NAME_LENGTH 			36
#define MAX_NUM_GPT_ENTRIES						8192
#define LARGE_GPT_MAX_NUM_GPT_ENTRIES			8192
#define MAX_NUM_GPT_ENTRIES_FOR_BACKWARDS_COMPATIBILITY		(MAX_NUM_GPT_ENTRIES < 1024 ? 1024 : MAX_NUM_GPT_ENTRIES)

#ifndef TOMA_SIMULATOR_SANDBOX
#define METADATA_PARTITION_RATIO				0.005 /*0.5% from the disk size*/
#else
#define METADATA_PARTITION_RATIO				0.15 /* 15% of the disk size for the simulator sandbox with small disks */
#endif

#define MBR_SIZE								512
#define UEFI_MIN_GPT_ENTRY_SIZE					128

#endif /* NVMEIBT_PARAMS */
