before_script:
- echo "Starting CI"
- whoami
- export TEST_WITH_BRANCH="master"
- export TAGS="ci"
excelero_ci_job:
 script:
 - pwd
 - echo $CI_PROJECT_DIR
 - export REPO_TYPE=ssda
 - export CURDATE=$(date +%Y-%m-%d_%H-%M-%S)
 - export ARCHIVE_FOLDER="/opt/infrastructure/orchestrator/public/projectTar"
 - export ARCHIVE_FILE="build_id_"$CI_BUILD_ID"_"$CURDATE".tar"
 - export ORCHESTRATOR_IPORT='http://orchestrator.excelero.com:4010'
 - tar -cvf "$ARCHIVE_FOLDER/$ARCHIVE_FILE" -C $CI_PROJECT_DIR .
 - echo $?
 - echo "$ARCHIVE_FOLDER/$ARCHIVE_FILE"
 - python -u /etc/opt/CiExecuter.py # set location to run file from (not in repo)
 - exit $?

 only:
 - /DiSaBlE-Ci/
   #- schedules
