[tool.poetry]
name = "nvmesh"
version = "3.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

# The "tool.poetry.source" is a project-wide setup. Although one can define multiple poetry sources,
# they will not fallback to the follow-up poetry sources if it is due to connection failures. The other
# poetry sources are referenced only when a package cannot be found in earlier poetry sources.
#
# To select poetry dynamically, we can either add sources based on their availability, or remove
# sources if they are not reachable. We chose the latter because we assume NVIDIA internal PyPI repository
# is available for our internal lab and dev use case, and we optimize for this case. For external use
# cases(e.g., public cloud) where NVIDIA internal PyPI repository is not reachable, we dynamically remove
# the NVIDIA internal PyPI repository from poetry, thus, fallback to the default pypi.org repository. The
# poetry lock regenerate cost is only charged to the pypi.org path.

# NVIDIA combined PyPI (public mirror + nv-shared-pypi-local).
[[tool.poetry.source]]
name = "nv-shared"
url = "https://urm.nvidia.com/artifactory/api/pypi/nv-shared-pypi/simple"
priority = "primary"

[tool.poetry.group.pet.dependencies]
pyelftools = "^0.32"
pydantic = "^2.12.5"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
confluent-kafka = "2.1.1"
ipython = "7.34.0"
pyyaml = "^6.0.2"
paramiko = "^3.5.0"
requests = "^2.32.5"
traitlets = "^5.14.3"
urllib3 = ">=2.6.3,<3"

[tool.poetry.group.compile]
optional = true

[tool.poetry.group.compile.dependencies]
pyinstaller = "^6.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
