sonar.projectKey=NBUSW_NVMesh_NVMesh_excelero
sonar.qualitygate.wait=true
sonar.host.url=https://sonar.nvidia.com/

sonar.sources=.
sonar.coverage.exclusions=**/Documentation/**,**/.cache/**,**/examples/**,kernels/**,**/build/**,**/*unitest/**,testing/**,perfTest/**,**/*Test*/**,**/test*/**,tools/**,RPM/**
sonar.exclusions=kernels/**,**/build/**,**/*unitest/**,testing/**,perfTest/**,**/*Test*/**,**/test*/**,management_cm/scaleSimulators/**,tools/**,RPM/**,scripts/target/**,mlnx_fw/**,docker_driver/**,**/test_*.c,**/ibcm_test/**
sonar.test.inclusions=testing/**,perfTest/**,**/unitest/**,**/core_unitest/**

