#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0


source .config

if [ -z "$toma_mode" ]; then
	toma_mode="release"
fi

# Note we have 2 options due to an really old design
# 1) Only include static files here (not compiled ones).+
# 2) Can include both static and compiled files
# The differnce is that the on in 2) are used by mkinstallscript which compilator is using.

# Only include static files here (not compiled ones).
base_transfer_list="system.d/nvmeshagent.service \
        system.d/nvmeshcm.service \
        config/nvmesh.conf \
        config/nvmesh.conf.d/00-readme.conf \
        management_cm \
		bin/nvmesh_configure_management_server \
		bin/nvmesh_configure_nics"

# Can include both static and compiled files
base_tools_transfer_list="dist/pytools \
        scripts/target/nvme-cli"

# Can include both static and compiled files
target_transfer_list="srv/nvmeibs.ko* \
			toma/bin/*/nvmeibt_toma \
			toma/scripts/toma_persistence_to_JSON.sh	\
			toma/scripts/JSON_to_toma_persistence.sh	\
			toma/bin/*/nw_*.so \
			toma/bin/*/nvmeibt_toma_src_tar.pgp"

# Can include both static and compiled files
optional_target_transfer_list="tools/toma_rpc/toma_rpc \
            tools/toma_rpc/toma_link"

# Can include both static and compiled files
client_transfer_list="clnt/atom/nvmeiba.ko* \
			clnt/nvmeibc.ko*"

# Can include both static and compiled files
if [ -n "$NCONFIG_MODVERSIONS" ]; then
	client_transfer_list+=" symvers/symvers.ko*"
fi

# Can include both static and compiled files
common_transfer_list="common_public/*.ko* \
			common_public/*.c \
			common_public/*.h \
			common_public/Makefile \
			common_public/bnxt/*.c \
			common_public/bnxt/Makefile \
			common/nvmeib_common.ko* \
			keeper/nvmeib_keeper.ko* \
			keeper/*.c \
			keeper/*.h \
			softiwarp \
			tools/trace_daemon_2.0/trace_daemon \
			tools/trace_daemon_2.0/run_trace_daemon.sh \
			tools/pipe_tracer/build/bin/nvmeib_pipe_tracer \
			dictionaries.tar.gz \
			perfTest/io_stress/scan_locks/scan_locks_ec "

optional_common_transfer_list="tools/traces_post_processor/cpager \
			tools/nvmesh_netlink.py \
			tools/read_dwarf.py \
			tools/nvmesh_memmgr_monitor.py \
			tools/nvmesh_metrics.py \
			tools/nvmesh_client_upgrade_breakdown.py \
			tools/infra_shared/infra_shared.so \
			tools/the-calculator.py"

# Can include both static and compiled files
common_scripts_transfer_list="tools/dictionary.json \
			tools/traces_post_processor/pager.py \
			scripts/common/nvmesh_set_irq_affinity_common \
			scripts/common/nvmesh_set_tcp_affinity \
			scripts/common/nvmesh_set_tcp_affinity_dbg \
			scripts/common/nvmesh_set_irq_affinity \
			scripts/common/nvmesh_ib* \
			scripts/common/export_vdisk.sh \
			scripts/common/nvmesh_snapshot_logs.sh \
			scripts/common/nvmesh_install_ib_core_mod.sh \
			tools/traces_post_processor/pager-profiler.py \
			tools/traces_post_processor/formatters/formatters.py"

# Can include both static and compiled files
if [ -n "$NCONFIG_BNXT" ]; then
	common_transfer_list+=" \
		common_public/bnxt/*.ko* \
		common_public/bnxt/*.h"
fi

if [ -n "$NCONFIG_IB_CORE_MOD_DIR" ]; then
	common_transfer_list+="ib_core_modules.tar.gz "
fi

# Only include static files here (not compiled ones).
target_scripts_transfer_list="init.d/nvmeshtarget \
			system.d/nvmeshtarget.service \
			system.d/nvmeshtoma.service \
			bin/nvmesh_target \
			upgrade_scripts/nvmesh-target \
			scripts/target/nvmesh_auto_bind_nvme \
			scripts/target/nvmesh_auto_bind_back_nvme \
			scripts/target/nvme-cli \
			scripts/target/nvme_orphans.sh \
			scripts/target/google_uuids.sh \
			config/target_devices.conf \
			toma/toma_trace.config \
			toma/toma.d/default.rpc \
			toma/toma.d/nvmesh_oci.rpc \
			toma/toma.d/nvmesh_gcp.rpc	\
			toma/toma.d/nvmesh_gfn.rpc \
			toma/toma.d/nvmesh_xpnd_jour.rpc \
			examples/auto_takeover_drives_spec_example"

# Only include static files here (not compiled ones).
client_scripts_transfer_list="init.d/nvmeshclient \
				init.d/nvmeshclient \
				init.d/nvmesh_util \
				system.d/nvmeshclient.service \
				system.d/nvmeshagent.service \
				system.d/nvmeshcm.service \
				system.d/nvmeshtrace@.service \
				modprobe.d/nvmesh.conf \
				modprobe.d/nvmesh_pre2.6.0.conf \
				modprobe.d/nvmesh_oci.conf \
				modprobe.d/nvmesh_dpu.conf \
				modprobe.d/nvmesh_gcp.conf	\
				modprobe.d/nvmesh_gfn.conf	\
				modprobe.d/nvmesh_xpnd_jour.conf \
				modprobe.d/nvmesh_gfn_ms1.conf \
				modprobe.d/nvmesh_gfn_ms2.conf \
				depmod.d/zz02-nvmesh.conf \
				sysctl/60-nvmesh.conf \
				bin/nvmesh_client_instance_do \
				bin/nvmesh_clnt_shutdown.py \
				bin/nvmesh_update \
				scripts/client/nvmesh_udev_utils.py \
				scripts/client/nvmesh_spdk_wrapper.py \
				scripts/client/nvmesh_client_upgrade.py \
				config/nvmesh.conf \
				config/nvmesh.conf.d/00-readme.conf \
				management_cm \
				upgrade_scripts/nvmesh-client \
				rules.d/60-nvmesh.rules \
				clnt/block/datapath_utils_generic/profiling/nvmesh_profiling.py"

toma_symbols="toma/bin/*/nvmeibt_toma.with_symbols"

