/*
* SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
* SPDX-License-Identifier: GPL-2.0-only OR Apache-2.0
*/

#ifndef NVMEIBC_TOPOLOGY_H
#define NVMEIBC_TOPOLOGY_H
/* 1. Manages toma subscriptions to disk segments and their transport layer
 * opque resources.
 * 2. Updates topology according to messages received by toma During Attach/
 * Detach/Reconf - convert configuration to topology during init or
 * reconfiguration and kill topologies upon dettach
 * 3. Reposnd with topology update to pause and cont on disk (arrive as
 * interrupts).
 * 4. Handling reconfiguration - Working close with toma to make transition from
 * previous configuration to the next. If few segments relocate this transition
 * is not atomic and many tomas are involved
 */
#include "../toma/clnt/nvmeibt_client_protocol.h"
#include "datapath_utils_generic/nvmeibc_block_dp_lock_server.h"
#include "nvmeib_metrics.h"
#include "datapath_utils_generic/profiling/nvmeibc_block_dp_profiling_generic.h"
#include "block/recovery/nvmeibc_block_sync_profiling_stages.h"
#include "main/utils/nvmeibc_main_block_gen_work_sched.h"
#include "utils/nvmeib_jdr/nvmeib_txt.h"
#include "utils/nvmeib_jdr/nvmeib_jdr.h"
#include "block/dp_topology_traits.h"

/************ Todo: Move the generic stuff below to somwhere else *************/
#define UUID_LEN  (sizeof(((struct nvmeibt_client_topo_disk_segment*)0)->uuid))	// Todo: Remove it, use centralized define
#define UUID_COPY(dst,src)		strcpy((dst),(src));// Todo: Remove it, use centralized define
#define ARE_UUIDS_EQ(u1, u2) (!strncmp(u1, u2, UUID_LEN))
u32 ror32_width(u32 bm, u32 shift, u32 width);	// Handling segments bitmaps
u32 rol32_width(u32 bm, u32 shift, u32 width);

/******************************************************************************/
struct nvmeibc_topology;	// Forward declaration
struct nvmeibc_idisk;		// Forward declaration
#include "block/controlpath/nvmeibc_b_cp_topo_seg_on_active.h"

/************ Implementation of block device allocation **********************/
enum nvmeibc_segment_shared_memo {			// Few copies of same segment share info. Only the last copy (last user) can free the shared memo
	SEG_SHARED_MEMO_NONE		= 0,		// Segment does not own any shared info (initialized to zero)
  //SEG_SHARED_MEMO_RAID_VER                // Segment is the last user of registration on specific praid version (changes even on switch topo when lock-id is preserved). Example: Client Recovery job
	SEG_SHARED_MEMO_REGISTRAT 	= 1,		// Segment is the last user of registration info (lock id etc)
	SEG_SHARED_MEMO_SUBSCRIPT 	= 2,		// Segment is the last user of subscription info (toma_reg, transport layer memory, etc)
	SEG_SHARED_MEMO_ALL 		= (SEG_SHARED_MEMO_SUBSCRIPT|SEG_SHARED_MEMO_REGISTRAT),
} __attribute__ ((packed));

enum nvmeibc_segment_registration_status {
	SEG_REGSTATUS_EMPTY         = 0,		// Not registered vs toma. Must be 0
	SEG_REGSTATUS_TOMA_OK       = 1,		// Registered vs toma
} __attribute__ ((packed));
#define is_seg_active(seg) ((seg).registration_status != SEG_REGSTATUS_EMPTY)

/* A single allocation of a range of addresses on a physical single disk.
 * This range of drive LBAs is continous on that drive
 * (in contrast to volume LBAs). */
struct nvmeibc_disk_segment {
	struct nvmeibc_idisk *disk;             // Physical disk
	char uuid[NVMEIB_GID_STR_MAX];          // Use only 36 characters + \0. Defined 40 for padding. Unique id for each segment generated by the management system. Each block device registered to this segment will have identical field
	u64 first_lba, length;                  // Where this segment resides on the physical disk (units of blocks). (Unrelated to volume virtual adresses)
	u32 dbg_uuid;							// The de-facto unique part of the segment uuid, for tracing.
	u32 max_dma_size;                       // Parameter of access to physical disk. In units of blocks
	u32 sw_md_size;                         // Metadata size, equal to disk->md_size*(nvmesh_sector_size-disk_sector_size) if available, else NVMEIBC_SGMNT_DEFAULT_MD_SIZE
	struct lock_ownership_map lmap;         // Mapping
	struct nvmeibc_chunk *chunk;            // Each disk segment points back to the chunk it belongs to.
	struct nvmeibc_subscription_ctx *toma_reg;				// A handle to the toma_reg struct associated with this segment, used for sending TOMA messages related to it
	struct nvmeibc_profiler *lock_operation_profiler;
	struct nvmeibc_profiler *disk_operation_profiler;
#if defined(NVMEIBC_ENABLE_PER_VOLUME_STATS)
	struct nvmeib_io_stats *v_disk_stats;	// Shared by all segs of the same volume on the same disk
#endif
	enum NVMEIBT_PRAID_IS_PRIMARY_OWNER_LOCK_MOVING sync_safety;// Lock-Topo, Todo, move to praid
	bool is_safe_for_view_lock;				// Todo: move to praid, Id safe to view locks on read (instead of acquiring locks).
	enum NVMEIBTC_DS_MODE toma_acm;         // Seg-Topo: Dead - No IO to disk, Write only - Disk in recovery, data might be not valid. You can write new data but not read old corrupted data. RW - read and write sicne data is OK
	enum nvmeibc_segment_shared_memo shared_own;
	enum nvmeibc_segment_registration_status registration_status;			// Marks whether has successfully registered with TOMA and is now active
#ifndef DP_LIB								// Rest of the fields are needed for control path only
	struct nvmeibc_disk_segment *replacement;// When reconfiguring the system a segment temporary holds pointer to its replacement upgrade or downgrade
	struct nvmeibc_segment_on_active	on_active;	// A TOMA message to incorporate into the topology upon activation of the segment plus any further info the processing needs from the msg callback context
	//void *per_reg;							// Unused, a place holder of information stored per registration
#endif
};
void nvmeibc_segment_clear_old_topo_upon_unreg(struct nvmeibc_disk_segment *seg);	// Upon dup topo + unreg: Clear stuff of old topo.
void nvmeibc_segment_clear_new_topo_upon_unreg(struct nvmeibc_disk_segment *seg);	// Upon dup_topo + unreg: Clear stuff of new topo.
#define handle_of(seg) handle_of_subscription_ctx((seg)->toma_reg)
#define nvmeibc_disk_seg_to_bdev(seg)  nvmeibc_block_nt_to_b(seg->chunk->topology->nt)
static inline bool nvmeibc_is_readable_acm(enum NVMEIBTC_DS_MODE toma_acm) {
	return (toma_acm == NVMEIBTC_DS_MODE_RW || toma_acm == NVMEIBTC_DS_MODE_W_NO_DIRTY);
}
static inline bool nvmeibc_is_readable(const struct nvmeibc_disk_segment *ds) { return nvmeibc_is_readable_acm(ds->toma_acm); }

static inline int nvmeibc_sgmnt_sw_md_size(const struct nvmeibc_disk_segment *ds)
{
	return ds->sw_md_size;
}

bool nvmeibc_should_use_view_lock(const enum nvmeib_block_io_op, const struct nvmeibc_disk_segment *seg);	// Does this raid require a read lock for read (TODO: Degraded EC might "think" it needs but practically it might not - read a single block to a drive that is not degraded in a degraded p-raid)

enum nvmeib_io_type_permission {			   // The limitations on protection raid.
	NVMEIB_IO_TYPE_PERMIT_NEVER     		= -10, // Nothing can be done, IO was never enabled since the first attach. Volume did no IO
	NVMEIB_IO_TYPE_PERMIT_NONE_SUS			=  -7, // Nothing can be done, and protection raid topology is irrelevant (detaching/suspended)
	NVMEIB_IO_TYPE_PERMIT_NONE_INV			=  -2, // Nothing can be done, Toma/Transport gave us invalid topology, disabling al IO's intentionally
	NVMEIB_IO_TYPE_PERMIT_NONE_ERR			=  -1, // Nothing can be done now (Topology is good, but clnt is not registered properly to pr), hopefully soon IO will enable
	NVMEIB_IO_TYPE_PERMIT_NO_IO 			=   1, // No BIO allowed (only recoveries= Hot/Cold/Dbits/Etc...)
	NVMEIB_IO_TYPE_PERMIT_NO_RM_IO			=   2, // No BIO allowed (only recoveries= Hot/Cold/Dbits/Etc...) Due to reservation version mismatch
	NVMEIB_IO_TYPE_PERMIT_RDONLY			=   3, // BIO Read-only + recoveries
	NVMEIB_IO_TYPE_PERMIT_ALL_NO_PROTECTION	=   4, // Permit all IO's, good path IO state for some period of time.
	NVMEIB_IO_TYPE_PERMIT_ALL				=   5  // Permit all IO's, default good path IO state
};

bool nvmeibc_has_io_permission_changed(const enum nvmeib_io_type_permission old_perm,
				       const enum nvmeib_io_type_permission new_perm);

const char * nvmeib_io_type_permission_to_string(enum nvmeib_io_type_permission val);
const char *nvmeib_io_type_permission_to_string_short(enum nvmeib_io_type_permission val);

/********************************* Roles **************************************/
/* Describes roles of segments in specific blockset in a given topology, bit [i]
   represents NOT seg[i] but rather the segment which is i'th from slice start
   Assists datapath in with fast calculations and used for unitests */
struct nvmeibc_roles_bmps {
	struct {			  // Raid configuration (identical to all roles), kept here for optimization purposes, even though only a single copy is needed
		roles_bmp_t data; // Example: R6=8+2 .data=0xFF .pari= 0x300, .all=0x3FF/
		roles_bmp_t pari; // Data bits = 0 parity = 1
		roles_bmp_t all;  // Data bits = 1 parity = 1
	} raid;

	sgmnts_bmp_t data_sgmnts;   // Example: R6=8+2, Slice start on seg2 (shift=2). .data_sgmnts = 0x3FC, .pari_sgmnts=0x3
	sgmnts_bmp_t pari_sgmnts;   // Actual parity segments for given shift

	roles_bmp_t rw;				// Topology RW roles
	roles_bmp_t wp;				// Topology W+ roles
	roles_bmp_t w;				// Topology Writeable non readable (W|W-)
	roles_bmp_t wm;				// Topology W- roles
	roles_bmp_t dead;			// Topology dead roles
	roles_bmp_t readable;		// Topology RW | W+ roles: Source can be trusted.
	roles_bmp_t readable_sync;	// == ~(wm|dead). During sync, 'W' can be read, even with dirty bit, just to compare to expected data (avoid unnecessary write). But it is not a valid source of data only if dbit does not exist

	roles_bmp_t dbits_off_mask; // == .w,    A bitmap representing a set of roles writing to which may turn off dirty bits
	roles_bmp_t dbits_on_mask;  // == .dead, A bitmap representing a set of roles writing to which may turn on  dirty bits

	roles_bmp_t local_access;	// Roles for segments residing on disks where access is local

	// Flags
	u16 has_protection    :1;   // hweight32(dead|write) < protection ( == (replicas - slice size) == pari)
	u16 has_rw_pari       :1;   // (rw & pari) != 0
	u16 has_writable_pari :1;   // (~bmps.dead & bmps.pari) != 0
	u16 reserved         :13;
}__attribute__((packed));

void nvmeibc_raid1_acm2bmp(enum NVMEIBTC_DS_MODE acm, int si, struct nvmeibc_roles_bmps *bmp);

static inline void nvmeibc_update_roles_bmps_flags(struct nvmeibc_roles_bmps* bmps) {
	bmps->has_protection = hweight32(bmps->dead|bmps->w) < hweight32(bmps->raid.pari);
	bmps->has_rw_pari = (0 != ((bmps->rw | bmps->wp) & bmps->raid.pari));
	bmps->has_writable_pari = ((bmps->dead & bmps->raid.pari) != bmps->raid.pari);
	bmps->reserved = 0;
}

// Container for various data that can be calculated on based raid level topology data for future reuse
struct nvmeibc_raid1_calculated_data {
	struct nvmeibc_roles_bmps roles_bmps[N_MAX_RAID_SLICE_LEN];	// Precalculated nvmeibc_roles_bmps data structure held for each possible roles shift
	enum nvmeib_io_type_permission final_io_perm;				// Final io_perm <= r1->toma.io_perm
	struct dp_topology_traits topo_traits;			// Topology description for the raid1
};

/* Data protection raid struct: Supports D+P: 1+{0..3}, {2..8}+{1..2} */
struct nvmeibc_raid1 {
	int version;							// Unique id for multiple segments which mirror each other. Starts from 1 and grows to infinity
	int replicas;							// Number of segments in praid
	int slice_size;							// Size in blocks of a single slice in protection raid, For raid1 it is 1, for raid5 - the amount of D segments. We write exactly one block in each segment in a slice to minimize the amount of parities written
	union nvmeib_lock_id lid;				// Toma Lock id (generated by toma) - written into locks (toma can know which client locked the memory). 0=unlocked value. Unique for each raid1 (in each block device in each client).
	struct {								// Auxiliary fields for toma protocol. Should be private if this was a class. dont access them from outside of topology.c implementation
		u32	topo_checksum;						// Checksum of topology. Must be identical regardless of which toma generates it. Designed to catch bugs where different topo use same praid version
		enum nvmeib_io_type_permission io_perm;	// Use nvmeibc_raid1_get_io_perm() in datapath. This field represents only the permission given by toma, If raid is validly registered this is the maximal permissions it may have
		u64 conversation_ind;				// Latest conversatino id with Tomas on which the current lock id was agreed. Ever growing number
	} toma;
	struct nvmeibc_raid_topo_persistent *hdr; // Persistant header of raid1, not changed with dup_topo()
	struct nvmeibc_disk_segment *segments;  // Array of 'replicas' allocations
	struct nvmeibc_locks_scheme lock_scheme;// Locking scheme is relevant for each protection raid
	struct nvmeibc_raid1_calculated_data calculated_data; // Calculated data for ACTIVE topology. !!!DO NOT ACCESS DIRECTLY, USE HELPER FUNCTION!!! nvmeibc_raid1_get_calculated_data
	bool use_rdma_locks;
};

#define nvmeibc_raid1_role2seg(r1, slice_start_seg_ind, role)     (((slice_start_seg_ind) + (role)) % (r1)->replicas)
#define nvmeibc_raid1_seg2role(r1, slice_start_seg_ind, seg_ind)  (((seg_ind) + ((r1)->replicas) - (slice_start_seg_ind)) % (r1)->replicas)

#define nvmeibc_raid1_get_calculated_data(pr) (&(pr)->calculated_data)
#define nvmeibc_raid1_get_data_bmp(pr)       ((1<<(pr)->slice_size)-1)							// Retrieve a bitmap of form 0 - parity, 1 - data
#define nvmeibc_raid1_get_all_bmp(pr)        ((1<<(pr)->replicas  )-1) 							// Retrieve a bitmap of form 1 - parity, 1 - data
#define nvmeibc_raid1_get_parities_bmp(pr) (nvmeibc_raid1_get_all_bmp(pr)^nvmeibc_raid1_get_data_bmp(pr))	// Retrieve a bitmap of form 1 - parity, 0 - data

// Retrieve a bitmap for blockset where D0 is at slice_start_seg_ind.
#define nvmeibc_raid1_get_roles_bmp(r1, slice_start_seg_ind, bmp) \
	nvmeibc_raid1_get_calculated_data(r1)->roles_bmps[slice_start_seg_ind].bmp

// Inverse of the above
#define nvmeibc_raid1_get_inverse_roles_bmp(r1, slice_start_seg_ind, bmp) \
	((~(nvmeibc_raid1_get_roles_bmp(r1, slice_start_seg_ind, bmp))) & nvmeibc_raid1_get_roles_bmp(r1, slice_start_seg_ind, raid.all))

// Retrieve a bitmap for physical segments in praid (actually equal to role with shift 0)
#define nvmeibc_raid1_get_sgmnts_bmp(r1, bmp) ((sgmnts_bmp_t)nvmeibc_raid1_get_roles_bmp(r1, 0, bmp))

// Retrieve an inverse mask of a bitmap from segment level calculated data (masked with raid1 replicas size).
// Segment level is actually equal to role with shift 0
#define nvmeibc_raid1_get_inverse_sgmnts_bmp(r1, bmp) \
	nvmeibc_raid1_get_inverse_roles_bmp(r1, 0, bmp)

// Count the number of bits in bitmap
#define nvmeibc_raid1_count_bmp(        r1, bmp) (hweight16(nvmeibc_raid1_get_sgmnts_bmp(        r1, bmp)))
#define nvmeibc_raid1_count_inverse_bmp(r1, bmp) (hweight16(nvmeibc_raid1_get_inverse_sgmnts_bmp(r1, bmp)))

void nvmeibc_raid1_clear_new_topo_upon_unreg(struct nvmeibc_raid1 *r1);	// Upon dup_topo + unreg: Clear registration data and prepare for next registration
void nvmeibc_raid1_clear_old_topo(           struct nvmeibc_raid1 *r1); // Upon dup topo + raid change: Clear stuff of old topo.
enum nvmeib_io_type_permission nvmeibc_raid1_get_io_perm(const struct nvmeibc_topology *t, int c, int r);
#define                        nvmeibc_raid1_get_io_perm_2(r1) ((r1)->calculated_data.final_io_perm)

static inline bool nvmeibc_raid_is_ec(const struct nvmeibc_raid1 *r){ return r->slice_size > 1;}
static inline bool nvmeibc_raid_is_mirror(const struct nvmeibc_raid1 *r){ return (r->slice_size == 1) && (r->replicas > 1);}


#define nvmeibc_raid_is_enable_partial_slice_write(pr) nvmeibc_raid_is_ec(pr)				// protection raid capability
static inline int  nvmeibc_raid1_get_protect_lvl(const struct nvmeibc_raid1 *pr){return pr->replicas - pr->slice_size; }
static inline bool nvmeibc_raid_is_jbod(     const struct nvmeibc_raid1 *pr) {return pr->replicas == 1;}
static inline u64  nvmeibc_raid_get_rlba_len(const struct nvmeibc_raid1 *pr) {return pr->slice_size * pr->segments[0].length; }
static inline u64  nvmeibc_raid_get_slba_len(const struct nvmeibc_raid1 *pr) {return pr->segments[0].length; }

#define nvmeibc_praid_are_all_readable(pr)		(nvmeibc_raid1_get_sgmnts_bmp(pr, readable) == nvmeibc_raid1_get_sgmnts_bmp(pr, raid.all))
#define nvmeibc_praid_is_topo_no_dbits(pr)		((nvmeibc_raid1_get_protect_lvl(pr) == 0) || nvmeibc_praid_are_all_readable(pr))
#define nvmeibc_praid_get_num_deg_segs(pr)		((int)nvmeibc_raid1_count_inverse_bmp(pr, readable))
#define nvmeibc_raid1_get_num_dead_seg(pr)		((int)nvmeibc_raid1_count_bmp(        pr, dead))
#define nvmeibc_praid_enable_multi_degraded_writes(pr) (nvmeibc_praid_get_num_deg_segs(pr) > 1)
/* Convert bmp: relative to slice start to rel-to-seg0 + insert parities */
sgmnts_bmp_t nvmeibcbdpec_bmp_ss2fs_with_pari(struct nvmeibc_raid1 *r1, u64 slba, roles_bmp_t tx_bmp);

struct nvmeibc_raid1 const* __nvmeibc_disk_segment_get_praid_impl(struct nvmeibc_disk_segment const* seg);

#define nvmeibc_disk_segment_get_praid(self) 																	\
	__builtin_choose_expr(__builtin_types_compatible_p(__typeof__(self), const struct nvmeibc_disk_segment*),	\
		__nvmeibc_disk_segment_get_praid_impl(self),															\
		(struct nvmeibc_raid1*)__nvmeibc_disk_segment_get_praid_impl(self)) 								\


union nvmeibc_raid1_io_pet_status{
	struct{
		u8 n_sgmnts;
		struct {
			u8 sgmnt;
			enum NVMEIBTC_DS_MODE mode : 8;
		} __attribute__((packed)) dgrd_sgmnts[2];
	} info;
	u64 all;
};

__attribute__((nonnull(1)))
union nvmeibc_raid1_io_pet_status nvmeibc_raid1_io_pet_describe_state(struct nvmeibc_raid1 const* raid);

#define raid1_for_each_seg(r1, seg, si) \
	for (si = 0, seg = r1 ? (r1)->segments : 0; \
		r1 && (si < (r1)->replicas); ++seg, ++si)

/*
 * A volume has space allocated to it based upon its type (JBOD/LVM, RAID-0,
 * RAID-1, etc.). It may not be possible to allocate all its space in one
 * allocation. Each allocation is called a chunk. A chunk fulfills a range of
 * virtual block addresses on the volume. There is no limit to the number of
 * chunks in a volume. Each chunk requires one or more allocations from
 * different drives (depdending on the volume type). A JBOD / LVM has one
 * allocation per chunk. A RAID-1 has 2. A RAID-0 has stripe width allocations.
 * RAID-10 has 2 * width.
 */
struct nvmeibc_chunk {
    u64 first_vlba;                         // Beginning of the range of virtual block adresses on the volume
	int stripe_size;						// Num of sequential blocks in each stripe. In raid5+0 (D+P), skipping stripe after 1 lock, slice size is 32[blocks]*D. Todo: move to be a field of per chunk
	//int stripe_width;						// 1 If not striped. Amount of elements in the raid1s array. Todo: move this field from topology
	struct nvmeibc_raid1 *raid1s;  			// Array of allocations. Length of the array depends upon type of the volume (read above). If RAID 1, segment 2*i and 2*i+1 are mirrors
    struct nvmeibc_topology *topology;      // References back to the configuration (type of the volume) which holds this chunk. Private struct defined in nvmeibc_topology.h
};
#define nvmeibc_chunk_get_num_raids(t, c)	((t)->stripe_width)

/* Find the chunk which contains given address and return its index */
int nvmeibc_get_chunk_ind_of_lba(u64 lba, const struct nvmeibc_topology *t);

/* Bitmask for nvmeibc_io_throttle_metrics_trace_selected() and module param io_throttle_metrics_trace_mask.
 * bit 0 (0x1): per-CPU event-count array
 * bit 1 (0x2): per-CPU highres throttle latency histogram (includes max_ticks)
 * bit 2 (0x4): reserved (was max_latency; use HIGHRES_HISTOGRAM.MAX_TICKS)
 * bit 3 (0x8): number of throttled IOs
 */
#define NVMEIBC_IO_THROTTLE_METRIC_COUNT		(1u << 0)
#define NVMEIBC_IO_THROTTLE_METRIC_LATENCY		(1u << 1)
#define NVMEIBC_IO_THROTTLE_METRIC_NUM_THROTTLED	(1u << 3)

extern uint nvmeibc_io_throttle_metrics_trace_mask;

struct nvmeibc_io_throttle_metrics {
	struct nvmesh_metric_monotonic_counter count;       /* IOs throttled (monotonic) */
	struct nvmesh_metric_highres_histogram latency;     /* time in queue (TSC ticks; includes exact max) */
	struct nvmesh_metric_gauge            num_throttled; /* number of throttled IOs */
};

static inline void nvmeibc_io_throttle_metrics_clear(struct nvmeibc_io_throttle_metrics *m)
{
	nvmesh_metric_monotonic_counter_clear(&m->count);
	nvmesh_metric_highres_histogram_clear(&m->latency);
	nvmesh_metric_gauge_clear(&m->num_throttled);
}

static inline void nvmeibc_io_throttle_metrics_record_throttled(struct nvmeibc_io_throttle_metrics *m)
{
	nvmesh_metric_monotonic_counter_update(&m->count, 1);
	nvmesh_metric_gauge_update(&m->num_throttled, 1);
}

static inline void nvmeibc_io_throttle_metrics_record_dequeued(struct nvmeibc_io_throttle_metrics *m, u64 wait_ticks)
{
	nvmesh_metric_highres_histogram_update(&m->latency, wait_ticks);
	nvmesh_metric_gauge_update(&m->num_throttled, -1);
}

struct topo_percore_shared;
void nvmeibc_io_throttle_metrics_trace_selected(const char *dev_name,
						struct topo_percore_shared *percore_shared,
						unsigned int trace_mask);

/***************** Implementation of real time topology **********************/
/* This object exist per core BUT unlike percpu all cores update it regularly.*/
struct topo_percore_shared {				// It must *NOT* be within the percpu pages bcz otherwise it will cause contention for other variables that share the cache line & assume that the data is private for the core.
	spinlock_t 		list_access;			// Accessing the list below: 1 cpu adds new io's  while another cpu removes when it finishes previous io
	struct list_head	io_wait_list;		// list of IO's waiting for execution (kernel sent those io to this cpu so they are in its list)
	u64				ios_completed;			// # of in air io's (originating from this core) that were already completed (by this or other core), monotonically increasing.
	struct nvmeibc_io_throttle_metrics throttle_metrics;
	int 			n_wait_list;			// number of 'op' queued in the wait-list
	#ifdef DEBUG_PERCPU_ISSUED_IO_CNTRS
		unsigned	n_ios;					// # of io's that are currently in-flight from this core (debugging counter only) == (ios_issued - ios_completed).
	#endif
} ____cacheline_aligned;

struct topos_percpu {						// This object has member that each core maintains seperately
	volatile int nt_users; /* Amount or topo-readers (doing get() put() topo). 0 or 1 for each CPU */
	unsigned long flags;	 /* Obtaining topology must be with irq disabled */
	u64		ios_issued;						// # of io's in air (originating from this core) that were issued, monotonically increasing.
} ____cacheline_aligned;

enum nvmeibc_topo_boot_state {						// Internal boot state of the topologies, used during volume reboot/detach/suspend/revive operations
	NVMEIBC_TOPO_BOOT_NORMAL			= 0x0,		// Reboot not running. Must be zero!
	NVMEIBC_TOPO_BOOT_SUSPENDING		= 0x2,		// Entered suspend attempt, waiting too drain all topos before the suspended one.
	NVMEIBC_TOPO_BOOT_LIST_CLEANUP		= 0x3,		// Cleaning up topos list (unregister, unsubscribe segments), soon the list will be empty
	NVMEIBC_TOPO_BOOT_NO_GET_TOPO		= 0x4,		// List cannot support get() operations, it might be empty now or last topo is being freed
	NVMEIBC_TOPO_BOOT_APPLIED_NEW		= 0x5,		// New configuration is inserted as starting topology
	NVMEIBC_TOPO_BOOT_REVIVING			= 0x6,		// Registering segments of new topology. Will soon transition back to Normal
};
#define is_suspended(nt) (((nt).boot_state!=NVMEIBC_TOPO_BOOT_NORMAL))


/******************* Live TOMA message handlers drainer **********************/
struct toma_msg_handlers_drainer {
	struct kref handlers;
	void (*release_cb)(struct toma_msg_handlers_drainer *);
};
void toma_msg_handlers_drainer_reinit(struct toma_msg_handlers_drainer*);
void toma_msg_handlers_drainer_init(  struct toma_msg_handlers_drainer*, void (*release_cb)(struct toma_msg_handlers_drainer *));
void toma_msg_handlers_drainer_get(   struct toma_msg_handlers_drainer*);
void toma_msg_handlers_drainer_put(   struct toma_msg_handlers_drainer*);

struct nvmeibc_topologies {
	struct list_head topologies;								// Linked list of topologies. Head is the most recent one
	const char *device_name; 									// Todo: Remove. Use the pointer below. For prints
	struct nvmeibc_block_device *nd;							// Todo: Remove, use: nvmeibc_block_nt_to_b instead, Not nice to break the layers like this...
	__concurrent_access volatile enum nvmeib_io_type_permission io_perm;			// Does the head topology allows successfull IO or it contains error.
#ifndef DP_LIB													// Rest of the fields are needed for control path only
	atomic_t need_update; 										// Flags someone wants to insert new (updated) topology into the list as the head.
	spinlock_t lock;											// Lock to serialize topology updates. Each flow that updates topology head (toma message/pause/cont/configuration change/...) must to the update atomically and this lock guarantees this atomicity
	struct topos_percpu         *percpu;						// Struct which keeps count of parallel cpu's accessing topologies list (many can read, only one can write)
	struct topo_percore_shared 	*percore_shared;				// similiar to percpu (instance per core) but expectation is that all cores access all instances.
	u64 dbg_disabling_ts;										// If IO is disabled, stores the jiffies when IO became disabled. Otherwise 0. Use to print the period where there was no bio

	void (*error_state_update_cb)(struct nvmeibc_topologies *nt, enum nvmeib_io_type_permission new_io_perm, void* ctx);	// Callback of higher level software (block device) upon topology update (possibly io enabled or disabled)
	struct {													// When IO was disabled and becomes enabled, call this debug callback. Used for unitests
		void (*cb)(struct nvmeibc_topologies *nt, void* ctx);
		void *ctx;
	} debug_on_io_enabled;

	u64 reservation_version;									// Used to enforce reservation mode, mgmt generated
	__concurrent_access u64 reservation_version_max_seen;							// Holds the max reservation version seen by the volume (If > mine then I am preempted). This number is sent to toma
	/* Fields for suspention and reviving block device */
	enum nvmeibc_topo_boot_state boot_state;
	void *susped_context;	/* Opaque context and callback to return when */
	blk2blk_gen_work_t on_suspend_finish_cb; /* Last IO finishes */
	struct toma_msg_handlers_drainer tmhd;
	char io_disabled_reason[256];								// Textual reason why io is disabled right now.
#endif
	u64 topo_debug_unique_index_generator;						// Every topology gets a monotonically increasing index
	u64 topo_debug_last_freed_version;							// Ever increasing index (above) that was already freed. (-1 ..-N) from the head topology.
	u64 dbg_num_enabling_io_toggles;							// Amount of times io was disabled and enabled
};
#define nvmeibc_topo_init_io_perm(t)   ({ (t)->io_perm = NVMEIB_IO_TYPE_PERMIT_NONE_ERR; })	 // By default no IO, will be updated upon insertion as head to the topos list
#define nvmeibc_topo_is_invtopo_state(t) ((s16)((t)->io_perm) <  NVMEIB_IO_TYPE_PERMIT_NONE_ERR)	 // Invalid topology, registering segments wont help
#define nvmeibc_topo_is_in_err_state(t)  ((s16)((t)->io_perm) <= NVMEIB_IO_TYPE_PERMIT_NONE_ERR)	// No BIO, No syncs
//TODO: may be the better name would be is_writable?
#define nvmeibc_topo_is_io_ok(t)         ((t)->io_perm >=  NVMEIB_IO_TYPE_PERMIT_ALL_NO_PROTECTION)
#define nvmeibc_topo_is_partially_ok(t)  ((t)->io_perm > NVMEIB_IO_TYPE_PERMIT_NO_RM_IO)		 // At least some IO's are allowed

struct nvmeibc_topology_resize{
	u64 size;													// Non zero during volume resizing. Stores the size after reconfiguration.
	struct nvmeibc_chunk *chunks;								// Array of new chunks to add (when expanding). Special marker when shrinking.
	short int nchunks;											// Amount of final chunks (length of 'chunks' when expanding, when shrinking smaller than the previous amount)
	short int n_last_disabled_chunks;							// When appending/shrinking last chunks become disabled
};
void nvmeibc_topology_resize_clear(struct nvmeibc_topology_resize *r);

#include "block/controlpath/nvmeibc_b_cp_topo_on_free.h"

struct nvmeibc_topology {
	struct list_head list_n;									// Link to list of topologies in 'nt'
	struct nvmeibc_topologies *nt;								// Points back to topologies struct
	u64 configuration_version;									// Ever increasing index of configuration issued by management
	u64 topology_version;										// Curerntly unused, because each raid1 has its own version
	u64 debug_unique_index;										// Only for debug, each consecutive topology get increased unique index
	spinlock_t delete_lock;										// Used only when deleting the topology. Prevents race condition when 2 cpu's simultanously stop using the topology, reference count drops to zero and both cpu's try to free it in parallel

	/* This is a map of the remote distribution of the LBAs comprising this device */
	int nchunks;												// Number of chunks (as written in the current configuration)
	int highest_pow2_in_chunk_ind;								// Max power of 2 which < index of last chunk. Used for binary search
	int stripe_width;											// Amount of protection raids in chunk. R1+0 of width 3 will have 3 Raid1's. Todo: move to be a field of per chunk
	int max_n_segs_in_praid;									// Accross all praids in all chunks, stores the the maximal amount of segments in a praid
	bool is_safe_for_view_lock;									// Is entire topology safe to view locks on read. Takes the worst value of all praids. If no, then maybe specific raid is safe
	__concurrent_access volatile int phased_out;									// 0(false) regular topolocy, 1(true) once reference counter drops to zero will be deleted, NVMEIBC_TOPOLOGY_BEING_FREED - being deleted
	enum nvmeib_io_type_permission io_perm;						// Same as 'nt->io_perm' but for each topology
	struct nvmeibc_chunk *chunks;
#ifndef DP_LIB													// Rest of the fields are needed for control path only
	int num_reconfing_segs;										// Amount of segments that are being reconfigured (replaced/upgraded/downgraded by a newer configuration). Non zero during transition from configuration i to i+1
	struct nvmeibc_topology_resize resize;
	struct on_topo_free on_free;
	struct nvmeibc_topo_percpu *percpu;
	struct nvmeibc_topology *newer; 							// Exists for debug only. == container_of(list_n->prev)
	#ifdef DEBUG_TOPO_CNTRS
		spinlock_t dbg_tcntrs_lck;
		struct list_head dbg_tcntrs;
	#endif
#endif
};
#define __get_topo_num_chunks(t)		((t)->nchunks-1)		// We add a dummy chunk at the end

// read the counter of *another* core.
u64 topo_get_cpu_io_completed(const struct nvmeibc_topologies *nt, int cpu_id);

/* Returns upper bound on number of IO's in flight from core 'cpu_id'.
   Important: use between calls to get_cpu() .... put_cpu(), and ask only on the
   current cpu. If X is returned, inflight, io's is at most X. */
u64 topo_get_cpu_ios(const struct nvmeibc_topologies *nt, int cpu_id);

void nvmeibc_topology_fill_all_topo_raids_calculated_data(struct nvmeibc_topology *);

struct nvmeibc_disk_segment *nvmeibc_topology_get_seg(struct nvmeibc_topology *,
							int chunk, int raid1, int seg);

int nvmeibc_topologies_init(struct nvmeibc_topologies *nt, const char *device_name);

/* Allocate and construct topology from input volume configuration.
 * On first configuration (upon which block device is created) 'is_update' is
 * false. When reconfiguring block device use true.
 */
int nvmeibc_topology_update_configuration(struct nvmeibc_topologies *nt,
	struct nvmeibc_volume_conf *conf, int version, bool is_update,
										  struct list_head *disks);

/* Given a topology representing a new configuration, calculate diff from the
 * head (of nt) and append the changes to the head (only append changes, do not
 * apply yet). Will be applied in future in hot or warm fashion.
 * hot - continuos IO. warm - stopping IO (unreg all segments, apply and rereg)
 * Example: Append to deprecated segments their replacements, to upgraded or
 * downgraded raid1s special marks, shrink or grow the volume by chunks etc
 * negative error from errno-base.h is returned or 0 on success
 */
int nvmeibc_calc_and_append_conf_diffs(struct nvmeibc_topologies *nt,
		struct nvmeibc_topology *new_conf_t);

/* If the function above failed, we can try to replace the previous topologies
   with the new configuration. This is a very dangerous step which is done
   during volume reboot. This is done in 2 steps (order is crucial):
   1. Activate the new configuration (to prevent volume being without segments)
   2. Inject it into the previous. */
void nvmeibc_topology_force_replace_t_act(struct nvmeibc_topologies *nt,
									  struct nvmeibc_topologies *new_conf_t);
void nvmeibc_topology_force_replace_t_inj(struct nvmeibc_topologies *nt,
									  struct nvmeibc_topologies *new_conf_t);

/* Cleanup to the 2 functions above (release new condiguration). Should be
   called, once regardless if reconfiguration was success or failure*/
void nvmeibc_topology_free_new_conf_t(struct nvmeibc_topologies *new_conf_t);

void nvmeibc_topologies_error_state_reason(struct nvmeibc_topologies *nt, void *ctx);

/* After we calculated and appended diffs, subscribe the new segments with Toma
   This is crucial step to do before sending registers. This it a long function
   which waits for calbacks and reschedules to other CPU's. Call it from
   appropriate context */
int nvmeibc_subscribe_requested_conf_diffs( struct nvmeibc_topologies *nt);

/* Unregister the whole device, force apply all conf changes and re-register */
int nvmeibc_warm_apply_conf_diffs(struct nvmeibc_topologies *nt);

/* Without unregisterring, apply only those conf changes which toma already
   requested. If Toma received new configuration before client, it will request
   to apply changes that client is not aware of. Client will mark those request
   and when new configuration finally arrives, it will apply the immediately. */
int nvmeibc_apply_requested_conf_diffs( struct nvmeibc_topologies *nt);

/* Complementary to the above function. After we applied diffs, some other segs
   that have not changed are unregister coz they got volume version mismatch.
   try register them too */
int nvmeibc_topologies_conf_register_mismatch_segs(struct nvmeibc_topologies*);
/*
 * Register all segments upon creation of bock device. Call only when there is
 * no active IO.
 * Return value: Error value upon error...otherwise, the amount of
 * requested segments.
 */
int  nvmeibc_topologies_register(struct nvmeibc_topologies *nt);
int  nvmeibc_topologies_cleanup( struct nvmeibc_topologies *nt);
void nvmeibc_topologies_free(	 struct nvmeibc_topologies *nt);
bool nvmeibc_topologies_are_reads_enabled(struct nvmeibc_topologies *nt);
void nvmeibc_topologies_duplicate(struct nvmeibc_topologies *nt, void (*fn)(struct nvmeibc_topology* new_t));		// Method to extend topologies. Duplicates topo, apply optional fn() on new topology and set it as head

/* When block device messed up IO on a segment (abandoned locks), it can notify
   toma and start from clean via this method (reregister active segment).
   Existing optimization: Even if block abandoned N locks on the segment only
   the first rereg will occur (no need to rereg N times) */
int nvmeibc_topologies_rereg_seg(struct nvmeibc_disk_segment *seg);

struct nvmeibc_topology *nvmeibc_topology_get(struct nvmeibc_topologies *nt);
void                     nvmeibc_topology_put(      struct nvmeibc_topology *t);
struct nvmeibc_topology *nvmeibc_topology_addref(   struct nvmeibc_topology *t);
#define nvmeibc_topology_get_max_num_replicas(t) ((t)->max_n_segs_in_praid)

/* Must be called with interupts disabled, and delete lock locked! */
bool nvmeibc_topology_is_being_freed_ID(struct nvmeibc_topology *t);

/* Is the device in the middle of reconfiguration (it's volume version is
   undefined, because reconfiguration is not atomic) */
bool nvmeibc_topology_is_reconfiguring_now(const struct nvmeibc_topology *t);
void nvmeibc_topo_update_size_of_bdev(           struct nvmeibc_topology *t);

void nvmeibc_topology_pause(struct nvmeibc_topologies *nt, struct nvmeibc_idisk *disk);
void nvmeibc_topology_cont( struct nvmeibc_topologies *nt, struct nvmeibc_idisk *disk);

/* Generate a string describing the current topology. Write it into the buffer
   and return the numb of written bytes. 'nt' not const beacause we take
   spinlock */
void nvmeibc_topologies_status_tostring(   struct nvmeibc_topologies *nt, struct nvmeib_txt *txt);
void nvmeibc_topologies_status_tojson(     struct nvmeibc_topologies *nt, struct jdr *jdr);
void nvmeibc_topologies_stalocks_tostring( struct nvmeibc_topologies *nt, struct nvmeib_txt *txt);
void nvmeibc_topologies_profilers_tostring(struct nvmeibc_topologies *nt, struct nvmeib_txt *txt);
void nvmeibc_topologies_profilers_tocsv(   struct nvmeibc_topologies *nt, struct nvmeib_txt *txt);

#if defined(BLKDEV_SIMULATOR) && (BLKDEV_SIMULATOR==1)
/* For debugging, while there is no IO. Checks there is no corruption. Return true if everything is OK, otherwise invokes bug (if do_assert==true) or return false */
bool nvmeibc_topology_is_stable_noio(const struct nvmeibc_topologies *nt, bool do_assert);

/* Debug: wait until there's a single topology & it has no IO's. */
void nvmeibc_topo_wait_for_single_topo_no_io(const struct nvmeibc_topologies *nt, int n_refs);
#endif

/* Suspends/Revive the entire block device. Used by nvmeibc_block_suspend() */
int nvmeibc_topologies_set_suspend_state(struct nvmeibc_topologies *nt,
		bool is_on, void *susped_context, blk2blk_gen_work_t on_suspend_finish_cb);

/* Notify all tomas of a given raid (chunk[ci].raids[ri]) that data corruption
   occured in this raid. If addrs_array==NULL notifies all raids in volume */
int nvmeibc_topologies_inform_di_bug_in_raid(struct nvmeibc_topologies *nt,
		u64 *addrs_array, int ci, int ri);

/* A debug function which scans all subscribed segments (of all volumes) and in
   O(n^2) finds if there is overlapping in any 2 of them. Returns the amount of
   corruptions. 0 if configuration is OK */
int nvmeibc_trs_detect_config_corruption(const struct nvmeibc_cinst_params_blk *p);

/* A debug function which scans if raid of volume has illegal structure, and in
   O(n^2) finds if there is such raid. Returns the amount of corruptions.
   0 if configuration is OK */
int nvmeibc_topologies_detect_illegal_raid_conf(struct nvmeibc_topologies *nt);

/* Debug method: prints the lst of topologies and recovers a stuck list
 * (topology is not freed even when its reference counter is zero) */
bool nvmeibc_topology_manual_attempt_recover_list(struct nvmeibc_topologies *nt);

/**************************** Printing functions ******************************/
#define WARN_TOPO(cond, t, fmt, ...) WARN(cond, DMESG_PREFIX("%s: ") "bug <%lld>: " fmt, t ? t->nt->device_name : "???", t ? t->debug_unique_index : (u64)~0, ##__VA_ARGS__)

#define __NLVL_TOPO_DEV(LVL, name, t, format, ...) LVL(name, topology /*Scope*/, DMESG_PREFIX("@DEV_NAME") "@TOPO_DBG_ID: " format, t ? t->nt->device_name : "", t ? t->debug_unique_index : (u64)~0, ##__VA_ARGS__)

#define _ND_TOPO(name, t, format, ...) __NLVL_TOPO_DEV(_ND_SCOPE, name, t, format, ##__VA_ARGS__)
#define _NT_TOPO(name, t, format, ...) __NLVL_TOPO_DEV(_NT_SCOPE, name, t, format, ##__VA_ARGS__)
#define _NI_TOPO(name, t, format, ...) __NLVL_TOPO_DEV(_NI_SCOPE, name, t, format, ##__VA_ARGS__)
#define _NW_TOPO(name, t, format, ...) __NLVL_TOPO_DEV(_NW_SCOPE, name, t, format, ##__VA_ARGS__)
#define _NE_TOPO(name, t, format, ...) __NLVL_TOPO_DEV(_NE_SCOPE, name, t, format, ##__VA_ARGS__)

#define SEGMENT_FMT "(@CHUNK_IDX,@PRAID_IDX,@SI)"				// Print like that in binary tracing
#define __NLVL_TR(LVL, name, format, ...)  LVL(name, topology /*Scope*/, "@DEV_NAME" SEGMENT_FMT ": " format, tr->nt->device_name, tr->ch, tr->r1, tr->seg, ##__VA_ARGS__)
#define _NTTR(name, format, ...) __NLVL_TR(_NT_SCOPE, name, format, ##__VA_ARGS__)
#define _NITR(name, format, ...) __NLVL_TR(_NI_SCOPE, name, format, ##__VA_ARGS__)
#define _NWTR(name, format, ...) __NLVL_TR(_NW_SCOPE, name, format, ##__VA_ARGS__)
#define _NETR(name, format, ...) __NLVL_TR(_NE_SCOPE, name, format, ##__VA_ARGS__)
#endif // NVMEIBC_TOPOLOGY_H
