#!/bin/bash

# This script configures receive steering for SIW to optimize performance and throughput
# Needs to be run as root

DEFAULT_DEVICE=eth0
DEFAULT_NUM_QUEUE=8
DEFAULT_SET_RXQ=false
DEFAULT_BASE_QUEUE=0
DEFAULT_SIW_BASE_PORT=7915
DEFAULT_RPS_SOCK_FLOW_ENTRIES=65536
DEFAULT_SET_IRQ=true
DEFAULT_AFFINITY_DOMAIN=persocket
DEFAULT_NUM_CHANNELS=32
DEFAULT_FLOW_STEER="none"
DEFAULT_RPS_MODE="donttouch"
DRY_RUN=false
CLEAN=false

PARAMS="$@"

# Get CPU Tables for Affinty Domains
source $(dirname $0)/nvmesh_set_irq_affinity_common
if [ $? != 0 ]; then
	echo "$0: ERROR - $(dirname $0)/nvmesh_set_irq_affinity_common not found!" | tee /dev/kmsg
	exit 1
fi

# process command line opts, if any
function usage()
{
	echo -e "Usage: $(basename $0) [options]\n"
	echo -e "options:"
	echo -e "\t[-d|--device] <eth-device>"
	echo -e "\t[-c|--channels] <num-nrch-channels>"
	echo -e "\t[-q|--queues] <num-rx-queues>"
	echo -e "\t[-x|--setrxq] Set number of RXQs (ethtool -L) if needed"
	echo -e "\t[-b]--baseq] <base-rx-queue>"
	echo -e "\t[-p|--port] <siw-base-port>"
	echo -e "\t[-e|--entries] <rps-sock-flow-entries>"
	echo -e "\t[-m|--domain] <affinity-domain - pernuma, persocket, fullspread, list-of-cpus e.g. \"16,17,18,19,20,21,22,23,24\" or \`seq -c, 0 15\` >"
	echo -e "\t[-n|--noirq] Don't set IRQ affinity"
	echo -e "\t[-f|--flowsteer] <flow-steering-mode - rfs, ntuple, none> (none falls back to RSS if enabled)"
	echo -e "\t[-s|--rpsmode] <rps-mode - alldomain, irq_range_wrap, irq_neighbour, off, donttouch>"
	echo -e "\t[--dryrun] Don't change anything, just echo the changes to stdout"
	echo -e "\t[--clean] Clean all previous settings while applying new configuration"
	echo -e "\t[-h|--help]"
	exit 1
}

SHORT_OPTIONS="hn" # no args
SHORT_OPTIONS+="d:q:p:e:b:m:c:r:f:s:x:" # with arg

LONG_OPTIONS="help,noirq,setrxq,dryrun,clean" # no args
LONG_OPTIONS+=",device:"
LONG_OPTIONS+=",queues:,port:,entries:,baseq:,domain:,channels:,flowsteer:,rpsmode:" # with arg

options=$(getopt -o ${SHORT_OPTIONS} -l ${LONG_OPTIONS} -- "$@")
if [ $? -ne 0 ]; then
	# something went wrong, getopt should have printed an error message
	usage
fi

eval set -- ${options}

while [ $# -gt 1 ]; do
	case $1 in
		-h|--help) usage; ;;
		-d|--device) CMD_DEVICE="$2"; shift ;;
		-c|--channels) CMD_CHANNELS="$2"; shift ;;
		-q|--queues) CMD_QUEUE="$2"; shift ;;
		-b|--baseq) CMD_BASE_QUEUE="$2"; shift ;;
		-r|--basecpu) CMD_BASE_CPU="$2"; shift ;;
		-p|--port) CMD_PORT="$2"; shift ;;
		-e|--entries) CMD_ENTRIES="$2"; shift ;;
		-m|--domain) CMD_AFFINITY_DOMAIN="$2"; shift ;;
		-n|--noirq) CMD_SET_IRQ=false;;
		-s|--rpsmode) CMD_RPS_MODE="$2"; shift ;;
		-x|--setrxq) CMD_SET_RXQ=true;;
		-f|--flowsteer) CMD_FLOW_STEER="$2"; shift ;;
		--dryrun) DRY_RUN=true;;
		--clean) CLEAN=true;;
		(--) shift; break ;;
		(-*) echo "$0: error - unrecognized option $1" 1>&2; usage; ;;
		(*) break ;;
	esac
	shift
done

# Select between defaults and options
DEVICE=${CMD_DEVICE:-${DEFAULT_DEVICE}}
NUM_CHANNELS=${CMD_CHANNELS:-${DEFAULT_NUM_CHANNELS}}
NUM_QUEUE=${CMD_QUEUE:-${DEFAULT_NUM_QUEUE}}
BASE_QUEUE=${CMD_BASE_QUEUE:-${DEFAULT_BASE_QUEUE}}
SIW_BASE_PORT=${CMD_PORT:-${DEFAULT_SIW_BASE_PORT}}
RPS_SOCK_FLOW_ENTRIES=${CMD_ENTRIES:-${DEFAULT_RPS_SOCK_FLOW_ENTRIES}}
SET_IRQ=${CMD_SET_IRQ:-${DEFAULT_SET_IRQ}}
AFFINITY_DOMAIN=${CMD_AFFINITY_DOMAIN:-${DEFAULT_AFFINITY_DOMAIN}}
BASE_CPU=${CMD_BASE_CPU:-${DEFAULT_BASE_CPU}}
FLOW_STEER=${CMD_FLOW_STEER:-${DEFAULT_FLOW_STEER}}
RPS_MODE=${CMD_RPS_MODE:-${DEFAULT_RPS_MODE}}
SET_RXQ=${CMD_SET_RXQ:-${DEFAULT_SET_RXQ}}
ENDQ=$(($BASE_QUEUE + $NUM_QUEUE - 1))

if $DRY_RUN; then
	echo "----------------------DRY-RUN-------------------------------"
else
	if (( $EUID != 0 )); then
		echo "Please run as root"
		exit
	fi
fi

# Helper function. Log
function log()
{
	if $DRY_RUN; then
		echo "$0: $*"
	else
		echo "$0: $*" | tee /dev/kmsg
	fi
}

# Helper function. Warning to Log
function warn_log()
{
	if $DRY_RUN; then
		echo "$0: WARNING: $*"
	else
		echo "$0: WARNING: $*" | tee /dev/kmsg
	fi
}

# Helper function. Error to Log
function err_log()
{
	if $DRY_RUN; then
		echo "$0: ERROR: $*"
	else
		echo "$0: ERROR: $*" | tee /dev/kmsg
	fi
}

# ------------------------------------------------------------------------------
# Flow Steering Mode ([a]RFS, n-Tuple, None)
#
# Flow Steering Mode is the method by which the RX Queue is chosen for the incoming flow (TCP connection)
#
# [a]RFS (requires the driver to implement ndo_rx_flow_steer and ethtool ntuple on) - dynamically creates flow rules
# to steer the packets to the RXQ based on the flow CPU and the RXQ IRQ Affinity.
# The flow CPU is set by calls to accept, kernel_sendmsg and kernel_recvmsg.
# In the case of SIW, only the call to kernel_sendmsg is relevant and it is called from the TX Thread.
# The TX thread CPU depends on the SIW_IB_SEND_TX_CTX_PREF_* wr_flags, the scq vector and
# the tx_cpu_list modparam.
#
# n-Tuple - (requires the ethtool ntuple on) - statically creates flow rules using ethtool -N
# to steer the packets to an RXQ [--baseq, --baseq + --numq) based on the SIW TCP port [--port, --port + --channels)
#
# None - No Flow Steering is set, instead the RXQ will be chosen based on the RSS Indirection Table and RSS Hash of the packet
#
# ------------------------------------------------------------------------------
case $FLOW_STEER in
	rfs)
		SET_NTUPLE=true
		SET_FILTER_RULES=false
		SET_RPS_SOCK_FLOW_ENTRIES=true
		SET_RXQ_RPS_FLOW_CNT=true
		;;
	ntuple)
		SET_NTUPLE=true
		SET_FILTER_RULES=true
		SET_RPS_SOCK_FLOW_ENTRIES=false
		SET_RXQ_RPS_FLOW_CNT=false
		;;
	none)
		SET_NTUPLE=false
		SET_FILTER_RULES=false
		SET_RPS_SOCK_FLOW_ENTRIES=false
		SET_RXQ_RPS_FLOW_CNT=false
		;;
	*)
		echo "Invalid Flow Steering Mode: $FLOW_STEER"
		exit 1
esac

SET_RXQ_RPS_CPUS=true
if [ "$RPS_MODE" == "none" ]; then
	SET_RXQ_RPS_CPUS=false
fi

log "$PARAMS"
log "Configure receive-steering for device=$DEVICE : "\
"flow-steering-mode=$FLOW_STEER rps-mode=$RPS_MODE, rx-qs={$BASE_QUEUE..$ENDQ}, tcp-ports: {$SIW_BASE_PORT..$(($SIW_BASE_PORT + $NUM_CHANNELS - 1))}, "\
"affinity-domain: $AFFINITY_DOMAIN, num-channels=$NUM_CHANNELS, set-rxq=$SET_RXQ, "\
"set-ntuple=$SET_NTUPLE, set-filter-rules=$SET_FILTER_RULES, "\
"set-rps-sock-flow_entries=$SET_RPS_SOCK_FLOW_ENTRIES, "\
"set-rxq-rps-flow-cnt=$SET_RXQ_RPS_FLOW_CNT set-rxq-rps-cpus=$SET_RXQ_RPS_CPUS "\
"set-IRQs-affinity=$SET_IRQ dry-run=$DRY_RUN clean=$CLEAN"

# ------------------------------------------------------------------------------
# Find base-device - Used for VLANs and Azure Accelerated NW
# ------------------------------------------------------------------------------
echo "---"
echo "Find base-device of device=$DEVICE..."

if ! [ -d "/sys/class/net/$DEVICE" ]; then
    echo "No such file or directory /sys/class/net/$DEVICE..."
    exit 1
fi

# Follow "lower" links down to base device (e.g. /sys/class/net/eth0/lower_enPxxx)
BASE_DEVICE=$DEVICE
LOWER_LINK=$(find /sys/class/net/$BASE_DEVICE/ -name 'lower_*' -type l)
while [ ! -z $LOWER_LINK ]; do
	BASE_DEVICE=$(basename $LOWER_LINK | cut -c 7-)
	LOWER_LINK=$(find /sys/class/net/$BASE_DEVICE/ -name 'lower_*' -type l)
done

function cpu_list_to_mask()
{
	declare -a cpu_mask

	# Get max cpu from input
	max_cpu=0
	for i in $*
	do
		if (( $i > $max_cpu)); then
			max_cpu=$i
		fi
	done

	max_mask_idx=$(($max_cpu / 32))

	# Populate cpu_mask array with 0s
	for i in `seq 0 $max_mask_idx`
	do
		cpu_mask[$i]=0
	done

	# Set bits in cpu_mask array
	for i in $*; do
		mask_idx=$(($i / 32))
		idx_in_mask=$(($i % 32))
		cpu_mask[$mask_idx]=$(( ${cpu_mask[$mask_idx]} | (1 << $idx_in_mask) ))
	done

	# Convert to hex CSV string
	out=""
	for field in ${cpu_mask[@]}
	do
		out=`printf "%x,%s" $field $out`
	done
	# Remove final comma
	echo ${out%?}
}

# Helper function. Execute command $* and check return value
function exec_cmd_check_return()
{
	if $DRY_RUN; then
		echo "> $*"
		RET=0
	else
		$*
		RET=$?
	fi
	if [ $RET -ne 0 ]; then
		echo "$0: Failed ($RET): $*" | tee /dev/kmsg
		exit $RET
	fi
}

# Helper function. Write $1 into $2 file and check return value
function write_file_check_return()
{
	if $DRY_RUN; then
		echo "echo $1 > $2"
		RET=0
	else
		echo $1 > $2
		RET=$?
	fi
	if [ $RET -ne 0 ]; then
		echo "$0: Failed ($RET): echo $1 > $2" | tee /dev/kmsg
		exit $RET
	fi
}

function is_integer() {
	re='^[0-9]+$'
	if [[ "$1" =~ $re ]] ; then
		return 0
	else
		return 1
	fi
}

# ------------------------------------------------------------------------------
# Increase number of Rx/Combined Queues/Channels via ethtool -L option
# ------------------------------------------------------------------------------
# Example:
# root@nvmesh1:/root# ethtool -l $BASE_DEVICE
# Channel parameters for enP40275s1:
# Pre-set maximums:
# RX:             48
# TX:             32
# Other:          0
# Combined:       0
# Current hardware settings:
# RX:             16
# TX:             32
# Other:          0
# Combined:       0
#
# root@nvmesh1:/root# ethtool -l eth0
# Channel parameters for eth0:
# Pre-set maximums:
# RX:             0
# TX:             0
# Other:          0
# Combined:       48
# Current hardware settings:
# RX:             0
# TX:             0
# Other:          0
# Combined:       8

NEED_RXQ=$(($NUM_QUEUE + $BASE_QUEUE))
MAX_RXQ=$(ethtool -l $BASE_DEVICE | grep RX: | head -1 | cut -c4- | xargs)
if ! is_integer $MAX_RXQ; then
	echo "ethtool -l $BASE_DEVICE returned non-integer MAX_RXQ=$MAX_RXQ setting MAX_RXQ=0"
	MAX_RXQ=0
fi


if (( $MAX_RXQ == 0 )); then
# Combined Queues
	MAX_RXQ=$(($(ethtool -l $BASE_DEVICE | grep Combined: | head -1 | cut -c10-) + 0))
	NUM_RXQ=$(($(ethtool -l $BASE_DEVICE | grep Combined: | tail -1 | cut -c10-) + 0))
	if (( $NEED_RXQ > $MAX_RXQ )); then
		echo "Invalid number of RX Queues: $NUM_QUEUE for Device $BASE_DEVICE. Maximum is $MAX_RXQ"
		exit 1
	fi

	if (( $NEED_RXQ > $NUM_RXQ )); then
		if $SET_RXQ; then
			echo "Increasing number of RX Queues to: $NEED_RXQ for Device $BASE_DEVICE"
			exec_cmd_check_return ethtool -L $BASE_DEVICE combined $NEED_RXQ
			NUM_RXQ=$NEED_RXQ
		fi
	fi
else
# Not combined
	NUM_RXQ=$(($(ethtool -l $BASE_DEVICE | grep RX: | tail -1 | cut -c4-) + 0))
	if (( $NEED_RXQ > $MAX_RXQ )); then
		echo "Invalid number of RX Queues: $NUM_QUEUE for Device $BASE_DEVICE. Maximum is $MAX_RXQ"
		exit 1
	fi

	if (( $NEED_RXQ > $NUM_RXQ )); then
		if $SET_RXQ; then
			echo "Increasing number of RX Queues to: $NEED_RXQ for Device $BASE_DEVICE"
			exec_cmd_check_return ethtool -L $BASE_DEVICE rx $NEED_RXQ
			NUM_RXQ=$NEED_RXQ
		fi
	fi
fi

if $SET_NTUPLE; then
	# Enable ntuple filtering (needed for both fixed rules and aRFS)
	echo "Enabling $BASE_DEVICE ntuple filtering"
	exec_cmd_check_return ethtool -K $BASE_DEVICE ntuple on
elif $CLEAN; then
	# Disable ntuple filtering
	echo "Disabling $BASE_DEVICE ntuple filtering"
	exec_cmd_check_return ethtool -K $BASE_DEVICE ntuple off
fi

if $SET_RPS_SOCK_FLOW_ENTRIES; then
	# Enable RPS system-wide
	echo "Setting /proc/sys/net/core/rps_sock_flow_entries to $RPS_SOCK_FLOW_ENTRIES"
	write_file_check_return $RPS_SOCK_FLOW_ENTRIES /proc/sys/net/core/rps_sock_flow_entries
elif $CLEAN; then
	# Disable RPS system-wide
	echo "Setting /proc/sys/net/core/rps_sock_flow_entries to 0"
	write_file_check_return 0 /proc/sys/net/core/rps_sock_flow_entries
fi

if $SET_RXQ_RPS_FLOW_CNT; then
	# Enable RPS for each queue
	RPS_FLOW_COUNT_Q=$(($RPS_SOCK_FLOW_ENTRIES / $NUM_QUEUE))
	for q in $(seq $BASE_QUEUE $ENDQ); do
		echo "Setting /sys/class/net/$BASE_DEVICE/queues/rx-$q/rps_flow_cnt to $RPS_FLOW_COUNT_Q"
		write_file_check_return $RPS_FLOW_COUNT_Q /sys/class/net/$BASE_DEVICE/queues/rx-$q/rps_flow_cnt
	done
elif $CLEAN; then
	#Disable RPS for each queue
	for q in $(seq $BASE_QUEUE $ENDQ); do
		echo "Setting /sys/class/net/$BASE_DEVICE/queues/rx-$q/rps_flow_cnt to 0"
		write_file_check_return 0 /sys/class/net/$BASE_DEVICE/queues/rx-$q/rps_flow_cnt
	done
fi

if $SET_FILTER_RULES; then
	# Create rules
	for i in $(seq 0 $(($NUM_CHANNELS - 1))); do
		RXQ=$(($BASE_QUEUE + ($i % $NUM_RXQ)))
		echo "Creating rules for channel $i port $(($SIW_BASE_PORT + $i)) to rx-queue $RXQ"
		exec_cmd_check_return ethtool -U $BASE_DEVICE flow-type tcp4 dst-port $(($SIW_BASE_PORT + $i)) action $RXQ loc $(($RPS_BASE_LOC + $i))
		exec_cmd_check_return ethtool -U $BASE_DEVICE flow-type tcp4 src-port $(($SIW_BASE_PORT + $i)) action $RXQ loc $(($RPS_BASE_LOC + $i + $NUM_CHANNELS))
	done
elif $CLEAN; then
	for i in $(ethtool -u $BASE_DEVICE | grep Filter | cut -d: -f2); do
		echo "Deleting n-tuple rule $i"
		exec_cmd_check_return ethtool -U $BASE_DEVICE delete $i
	done
fi

proc_int_cache=$(mktemp)
cat /proc/interrupts > $proc_int_cache

# Getting NIC IRQs
declare -A NIC_IRQS
N_NIC_IRQ=0
for i in $(ls /sys/class/net/$BASE_DEVICE/device/msi_irqs | sort -n); do
	IRQ_NAME=$(grep -E "^\s*$i:" $proc_int_cache | awk '{print $NF}')
	ASYNC_IRQ=$(grep -E "^\s*$i:" $proc_int_cache | grep "async\|cmd\|page" -c)
	if (( $ASYNC_IRQ == 0 )); then
		if [ -d /proc/irq/$i ]; then
			echo "Found RX IRQ $N_NIC_IRQ - $IRQ_NAME"
			NIC_IRQS[$N_NIC_IRQ]=$i
			N_NIC_IRQ=$(($N_NIC_IRQ + 1))
		fi
	else
		echo "Skipping async IRQ $IRQ_NAME"
	fi
done

declare -a CPU_ARRAY
NIC_N_CPU=0

# ------------------------------------------------------------------------------
# Affinity Domain (pernuma, persocket, fullspread, custom-list)
#
# Domain of CPUs to use for TCP RX
#
# pernuma - All CPUs with the same NUMA node as the NIC
#
# persocket - All CPUs with the same socket as the NIC
#
# fullspread - All CPUs
#
# custom-list - List of CPUs separated by commas eg "16,17,18,19" - can be generated using seq -c,
#
# ------------------------------------------------------------------------------
NIC_NUMA_NODE=$(cat /sys/class/net/$BASE_DEVICE/device/numa_node)
NIC_SOCKET=${NUMA_2_SOCK[$NIC_NUMA_NODE]}
case $AFFINITY_DOMAIN in
	pernuma)
		NIC_N_CPU=${NUM_CPUS_PER_NUMA[$NIC_NUMA_NODE]}
		for ((i=0;i<$NIC_N_CPU;i++)); do
			CPU_ARRAY[$i]=${TBL_CPUS_PER_NUMA[$NIC_NUMA_NODE,$i]}
		done
		;;
	persocket)
		NIC_N_CPU=${NUM_CPUS_PER_SOCK[$NIC_SOCKET]}
		for ((i=0;i<$NIC_N_CPU;i++)); do
			CPU_ARRAY[$i]=${TBL_CPUS_PER_SOCK[$NIC_SOCKET,$i]}
		done
		;;
	fullspread)
		NIC_N_CPU=${NUM_CPUS_PER_HOST[0]}
		for ((i=0;i<$NIC_N_CPU;i++)); do
			CPU_ARRAY[$i]=${TBL_CPUS_PER_HOST[0,$i]}
		done
		;;
	*)
		IFS=', ' eval 'CPU_ARRAY=($AFFINITY_DOMAIN)'
		NIC_N_CPU=${#CPU_ARRAY[@]}
		echo "Custom Affinity Domain: ${CPU_ARRAY[@]}"
		;;
esac

# ------------------------------------------------------------------------------
# RPS Mode (All NUMA, All Socket, Full-Spread, IRQ-Wrap, IRQ-Neighbour, None)
#
# RPS selects the CPU to perform protocol processing above the interrupt handler.
# This is accomplished by placing the packet on the desired CPU’s backlog queue
# and waking up the CPU for processing.
#
# The CPU is chosen from the rps_cpus mask for the RX Queue based on the RSS Hash.
# It adds some additional processing to the interrupt
#
# All Domain   	- All CPUs in the Affinity Domain are available for the Queue. There will be CPU overlaps between the queues
#
# IRQ-Wrap    	- Each RX Queue is assigned CPUs b + q, b + q + nq, b + q + 2nq, ... where b - Base IRQ CPU, q - RXQ Number, nq - Number of RXQs
#
# Not-IRQ - Remaining CPUs after IRQs have been assigned are divided up amongst the RX Queues.
#
# None		- RPS is off. The RX Queue IRQ CPU processes all packets from the queue
#
# ------------------------------------------------------------------------------

case $RPS_MODE in
	alldomain)
		SET_RXQ_RPS_CPUS=true
		RPS_CPUS_BASE_IDX=0
		RPS_CPUS_STRIDE=1
		RPS_CPUS_Q_STRIDE=0
		RPS_CPUS_Q_N_CPU=$NIC_N_CPU
		if (($RPS_CPUS_Q_N_CPU <= 1)); then
			warn_log "Not enough CPUs in domain for RPS Mode: $RPS_MODE"
		fi
		;;
	irqwrap)
		SET_RXQ_RPS_CPUS=true
		RPS_CPUS_BASE_IDX=0
		RPS_CPUS_STRIDE=$N_NIC_IRQ
		RPS_CPUS_Q_STRIDE=1
		RPS_CPUS_Q_N_CPU=$(($NIC_N_CPU / $N_NIC_IRQ))
		if (($RPS_CPUS_Q_N_CPU <= 1)); then
			warn_log "Not enough CPUs in domain for RPS Mode: $RPS_MODE"
		fi
		;;
	notirq)
		SET_RXQ_RPS_CPUS=true
		RPS_CPUS_BASE_IDX=$N_NIC_IRQ
		RPS_CPUS_STRIDE=1
		RPS_CPUS_Q_N_CPU=$((($NIC_N_CPU - $N_NIC_IRQ) / $NUM_QUEUE))
		RPS_CPUS_Q_STRIDE=$RPS_CPUS_Q_N_CPU
		if (($RPS_CPUS_Q_N_CPU <= 1)); then
			warn_log "Not enough CPUs in domain for RPS Mode: $RPS_MODE"
		fi
		;;
	off)
		SET_RXQ_RPS_CPUS=true
		RPS_CPUS_BASE_IDX=0
		RPS_CPUS_STRIDE=0
		RPS_CPUS_Q_N_CPU=0
		RPS_CPUS_Q_STRIDE=0
		;;
	donttouch) 
		SET_RXQ_RPS_CPUS=false
		;;
	*)
		err_log "Invalid RPS Mode $RPS_MODE"
		exit 1
	;;
esac

# ------------------------------------------------------------------------------
# Set the RX Queues RPS CPUs mask according to the mode
# ------------------------------------------------------------------------------
for i in $(seq 0 $(($NUM_QUEUE - 1))); do
	RXQ=$(($BASE_QUEUE + $i))
	if $SET_RXQ_RPS_CPUS; then
		RX_CPU_IDX=$(($RPS_CPUS_BASE_IDX + $i * $RPS_CPUS_Q_STRIDE))
		RX_CPU_LIST=""
		for j in $(seq 1 $RPS_CPUS_Q_N_CPU); do
			RX_CPU=${CPU_ARRAY[$RX_CPU_IDX]}
			RX_CPU_LIST="${RX_CPU_LIST} ${RX_CPU}"
			RX_CPU_IDX=$(($RX_CPU_IDX + $RPS_CPUS_STRIDE))
		done
		RX_CPU_MASK=$(cpu_list_to_mask $RX_CPU_LIST)
		echo "Setting CPUs $RX_CPU_LIST (0x${RX_CPU_MASK}) for $BASE_DEVICE RX Queue $RXQ RPS"
		write_file_check_return $RX_CPU_MASK /sys/class/net/$BASE_DEVICE/queues/rx-$RXQ/rps_cpus
	elif $CLEAN; then
		echo "Setting rps_cpus of $BASE_DEVICE RX Queue $RXQ to 0"
		write_file_check_return 0 /sys/class/net/$BASE_DEVICE/queues/rx-$RXQ/rps_cpus
	fi
done

# ------------------------------------------------------------------------------
# Set SMP affinity to device's irqs according to CPUs in domain
# ------------------------------------------------------------------------------
if $SET_IRQ; then
	if systemctl is-active --quiet irqbalance; then
		echo "Stop irqbalance daemon..."
		exec_cmd_check_return systemctl stop irqbalance
	fi

	for i in $(seq 0 $(($N_NIC_IRQ - 1))); do
		RX_CPU_IDX=$(($i % $NIC_N_CPU))
		RX_CPU=${CPU_ARRAY[$RX_CPU_IDX]}
		RX_CPU_MASK=$(cpu_list_to_mask $RX_CPU)
		IRQ=${NIC_IRQS[$i]}
		IRQ_NAME=$(grep -E "^\s*$IRQ:" $proc_int_cache | awk '{print $NF}')
		echo "Setting CPU $RX_CPU (${RX_CPU_MASK}) for $BASE_DEVICE IRQ $IRQ - $IRQ_NAME"
		write_file_check_return $RX_CPU_MASK /proc/irq/$IRQ/smp_affinity
	done
elif $CLEAN; then
	for i in $(seq 0 $(($N_NIC_IRQ - 1))); do
		DFLT_CPU_MASK=$(cat /proc/irq/default_smp_affinity)
		IRQ=${NIC_IRQS[$i]}
		IRQ_NAME=$(grep -E "^\s+$IRQ:" $proc_int_cache | awk '{print $NF}')
		echo "Setting Default Affinity Mask (0x${DFLT_CPU_MASK}) for $BASE_DEVICE IRQ $IRQ - $IRQ_NAME"
		write_file_check_return $DFLT_CPU_MASK /proc/irq/$IRQ/smp_affinity
	done

	if systemctl is-enabled --quiet irqbalance; then
		echo "Starting irqbalance daemon..."
		exec_cmd_check_return systemctl start irqbalance
	fi
fi
