# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-only OR Apache-2.0

#
obj-m += nvmeib_keeper.o
nvmeib_keeper-y := ../utils/nvmeib_jdr/nvmeib_jdr.o nvmeib_keeper_main.o
