#!/bin/bash

MDIR="/opt/nvmesh/target-repo"
NVMLOGDIR="/var/log/nvmesh"
MANAGEMENTCONFDIR="/etc/nvmesh"
MANAGEMENTCONFFILE="$MANAGEMENTCONFDIR/nvmesh.conf"
UPGRADEERRORPATH="/var/opt/nvmesh/target-upgrade.err"
versionregex='^([0-9]+.){2}[0-9]+-[0-9]+'
LOGFILE="$NVMLOGDIR/nvmesh-target-install`date '+%Y%m%d-%R'`.log"
isUpgrade=true

if [ $1 -eq 1 ]; then
        isUpgrade=false
fi

runcommand () {
        # $1 is the message
        # $2 is the command to run
        # $3 is whether to check for error (1=yes, 0=no)
        echo "$1" | tee -a $LOGFILE
        echo "$2" >>$LOGFILE
        $2 >>$LOGFILE 2>&1
        ERR=$?
        if [ $3 -ne 0 ] ; then
                if [ $ERR -ne 0 ] ; then
                        echo "ERROR, command failed:"
                        echo $2
                        echo "See logfile: $LOGFILE"
                        echo "Exiting..."
                        exit 1
                fi
        fi
}

if [[ $(uname -v) =~ "Ubuntu" ]]
then
        chkconfig="update-rc.d"
        start_cmd="start 20 3 4 5"
else
        chkconfig="chkconfig --level 345"
        start_cmd="on"
fi

if ! $isUpgrade; then
	echo "Attempting Target installation at `date`" > $LOGFILE

	runcommand "Configuring init..." "$chkconfig nvmeshtarget $start_cmd" 1
else
	if [ ! -s $UPGRADEERRORPATH ] ; then 
		currentVersion=$(rpm -q --queryformat '%{version}-%{release}|' nvmesh-target)

		if [[ $currentVersion =~ $versionregex ]] ; then
			match=${BASH_REMATCH}
			echo 'install_'$match > $UPGRADEERRORPATH
		fi
	fi
fi

echo "Done!"
exit 0
