/*
* SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
* SPDX-License-Identifier: GPL-2.0-only OR Apache-2.0
*/

#ifndef NVMEIBC_CINST_PARAMS_H
#define NVMEIBC_CINST_PARAMS_H

#include "nvmeib_shared.h"

/* Defines the parameters for each client instance  */
#define CINST_NAME_LEN	8						// Daniel: Arbitrary choice. Dont add () around it, as it is used as string
struct nvmeibc_cinst_name {
	char str[CINST_NAME_LEN];					// Both the name and directory of block devices
};

#include "nvmeibc_mcs_stub.h"
/************** Todo: Move the struct below to main only include **************/
struct nvmeibc_cinst_params_main {			// Params to block layer
	const char *proc_dir_root_name;			// /proc/<dir/... of this instance
	struct t_cinst_params_main_mgmt {
		const char *cluster;				// Management cluster information (IPs of server, used by MCS)
		char db_uuid[34];					// UUID of 32[bytes] + '\0x0'
		bool use_https;						// Management protocol (http or https, used by MCS) - updated after init of main params
		bool is_auto_generated;				// Instance is autogenerated to support connection to multiple mgmts
	} mgmt;
	struct nvmeibc_config_profile cfg_profile;
	spinlock_t param_change_lock;			// Lock to serialize parameters update and paramters print via proc file. Needed because 'management_cluster' can be reallocated
	void **_private;						// Place where software layer should insert its private data for this instance
};
int nvmeibc_cinst_get_main_inst_num(const struct nvmeibc_cinst_params_main *p);
#define nvmeibc_cinst_is_first_main_instance(p) (nvmeibc_cinst_get_main_inst_num(p) == 0)

/************** Todo: Move the struct below to blok only include **************/
struct nvmeibc_cinst_params_blk {			// Params to block layer
	void **_private;						// Place where software layer should insert its private data for this instance
	struct nvmeibc_cinst_name dev_name;		// Directory under which volumes will be seen in cat /proc/devices | grep -e nvmeibc  Example: "nvmeibc"
	struct nvmeibc_cinst_name dir_lsblk;	// Directory under which volumes will be seen in /dev/, /sys/block/, also via lsblk.  Example: "nvmesh"
	u32 binje;								// EC multi slice size (N)
};
int nvmeibc_cinst_get_blok_inst_num(const struct nvmeibc_cinst_params_blk *p);
#define nvmeibc_cinst_is_first_blok_instance(p) (nvmeibc_cinst_get_blok_inst_num(p) == 0)

/************** Todo: Move the struct below to core only include **************/
struct nvmeibc_cinst_params_core {			// Params to core/transport layer
	void **_private;						// Place where software layer should insert its private data for this instance
	const char *filter_ports;
	const char *filter_guids;
	unsigned max_p_len;
	unsigned max_g_len;
	unsigned max_nic_srqs;
	unsigned sm_th;
	bool use_pcpu_cq;
	bool use_rdda;
	binje_t binje;
	unsigned int tcp_mode; /* see nvmeibc_tcp_mode */
};
int nvmeibc_cinst_get_core_inst_num(const struct nvmeibc_cinst_params_core *p);
#define nvmeibc_cinst_is_first_core_instance(p) (nvmeibc_cinst_get_core_inst_num(p) == 0)

/********************* Cummulative params of clnt instance ********************/
struct nvmeibc_cinst_params {					// Parameters that vary between instances of clients
	u16 index;									// Index in the array of clients
	struct nvmeibc_cinst_params_main main;
	struct nvmeibc_cinst_params_blk  blok;
	struct nvmeibc_cinst_params_core core;
};

const struct nvmeibc_cinst_params* nvmeibc_cinst_get_by_name(const char *name); // Get specific instance by name
#define nvmeibc_cinst_is_first_instance(p)  ((p)->index == 0)					// First instance is special in many ways
const struct nvmeibc_cinst_params* nvmeibc_cinst_array_get_itr_i_unsafe(int i);	// Daniel: Dont use this function, needed for mellanox hack only

#endif

