#!/usr/bin/env python3

import sys
import json
import math
import typing
import pprint
import argparse
import collections


class Metric(typing.NamedTuple):
	name: str
	size: int
	count: int
	average: int 

	@property
	def size_count_average(self):
		return (self.size, self.count, self.average)


class Channel(typing.NamedTuple):
	name: str
	first_trace_ts_ns: int
	last_trace_ts_ns: int
	count_system_trace: int
	TRACES: list[Metric]
	TOKENS: list[Metric]
	FUNCTIONS: list[Metric]
	FILES: list[Metric]

	@property
	def empty(self) -> bool:
		return self.first_trace_ts_ns == 0 \
				and self.last_trace_ts_ns == 0 \
				and self.count_system_trace == 0 \
				and bool(self.TRACES) == False \
				and bool(self.TOKENS) == False \
				and bool(self.FUNCTIONS) == False \
				and bool(self.FILES) == False

	@property
	def metrics(self) -> tuple[list[Metric]]:
		return (self.TRACES, self.TOKENS, self.FUNCTIONS, self.FILES)

#"/home/roman/tmp/trace_daemon/long_core": {
#	"first_trace_ts_ns": 0,
#	"last_trace_ts_ns": 0,
#	"count_system_trace": 0,
#	"TRACES": {
#		"trace_toma_toma_process_req": {
#			"count": 6,
#			"size": 153,
#			"avg": 25
#		},
#		...
#	},
#	"TOKENS": {...},
#	"FUNCTIONS": {...},
#	"FILES": {...}
#}
#

def load_metrics(name, values) -> list[Metric]:
	metrics: list[Metric] = []
	for name, properties in values.items():
		count = properties['count']
		size = properties['size']
		average = math.ceil(size / count) if count else 0
		metric = Metric(name=name, size=size, count=count, average=average)
		metrics.append(metric)
	return metrics


def dump_metrics(metrics: list[Metric]) -> typing.OrderedDict[str, typing.Any]:
	result = typing.OrderedDict()
	for m in metrics:
		result[m.name] = dict(count=m.count, size=m.size, average=m.average)
	return result
	

def load_channels(data) -> list[Channel]:
	channels: list[Channel] = []
	for channel_name, info in data.items():
		channel = Channel(name=channel_name,
							first_trace_ts_ns=info['first_trace_ts_ns'],
							last_trace_ts_ns=info['last_trace_ts_ns'],
							count_system_trace=info['count_system_trace'],
							TRACES=load_metrics('TRACES', info['TRACES']),
							TOKENS=load_metrics('TOKENS', info['TOKENS']),
							FUNCTIONS=load_metrics('FUNCTIONS', info['FUNCTIONS']),
							FILES=load_metrics('FILES', info['FILES']))
		channels.append(channel)
	return channels

def dump_channel(channel: Channel) -> typing.OrderedDict[str, typing.Any]:
	result = typing.OrderedDict()
	result['first_trace_ts_ns'] = channel.first_trace_ts_ns
	result['last_trace_ts_ns'] = channel.last_trace_ts_ns
	result['count_system_trace'] = channel.count_system_trace
	result['TRACES'] = dump_metrics(channel.TRACES)
	result['TOKENS'] = dump_metrics(channel.TOKENS)
	result['FUNCTIONS'] = dump_metrics(channel.FUNCTIONS)
	result['FILES'] = dump_metrics(channel.FILES)
	return result

def dump_channels(channels: list[Channel]) -> typing.OrderedDict[str, typing.Any]:
	result = typing.OrderedDict()
	for channel in channels:
		if not channel.empty:
			result[channel.name] = dump_channel(channel)
	return result



def process_channel(channel: Channel, top: int):
	for lst in channel.metrics:
		lst.sort(key=lambda m: m.size_count_average, reverse=True)
		del lst[top:]

if __name__ == '__main__':
	parser = argparse.ArgumentParser(description=' pager statistics analyzer')
	parser.add_argument('-s', '--statistics', type=argparse.FileType('r', encoding='ascii'), help="statistics file, generated by pager")
	parser.add_argument('-t', '--top', type=int, default=30, help="number of metrics to show")
	
	args = parser.parse_args()

	data = json.load(args.statistics) 
	channels = load_channels(data)
	for channel in channels:
		process_channel(channel, args.top)

	result = dump_channels(channels)
	json.dump(result, sys.stdout, indent=2)
	#pprint.pprint(channels)
