# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

AGENT_LOGGING_LEVEL="DEBUG"
BLACKLIST_NICS=""
CONFIGURED_NICS="ens7f0;ens7f1;enp65s0f0v0:[10.191.0.34]"
####
CONFIG_PROFILE_ID="2ec35a73-897c-11f0-b856-69c9b7c8d735"
CONFIG_PROFILE_NAME="Cluster Default"
CONFIG_PROFILE_VERSION="1"
DUMP_FTRACE_ON_OOPS="False"
IPV4_ONLY="True"
TCP_ENABLED="No"
TCP_ONLY="No"
####
MANAGEMENT_PROTOCOL="https"
MANAGEMENT_SERVERS="nvme34.lab.nvidia.com:4001"
KAFKA_SERVERS="nvme34.lab.nvidia.com:9092,nvme44.lab.nvidia.com:9092"
MCS_LOGGING_LEVEL="DEBUG"
AGENT_LOGGING_LEVEL="DEBUG"
MLX5_RDDA_ENABLED="No"
MAX_CLIENT_RSRC="0"
_REST_SERVERS="nvme34.lab.nvidia.com:4001,nvme44.lab.nvidia.com:9092"
### Credentials
KAFKA_TLS_ENABLED="true"
KAFKA_CA="_root/etc/nvmesh/tls/Kafka_ca_chain.crt"
KAFKA_TOMA_CERTIFICATE="_root/etc/nvmesh/tls/Kafka-zone1.TOMA.crt"
KAFKA_TOMA_KEY="_root/etc/nvmesh/tls/Kafka-zone1.TOMA_key.txt"

KAFKA_MCS_CERTIFICATE="_root/etc/nvmesh/tls/Kafka-MCS.crt"
KAFKA_MCS_KEY="_root/etc/nvmesh/tls/Kafka-MCS_key.txt"

#_REST_AUTH_METHOD="credentials"
_REST_AUTH_METHOD="MTLS"
_REST_CA="_root/etc/nvmesh/tls/rest_ca_chain.crt"



