
# Please read the corosync.conf.5 manual page
system {
        # This is required to use transport=knet in an unprivileged
        # environment, such as a container. See man page for details.
        allow_knet_handle_fallback: yes
}

totem {
        version: 2
        cluster_name: DHScluster

        # crypto_cipher and crypto_hash: Used for mutual node authentication.
        # If you choose to enable this, then do remember to create a shared
        # secret with "corosync-keygen".
        # enabling crypto_cipher, requires also enabling of crypto_hash.
        # crypto works only with knet transport
        crypto_cipher: none
        crypto_hash: none
        #udpu udp knet
        transport: knet
        interface {
                ringnumber: 0
                bindnetaddr: 127.0.0.0
                broadcast: yes
                mcastport: 2049
        }
}

logging {
        fileline: off
        to_stderr: yes
        to_logfile: no
        logfile: /var/log/corosync/corosync.log
        to_syslog: no
        debug: on
        #timestamp: hires
        logger_subsys {
                subsys: QUORUM
                debug: off
        }
}

quorum {
        # Enable and configure quorum subsystem (default: off)
        # see also corosync.conf.5 and votequorum.5
        provider: corosync_votequorum
        expected_votes: 21
        two_node: 0
        device {
                model: toma_based_raft
                votes: 16
        }
}

nodelist {
        # Change/uncomment/add node sections to match cluster configuration
        node {
                # Hostname of the node.
                name: DHSHnode1
                nodeid: 1
                ring0_addr: 127.0.0.1
                quorum_votes: 3
        }
        node {
                name: DHSHnode
                nodeid: 2
                ring0_addr: 192.168.1.137
                quorum_votes: 2
        }
}
