# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

##################################################################################
#Don't edit this file as it will be removed after nvmeshservice will be turned off
#use nvmesh_xyz.conf to overide/add module params
##################################################################################
install nvmeib_common_public  /sbin/modprobe --ignore-install `[ -f /etc/SuSE-release ] && echo "--allow-unsupported"` nvmeib_common_public ib_odp_info=`grep -c ib_umem_odp_get /proc/kallsyms 2> /dev/null || ( [ $? = 2 ] && echo -1 )` $CMDLINE_OPTS

# SoftiWARP Options
options siw mpa_crc_required=0 zcopy_tx=Y low_delay_tx=N
