#ifndef NVMEIBC_DP_ELEVATOR_H
#define NVMEIBC_DP_ELEVATOR_H

#define ND_OP_CACHE_LEN 16
#define ELEVATOR_TIMERS_IMPLEMENTATION (0)					// No need for timers, we use the even of scheduling out the user space task which issues IO's as async event to start io execution
#define USE_1_ELEV_HASH_TO_ALL_BDEVS 	(ELEVATOR_TIMERS_IMPLEMENTATION)	// Coz timers dont support yet a separated hash for each bdev

struct nvmeibc_elevator_operation_hash {
	struct spinlock lock;								// Lock for hash table
	#if ELEVATOR_TIMERS_IMPLEMENTATION
		struct radix_tree_root tree;					// Hash table, used to avoid bugs of del_timer() while timer is running. Can use del_timer_sync() and not need hash table at all
		ulong id;										// Evergrowing value for keys to hash table
	#endif
};

struct nvmeibc_blk_op_elevator {
	struct nvmeibc_merge_op_cache_t {
		struct operation *op;
		#if ELEVATOR_TIMERS_IMPLEMENTATION
			TIMER_LIST_INSTANCE(timer);
			ulong id;										// One of the id's generated by hash
		#endif
	} cache[ND_OP_CACHE_LEN];
	int		n_elem;
	#if !USE_1_ELEV_HASH_TO_ALL_BDEVS
		struct nvmeibc_elevator_operation_hash hash;
	#endif
};

void    nvmeibc_blk_op_elevator_init(   struct nvmeibc_blk_op_elevator *);
void    nvmeibc_blk_op_elevator_destroy(struct nvmeibc_blk_op_elevator *);
ssize_t nvmeibc_blk_op_elevator_string( struct nvmeibc_blk_op_elevator *, char *buf, size_t len, char fmt);

#endif  // H beginning

