
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

all:
	gcc -lrt -Wall -g -o aio_in_air aio_in_air.c
clean:
	rm -f aio_in_air aio_in_air.o
