# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-only OR Apache-2.0

#

obj-m += nvmeiba.o
nvmeiba-y := nvmeiba_infra.o nvmeiba_main.o nvmeiba_atom_os_api.o ../../utils/nvmeib_jdr/nvmeib_jdr.o

