#ifndef NVMESH_SIM_H
#define NVMESH_SIM_H
/* Simulator of the whole NVMesh cluster */
#include "./mgmt/nvmeibm_conf_db.h"
#include "./clnt/nvmeibc_user_space_simu.h"
#include "./mgmt/nvmeibm_mcs_simu.h"
#include "./server/nvmeibs_main_sim.h"
#include "di_tracker.h"

struct jdr;

struct NVMeshSystem {
	int nServers, nClients;									// Amount of storage servers and clients.
	struct serverSimulator servers[NVMESH_N_PHYS_DISKS];	// Array  of storage servers (maximum defined amount)
	struct clientSimulator clients[NVMESH_N_MAX_CLIENTS];	// Currently only one client is allowed
	struct mgmt_simu mgmt;									// Managment

	struct mongo_db_simu mdb;								// Global configuration (stored in mongo db), Clnts gets attach message autogenerated from mongo db
	struct tTopoOfNVMesh tcf;								// Global configuration as seen by Tomas (auto generated from mongo db)

	struct di_tracker di_tracker;							// Data integrity tracker

	struct {												// Prevent new IO entry from async IO threads while waiting for system to quiesce
		unsigned n_requestors;
		pthread_mutex_t mutex;
		pthread_cond_t cond;
	} async_io_gate;
};

void NVMeshSystem_gen_cmd_hooks_setup_single_disk(struct nvmeibc_disk* disk, struct nvmeibc_disk_hooks *hooks);
void NVMeshSystem_gen_cmd_hooks_setup_all_disks(struct NVMeshSystem *sys, struct nvmeibc_disk_hooks *hooks);
void NVMeshSystem_gen_cmd_hooks_clean_all_disks(struct NVMeshSystem *sys);
u32 NVMeshSystem_get_n_trans_err_injected(struct NVMeshSystem *sys);

int  NVMeshSystem_init(   	 struct NVMeshSystem *sys);		// Create the entire system.
int  NVMeshSystem_destroy(	 struct NVMeshSystem *sys);		// Destroy the entire system. Errors and memory leaks are tested
// TODO replace all n_vols with client->nBdevs for now set and unset
void NVMeshSystem_set_mtv_volumes(struct NVMeshSystem *sys);	// MTV requires QLC volume configuration for verification and attachment
void NVMeshSystem_unset_mtv_volumes(struct NVMeshSystem *sys);	// QLC volumes cannot attach on their own and need to be ignored
void NVMeshSystem_set_wcv_volumes(struct NVMeshSystem *sys);	// Set volume 0 type to WCV
void NVMeshSystem_unset_wcv_volumes(struct NVMeshSystem *sys);
void NVMeshSystem_service_nvmeshclient_start(struct NVMeshSystem *sys, int inst_id); // Initialize client service, nomally needs to be done at init only

/* Create new client instance, initialize service, attach it to all volumes @return new client id */
int  NVMeshSystem_new_client_add(struct NVMeshSystem *sys);
void NVMeshSystem_new_client_rmv(struct NVMeshSystem *sys, int inst_id);

void NVMeshSystem_attach_client_to_all_volumes(  struct NVMeshSystem *sys, int inst_id);
void NVMeshSystem_detach_client_from_all_volumes(struct NVMeshSystem *sys, int inst_id);

void NVMeshSystem_serialize( struct NVMeshSystem *sys);		// Wait for all communications and parallel work to terminate. The main thread is the only one which will be active upon exiting this method
bool NVMeshSystem_is_stable( struct NVMeshSystem *sys);		// Verify that no errors are present in the system. Call this function in a steady state of the system (no unregisters,pause,cont,attach,detach,etc) is allowed.

void NVMeshSystem_async_io_gate_init(struct NVMeshSystem *sys);
void NVMeshSystem_async_io_gate_destroy(struct NVMeshSystem *sys);
void NVMeshSystem_async_io_gate_get(struct NVMeshSystem *sys);
void NVMeshSystem_async_io_gate_put(struct NVMeshSystem *sys);
void NVMeshSystem_async_io_gate_wait(struct NVMeshSystem *sys);

void NVMeshSystem_wipe_all_disks(      struct NVMeshSystem *sys);
void NVMeshSystem_wipe_all_md_of_disks(struct NVMeshSystem *sys);
void NVMeshSystem_precondition_all_disks_for_EC(struct NVMeshSystem *sys);		// Format with metadata and precondition all discs
void NVMeshSystem_precondition_all_disks_for_R1(struct NVMeshSystem *sys);		// Format with metadata for mirror
void NVMeshSystem_volume_memset(struct NVMeshSystem *sys, int v, u8 val);
void NVMeshSystem_volume_wipe_MD(struct NVMeshSystem *sys, int v);
void NVMeshSystem_wipe_all_dirty_bits( struct NVMeshSystem *sys);
void NVMeshSystem_set_all_txid_to_1(struct NVMeshSystem *sys);
void NVMeshSystem_verify_no_dirty_bits(struct NVMeshSystem *sys);
int  NVMeshSystem_wipe_all_stale_locks(struct NVMeshSystem *sys);				// Use in cases, scenario of unitests could leave stale locks if last IO could not clear its lock due to disk disconenction
int  NVMeshSystem_wipe_all_read_only_locks(struct NVMeshSystem *sys);			// Use in cases, scenario of unitests could leave is_read locks if last READ IO could not clear its lock due to disk disconenction
bool NVMeshSystem_is_stable(           struct NVMeshSystem *sys);
void NVMeshSystem_all_clients_dbg_di(  struct NVMeshSystem *sys, bool set);		// Move all clients all volumes to debug di mode and cancel this mode.
void NVMeshSystem_all_clients_di_metadata_wr(struct NVMeshSystem *sys, bool set); // Force all clients all volumes to write debug metadata
bool NVMeshSystem_all_clients_ec_edic(struct NVMeshSystem *sys, bool set);		// Enable all EC reads to check EDIC of read data and compare to MD EDIC
void NVMeshSystem_all_clients_read_has_mutable_bio_buffers(struct NVMeshSystem *sys, int value);
bool NVMeshSystem_all_clients_mirror_edic(struct NVMeshSystem *sys, bool set);		// Enable all Mirror reads to check EDIC of read data and compare to MD EDIC
void NVMeshSystem_set_ignore_jour_gc_launch_requests_from_serjio(struct NVMeshSystem *sys, bool value); //System wide sets ignore_jour_gc_launch_requests to the value
void NVMeshSystem_detectStuckIOs(      struct NVMeshSystem *sys, bool long_wait); // Wait for IO's to finish, if some IO's are stuck, prints the problematic topology.
void NVMeshSystem__printUncompletedIOs(struct NVMeshSystem *sys);				// Print all stuck IO's in the system (uncompleted operations). Use when you already expected all IO's to finish. Do not issue new io's when calling this function
void NVMeshSystem_di_tracking_enable(struct NVMeshSystem *sys);
void NVMeshSystem_di_tracking_disable(struct NVMeshSystem *sys);
void NVMeshSystem_di_tracking_reset(struct NVMeshSystem *sys);
void NVMeshSystem_di_tracking_reconf(struct NVMeshSystem *sys, bool for_ec);

/* Debugging methods: Messing with internals of block device */
struct nvmeibc_topology * ___get_tail_topo_of_device(struct NVMeshSystem *sys, int v);	// Do not hold ref count to topo. Use with greate care, it can get free!

/**************************** Low layer events API ****************************/
void NVMeshSystem__invoke_pause_on_disk(	 struct NVMeshSystem *sys, int disk_id);							/* simulate the case when toma decided to disconnect the client from a physical disk */
void NVMeshSystem__invoke_cont_on_disk(		 struct NVMeshSystem *sys, int disk_id, bool leave_toma_not_ready);
void NVMeshSystem__invoke_pause_cont_on_disk(struct NVMeshSystem *sys, int disk_id);

void NVMeshSystem_check_no_abandoned(struct NVMeshSystem *sys);
void NVMeshSystem__verify_all_serjios_are_clean(struct NVMeshSystem *sys);
/*********************** NVMesh Configuration changes *************************/
void NVMeshSystem_swap_disk_between_servers(struct NVMeshSystem *sys, int n1, int n2);
void NVMeshSystem_DiskReappearEvent(        struct NVMeshSystem *sys, int n1, int n2, bool revert);
void NVMeshSystem_notify_new_disk_sgmnts(struct NVMeshSystem *sys);

/*********************** Config-to-client Propagator **************************/
//Todo: make order in this: Attacher/DEtacher/Class
void send_command_predefined_to_all(struct NVMeshSystem *sys, int inst_id);
void send_command_to_all(           struct NVMeshSystem *sys, int inst_id, enum volumeCommands cmd);
void send_command_to_vols(          struct NVMeshSystem *sys, int inst_id, enum volumeCommands cmd, u8 n_volumes, struct volumeDescriptor *volumes);
void send_command_to_vol_safe_detach_no_wait(struct NVMeshSystem *sys, int inst_id, int v);
void send_command_to_vol(           struct NVMeshSystem *sys, int inst_id, int v, enum volumeCommands cmd);
int  send_command_to_vol_attach_or_update(struct NVMeshSystem *sys, int inst_id, int v);			/* The actual command to start relocation */

int NVMeshSystem_send_volumes_config_to_clients_with_param(struct NVMeshSystem *sys, int inst_id, int vur, bool preempt, u64 reservation_version, bool allow_sub_block_io);
int NVMeshSystem_send_volumes_config_to_clients(struct NVMeshSystem *sys, int inst_id);

struct TstPRaid NVMeshSystem_TstPRaid_init_abs(struct NVMeshSystem *sys, u8 volume_index, u8 abs_praid_index);
struct TstPRaid NVMeshSystem_TstPRaid_init_rel(struct NVMeshSystem *sys, const struct volume_segment_index vsi);

//picks an existing disk range, which does not belong to this volume
struct TstPRaid NVMeshSystem_pick_other_volume_disk_range(struct NVMeshSystem *sys, const struct TstPRaid* raid);

/******************************************************************************/
struct slice_traits{	//TODO may be extended with chunk and raid references
	u16 chunk_idx;
	u16 raid_idx;
	u64 rlba		: 32;
	u64 slba		: 32;
	u16 replicas	: 8;
	u16 slice_size	: 8;
	roles_bmp_t tx_bm;
	u16 role2sgmnt[N_MAX_RAID_SLICE_LEN]; //mapping between role(D0, ... ,P, Q) and segment
	u16 sgmnt2role[N_MAX_RAID_SLICE_LEN]; //mapping from segment id to role(D0, ..., P, Q)
	u64 sgmnt2dlba[N_MAX_RAID_SLICE_LEN]; //mapping between segment id to it's dlba
	struct nvmeibc_roles_bmps roles_bmps;
	struct lock_ownership_map rlmap;		// lockset's lock ownership map, not really per slice
};
//[vlba .. vlba+length] should be in a single slice
struct slice_traits get_io_slice_traits(struct test_context ctx, u64 vlba, u32 length);

void jdr_write_slice_traits(struct jdr* jdr, char const* name, struct slice_traits* slice_traits);

struct io_traits{
	u64 vlba;
	u32 n_blocks; //construction args, describes the I/O range
	u16 start_first_slice;
	u16 n_slices;
	struct slice_traits *slices/*[n_slices]*/;
	struct slice_traits *last_slice;//pointer to the last slice
};

//returns slice_traits for each slice participating in I/O; for the time being the I/O should be within the single RAID
struct io_traits get_io_traits(struct test_context ctx, u64 vlba, u32 length);
void free_io_traits(struct io_traits* io_traits);

#endif // NVMESH_SIM_H
