# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

.SUFFIXES:
.PHONY: clean all
.DEFAULT_GOAL := all

CFLAGS  := -ggdb3 -Wall -Werror
LDFLAGS := -pthread
CC      := gcc
LD      := $(CC)
TRACE    =#@echo '>' $@ ;
DEPEND   = -MT $*.o -MMD -MP -MF $*.d
NVMESH_SRC_DIR ?= ../..

EXE := trace_daemon
OBJ := main.o trace_channel.o mmap_manager.o capuch_worker.o
OBJ := $(foreach obj,$(OBJ),$(shell realpath $(obj)))
LZA_INCLUDE := -I$(NVMESH_SRC_DIR)/lz4/lib
STATIC_LIBS := $(NVMESH_SRC_DIR)/lz4/lib/liblz4.a

DEP := $(OBJ:.o=.d)

-include $(DEP)

all: $(EXE)

$(EXE): $(OBJ)
	$(TRACE)$(LD) $(LDFLAGS) $(OBJ) $(STATIC_LIBS) -o $@

%.o: %.c Makefile
	$(TRACE)$(CC) $(CFLAGS) $(TOOLS_LIB) $(DEPEND) -o $@ -c $<

clean:
	$(TRACE)rm -rf $(EXE) $(OBJ) $(DEP)
