#ifndef NVMEIBS_TREND_TYPES_H
#define NVMEIBS_TREND_TYPES_H

#define GENERATE_LOGOUT_ENUM(PREFIX, ENUM) PREFIX##ENUM,
#define GENERATE_LOGOUT_STRING(PREFIX, STRING) #PREFIX#STRING,


#define FOREACH_LOGOUT_REASON(PREFIX, OP) \
	/* Gerneral logout reasons*/ \
	OP(PREFIX, SEND_RSP_FAILED) \
	OP(PREFIX, MSG_HANDLE_FAILED) \
	OP(PREFIX, RCV_COMPLETION_FAILED) \
	OP(PREFIX, SND_COMPLETION_FAILED) \
	OP(PREFIX, UNSOL_DISCONNECTION) \
	OP(PREFIX, IB_EVENT_QP_FATAL) \
	OP(PREFIX, IB_EVENT_QP_ACCESS_ERR) \
	OP(PREFIX, SCQ_SND_COMPLETION_FAILED) \
	OP(PREFIX, RCV_UNEXPECTED_IDX) \
	OP(PREFIX, RCV_ADD_WORK_FAILED) \
	OP(PREFIX, CM_ERR) \
	OP(PREFIX, CONNECTION_ERR) \
	OP(PREFIX, DREQ_FROM_CLNT) \
	OP(PREFIX, REMOVE_DISK) \
	OP(PREFIX, SERVER_EXIT) \
	OP(PREFIX, CHANGE_CLNT) \
	OP(PREFIX, JOURNAL_CLEAR) \
	OP(PREFIX, SERJIO_ERROR) \
	OP(PREFIX, PORTS_CLEAR) \
	OP(PREFIX, PORT_DISABLE) \
	OP(PREFIX, CLIENT_DISCONNECT) \
	OP(PREFIX, PROCFS_ERR) \
	OP(PREFIX, DEBUG) \
	/* Toma logout reason */ \
	OP(PREFIX, TOMA_SND_COMPLETION_FAILED) \
	OP(PREFIX, TOMA_WORK_ALLOC_FAILED) \
	OP(PREFIX, TOMA_SND_TIMEOUT) \
	OP(PREFIX, TOMA_SND_GET_IU_FAILED) \
	OP(PREFIX, TOMA_DISCONNECT) \
	OP(PREFIX, TOMA_LOGOUT) \
	OP(PREFIX, TOMA_LOGIN_CLEAR_ALL_CLIENTS) \
	OP(PREFIX, TOMA_PROC_CLOSE) \
	/* IO channels logout reasons */ \
	OP(PREFIX, IO_CH_SND_COMPLETION_FAILED) \
	OP(PREFIX, IO_CH_DISCONNECTION) \
	/* NRCH logout reasons */ \
	OP(PREFIX, NR_CH_SND_IO_CMD_FAILED) \
	OP(PREFIX, NR_CH_SND_RSP_FAILED) \
	OP(PREFIX, NR_CH_RCV_COMPLETION_FAILED) \
	OP(PREFIX, NR_CH_SND_COMPLETION_FAILED) \
	OP(PREFIX, NR_CH_SND_CQ_INTR_FAILED) \
    OP(PREFIX, NR_CH_DISCONNECTION) \
	OP(PREFIX, NR_CH_ALREADY_CONNECTED) \
	OP(PREFIX, NR_CH_NO_SEND_IOCTX_RSRC) \
	OP(PREFIX, NR_CH_VMAP_BB_FAILED) \
	/* lock channels logout reasons */ \
	OP(PREFIX, LOCK_CH_STOP) \
	/* admin channels logout reasons */ \
	OP(PREFIX, ADMIN_CH_STOP) \
	OP(PREFIX, ADMIN_CH_KA_SND_FAILED) \
	OP(PREFIX, ADMIN_REJECT_LOGIN_ALLOC_FAILED) \
	OP(PREFIX, ADMIN_REJECT_RCQ_INIT_FAILED) \
	OP(PREFIX, ADMIN_REJECT_TARGET_ADMIN_QP_CREATE_FAILED) \

enum nvmeibs_logout_reason {
    FOREACH_LOGOUT_REASON(NVMEIBS_LOGOUT_REASON_, GENERATE_LOGOUT_ENUM)
};

__attribute__((used)) static const char *nvmeibs_logout_reason_str[] = {
    FOREACH_LOGOUT_REASON(NVMEIBS_LOGOUT_REASON_, GENERATE_LOGOUT_STRING)
};


#endif /* NVMEIBS_TREND_TYPES_H */
