#ifndef NVMEIBC_BLOCK_H
#define NVMEIBC_BLOCK_H

#include "kr_incs.h"
#include "block/datapath_utils_generic/nvmeibc_block_dp_defs.h"

#define nvmeibc_atomic_t atomic_t		// Default is real atomics like in kernel
#define nvmeibc_atomic_sub_return atomic_sub_return
#define nvmeibc_atomic_add_return atomic_add_return
#define nvmeibc_atomic_dec_return atomic_dec_return
#define nvmeibc_atomic_add atomic_add
#define nvmeibc_atomic_sub atomic_sub
#define nvmeibc_atomic_inc atomic_inc
#define nvmeibc_atomic_read atomic_read
#define nvmeibc_atomic_dec atomic_dec
#define nvmeibc_atomic_set atomic_set

#ifdef DP_LIB
	#define BLKCMP_SO_COMPLETION_PRESERVE_STACK	1		/* Syncs run in fiber mode (single stack) instead of advancing state machines via completions */
	#define BLKCMP_IO_COMPLETION_PRESERVE_STACK	(1 && BLKCMP_SO_COMPLETION_PRESERVE_STACK)	/* Same but for IO */
	#define BLKCMP_RC_COMPLETION_PRESERVE_STACK	(1 && BLKCMP_SO_COMPLETION_PRESERVE_STACK)	/* Same but for Recoveries */
#endif
#if !defined(NVMESH_TRACE_NAMESPACE)
	#include "nvmeibc_trace.h"
#endif
#include "nvmeibc_disk.h"								// Physical disk, A few block devices can point to a single physical disk
#include "kr_undef.h"
#include "nvmeibc_mcs_stub.h"
#include "nvmeib_public.h"
#include "nvmeibc_block_transport_api.h"

#ifndef KERNEL_SECTOR_SHIFT
	#define KERNEL_SECTOR_SHIFT	9
#endif
#define KERNEL_SECTOR_TO_SECTOR_SHIFT (NVMEIBC_SECTOR_SHIFT-KERNEL_SECTOR_SHIFT)		// Conversion of NVMEIBC block to kernel 512[b] sectors
#define KERNEL_SECTORS_IN_NVMEIBC_SECTOR (1 << KERNEL_SECTOR_TO_SECTOR_SHIFT)			// Number of kernel sectors in one nvmeibc block (sector)

typedef u32 vlba_blkset_t;					// Vlba in units of blocksets
#define ILLEGAL_VLBA_BLOCKSET ((vlba_blkset_t)~0ULL)
#define TODO(ticket_number, action_item)

#ifdef DEBUG_TOPO_CNTRS
struct debug_topo {
	struct nvmeibc_block_command *cmds;
	struct nvmeibc_block_command *new_cmds;
	struct list_head list;
	bool is_operation;
};
#endif

/* Transport layer should use this function to test if unsent cmd should be auto-failed locally due to time out */
bool nvmeibc_disk_io_command_is_timed_out(const struct nvmeibc_disk_io_command *, ulong now_jiff);

/********************************* API ***************************************/
/* The API below is given for a higher level software to control the
 * volume (create/destroy/disconnect a physical disk/querry status/ etc).
 * There is no API for IO transfers. The read/write/trim actions are done by
 * the OS and your file system. When you write a file to the volume, OS issues
 * IO requests to the block device using internal API
 * (Good documentation is here: https://static.lwn.net/images/pdf/LDD3/ch16.pdf)
*/
struct nvmeibc_block_device;
struct nvmeibc_volume;
struct nvmeibc_volume_conf;

/**
 * @brief Call first to initialize the module (create the block device/volume).
 * @param cdisks_num number of physical disks associated with the volume
 * @param cdisks array of physical disks (each possibly contributes zero or more
 * 	ranges of addresses to the volume)
 * @param volume - the volume which this block device will represent. Fields:
 * volume->dev_name name - Example: "MyBackUp". Becomes the name of the blockdev
 * volume->version - generated by the configuration manager for volume.
 * volume->block_dev - here our block device will be allocated and stored.
 *	It is later accessed with the rest of the API methods
 * volume->uuid - unique id of the volume (no longer than 63 characters).
 * 	Becomes id of the block device
 * @return 0 on success or negative error code.
 */
int nvmeibc_block_init(struct nvmeibc_volume_conf *conf,
					   struct nvmeibc_volume *volume);
/**
 * @brief Call after nvmeibc_block_init() to update volume
 *  	  configuration (relocated segments, updated version, ...)
 * @param Almost identical to init. 'volume->block_dev' already exists.
 * 	volume->version increses
 * @return 0 on success or negative error code.
 */
int nvmeibc_block_reconf(struct nvmeibc_volume_conf *conf,
						 struct nvmeibc_volume *volume);

/**
 * @brief wait until all IO's in air and topo users complete.
 *  	  Topologies are not needed anymore
 */
int nvmeibc_wait_for_io_drain(struct nvmeibc_block_device 	*dev,
							  void (*on_finish_cb)(void *ctx), void *ctx);

/**
 * @brief  remove the block device from the system. No more operations
 * will be sent to the given device. DOES NOT free dev.
 * In unsafe detach: continue detach after IO's have all been drained
 * @param dev pointer to block device created by nvmeibc_block_init()
 */
void nvmeibc_del_blkdev(struct nvmeibc_block_device *dev);

/**
 * @brief Called when we are totally done with uuid_to_detach =
 * 0 which means all. Must call after nvmeibc_del_blkdev().
 * @param dev pointer to block device. DOES free dev
 */
int nvmeibc_block_exit(struct nvmeibc_block_device *dev);

/**
 * @brief Used by QA unitests to tune parameters of block device
 *        Will write entries to log with QA_BLOCK_PREFIX string
 * @param dev - block device affected. Pass NULL to affect all devices
 * @param cmd - string command, refer to external documentation
 */
struct nvmeibc_cinst_params_blk;
int nvmeibc_block_qa_config(const struct nvmeibc_cinst_params_blk *p,
							struct nvmeibc_block_device *dev, const char* cmd);
#define QA_BLOCK_PREFIX   "ioctl: "
#define DMESG_PREFIX(id)      "volume " id
#define MAIN_IOCTL_PREFIX "main-ioctl"
#define DMESG_PD_PREFIX(id)   "diskp " id
#define DMESG_MOD_PREFIX  "module"
#define SUB_VOL_CMD       "sub_vol_"

/**
 * @brief Try detach bdev,
 * @param dev pointer to block device created by nvmeibc_block_init()
 * @param how instruction how to detach.
 * @return 0 if unused (detach started), negative value otherwise
 */
struct nvmeibc_vol_detach_cmd;
int nvmeibc_block_try_detach(struct nvmeibc_block_device *dev,
							 const struct nvmeibc_vol_detach_cmd how);

/**
 * @brief Get block device io status
 * @author doronl (4/26/2017)
 * @param dev pointer to block device created by nvmeibc_block_init()
 * @return bool is the device io blocked
 * The function will try to minimize the device io permissions jittering.
 * For example a short temporal disconnect and immidiate reconnect, with high probability,
 * will not be reported to the user.
 */
enum_io_perm nvmeibc_get_io_perm_for_reporting(struct nvmeibc_block_device *dev);

bool nvmeibc_block_is_during_attach_stabilization_period(struct nvmeibc_block_device *dev);

/**
 * @brief Get block device reservation information
 * @author doronl (3/5/2020)
 * @param dev pointer to block device created by nvmeibc_block_init()
 * @return vat (nvmeibc_volume_attach_t)
 */
const struct nvmeibc_volume_attach_t * nvmeibc_block_get_res_vat(const struct nvmeibc_block_device *dev);

/**
 * @brief Get the logical block size from the attachment parameters in the device
 * @param dev pointer to block device created by nvmeibc_block_init()
 * @return true iff 'is_512B_IO_allowed' was set in the attach parameters
 */
bool nvmeibc_block_is_kernel_sector_io_allowed(const struct nvmeibc_block_device *dev);

struct nvmeibc_os_api *nvmeibc_block_get_os_api(struct nvmeibc_block_device *dev);

/**
 * @brief Return I/O completion. A callback which lower level
 *        uses to notify the block device that remote IO
 *        operation completed.
 * @param completion structure of the command (with status). comp->comp_code:
 * 		0 - success, Negative errors: Daniel Todo specify which...
 */
void nvmeibc_block_completion(struct nvmeibc_d_iocmd_comp *comp);
/**
 * @brief Same as above but for gen_cmds (non IO commands).
 */
void nvmeibc_block_comp_gencmd(struct nvmeibc_d_iocmd_comp *comp);

const struct nvmeibc_block_device *get_bdev_of_bio(const struct bio *);

/**
 * @brief Free journal entries gen_cmd completion
 */
void nvmeibc_disk_free_jrnl_ents_info_comp(struct nvmeibc_disk_gen_cmd* gen_cmd, int comp_code);

/**
 * @brief Runs every X seconds and reports the devices status to the managment.
 *        Also, if volume is running too much time in "double dgrd write" topology,
 *        will change the topology to "read only"
 * @param unused
 */
int nvmeibc_block_watchdog_run_once(void *param_unused);

bool nvmeibc_block_dev_is_shadow(struct nvmeibc_block_device *dev);

/**
 * @brief Requests to stop the access to disk (due to failiure,
 *        network disconnection) and restart access (network
 *        reconnect, disk restart, etc)
 * @param dev pointer to block device created by nvmeibc_block_init()
 * @param disk pointer to the disk to stop or resume
 */
int nvmeibc_block_pause(struct nvmeibc_block_device *dev, struct nvmeibc_disk *disk);
int nvmeibc_block_cont( struct nvmeibc_block_device *dev, struct nvmeibc_disk *disk);

/******************************* Global init **********************************/
/* Initialization of the block layer and destructor */
struct nvmeibc_cinst_params_blk;
int  t_blok_clnt_globals_init(   const struct nvmeibc_cinst_params_blk *blk);
void t_blok_clnt_globals_destroy(const struct nvmeibc_cinst_params_blk *blk);
int  t_blok_clnt_globals_params_update(struct nvmeibc_cinst_params_blk *p, const char *ioctl);	// Respond to ioctl which updates params
void nvmeibc_block_dp_fill_cinst_params_from_module_params(struct nvmeibc_cinst_params_blk *p);
/**************************** Debugging Aids *********************************/
/* Print Generic information of all block devices */
int nvmeibc_block_layer_all_tostring(char *buf, int buf_len);
void nvmeibc_trs_hash_verify_empty_unsafe(void);


#define for_each_allocated_cpu(i)	for (i=0; i<MAX_NUM_ACTIVE_CPUS; i++)
extern int MAX_NUM_ACTIVE_CPUS;

u32 nvmeibc_block_bcmd_o_dbg_id(struct nvmeibc_disk_io_command *c);
void nvmeibc_block_device_disk_stats_remove(struct nvmeibc_block_device *dev);

/********** Read Modify Write Flow map translations **************************/
#define __extract_rmw_first_block_map(map) (map & ((1ULL << KERNEL_SECTORS_IN_NVMEIBC_SECTOR) - 1))
#define __extract_rmw_last_block_map( map) (map >> KERNEL_SECTORS_IN_NVMEIBC_SECTOR)
void __copy_sub_block_by_map(unsigned char *dst, unsigned char *src, const ulong map);

void nvmeibc_block_clean_debug_counters(struct nvmeibc_block_device *dev, bool io_tot, bool io_worst, bool recov, bool flow, bool profiler);

u64 nvmeibc_block_get_ro_header_sectors(struct nvmeibc_volume_conf *conf);

void nvmeibc_block_trace_stats(const struct nvmeibc_block_device *dev, bool diff_only);

ssize_t nvmeibc_block_cpu_masks_to_json(const struct nvmeibc_cinst_params_blk *p, char *buf, size_t len);
int nvmeibc_block_get_cpu_masks(const struct nvmeibc_block_device *dev, struct nvmeib_cpu_mask_info *mask_infos, int max_masks);

void nvmeibc_syncs_stats_tojson(struct jdr *jdr);

#endif
