#ifndef NVMEIBC_TREND_TYPES_H
#define NVMEIBC_TREND_TYPES_H

#include "nvmeibs_trend_types.h"	

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

#define FOREACH_RELEASE_REASON(OP) \
		OP(NVMEIBC_DISK_RELEASE_UNKNOWN)   \
		OP(NVMEIBC_DISK_RELEASE_OK)   \
		OP(NVMEIBC_DISK_RELEASE_NVME_SC_POWER_LOSS)   \
		OP(NVMEIBC_DISK_RELEASE_REDISCOVER_CALLED)   \
		OP(NVMEIBC_DISK_RELEASE_REM_DRV_ERR)   \
		OP(NVMEIBC_DISK_RELEASE_IOCH_DRAINED_EVENT)   \
		OP(NVMEIBC_DISK_RELEASE_DISK_REMOVE)   \
		OP(NVMEIBC_DISK_RELEASE_TOMA_SUBSCRIBE_FAILURE)   \
		OP(NVMEIBC_DISK_RELEASE_LOCK_CHAN_DISCONNECT) \
		OP(NVMEIBC_DISK_RELEASE_LOCK_CHAN_WD_EVENT) \
		OP(NVMEIBC_DISK_RELEASE_ADMIN_CHAN_DISCONNECT)   \
		OP(NVMEIBC_DISK_RELEASE_ADMIN_CHAN_KA_FAILED)   \
		OP(NVMEIBC_DISK_RELEASE_JOURNAL_ENTRY_ERASE_FAILURE)   \
		OP(NVMEIBC_DISK_RELEASE_DISK_PAUSED)   \
		OP(NVMEIBC_DISK_RELEASE_STARTED_OFFLINE) \
		OP(NVMEIBC_DISK_RELEASE_DISK_ABANDONED_JENTRY)   \
		OP(NVMEIBC_DISK_RELEASE_GET_REQUESTED_BINJE) \
		OP(NVMEIBC_DISK_RELEASE_CONFIG_UPDATE_LOCAL_SRV) \
		OP(NVMEIBC_DISK_RELEASE_CONFIG_UPDATE_NIC_REMOVE) \
		OP(NVMEIBC_DISK_RELEASE_CONFIG_UPDATE_PORT_REMOVE) \
		OP(NVMEIBC_DISK_RELEASE_CONFIG_UPDATE_PORT_UPDATE) \
		OP(NVMEIBC_DISK_RELEASE_CONFIG_UPDATE_COMPLETE) \
		OP(NVMEIBC_DISK_RELEASE_LOCAL_IO_FAILED) \
		OP(NVMEIBC_DISK_RELEASE_RETURN_RCOOKIE) \
		OP(NVMEIBC_DISK_RELEASE_COMMON_PREFIX_PRIORITY_NEW) \
		OP(NVMEIBC_DISK_RELEASE_COREMASK_LOCK_CHAN_EXHAUSTED) \

enum nvmeibc_disk_release_reason {
    FOREACH_RELEASE_REASON(GENERATE_ENUM)
	/* we also auto create release reasons from logout reasons */
	NVMEIBC_DISK_RELEASE_SRV_LOGOUT_START_MARKER,
	FOREACH_LOGOUT_REASON(NVMEIBC_DISK_RELEASE_SRV_LOGOUT_, GENERATE_LOGOUT_ENUM)
};

#define LOGOUT_REASON_TO_RELEASE_REASON(r) r + NVMEIBC_DISK_RELEASE_SRV_LOGOUT_START_MARKER + 1

__attribute__((used)) static const char *nvmeibc_disk_release_reason_str[] = {
    FOREACH_RELEASE_REASON(GENERATE_STRING)
	"NVMEIBC_DISK_RELEASE_SRV_LOGOUT_START_MARKER",
	FOREACH_LOGOUT_REASON(NVMEIBC_DISK_RELEASE_SRV_LOGOUT_, GENERATE_LOGOUT_STRING)
};

#define FOREACH_DISK_DISCOVER_STATUS(OP) \
		OP(NVMEIBC_DISK_DISCOVER_UNKNOWN)   \
		OP(NVMEIBC_DISK_DISCOVER_OK)   \
		OP(NVMEIBC_DISK_DISCOVER_NO_LOCAL_PORTS) \
		OP(NVMEIBC_DISK_DISCOVER_NO_LOCAL_NICS)   \
		OP(NVMEIBC_DISK_DISCOVER_NO_ARNICS)   \
		OP(NVMEIBC_DISK_DISCOVER_NO_ARNICS_ACCESS)   \
		OP(NVMEIBC_DISK_DISCOVER_ADMIN_CH_CREATE_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_DBITS_MEM_ALLOCATION_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_ARNIC_NO_PORTS)   \
		OP(NVMEIBC_DISK_DISCOVER_ARNIC_NO_PATHS) 		\
		OP(NVMEIBC_DISK_DISCOVER_IO_RESOURCES_READ_FAIL)   \
		OP(NVMEIBC_DISK_DISCOVER_GEN_WQ_ALLOCATION_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_LOCAL_REGISTER_SRV_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_INLINE_MD_UNSUPPORTED)   \
		OP(NVMEIBC_DISK_DISCOVER_LOCAL_LOCK_CH_CONNECT_FAILED) \
		OP(NVMEIBC_DISK_DISCOVER_LOCAL_LOCK_CH_ACTV_TBL_ALLOC_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_ACTIVE_LOCKS_TABLE_MAP_WRONG_DEV)   \
		OP(NVMEIBC_DISK_DISCOVER_LOCAL_LOCK_CH_STRAT_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_LOCAL_JOURNAL_GET_FAILED)		\
		OP(NVMEIBC_DISK_DISCOVER_JAM_ADD_FAILED) \
		OP(NVMEIBC_DISK_DISCOVER_TOMA_NO_ADMIN_CH)   \
		OP(NVMEIBC_DISK_DISCOVER_TOMA_DEV_CREATION_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_TOMA_REREG_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_ACCESS_RIONICS_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_NO_RIONICS)   \
		OP(NVMEIBC_DISK_DISCOVER_LOCAL_LOCK_CH_BUILD_SEGMENTS_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_PARSE_LOCK_MEM_MSG_FAILED) \
		OP(NVMEIBC_DISK_DISCOVER_ACCESS_MAP_CREATE_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_REMOTE_JOURNAL_GET_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_REQUEST_RDDA_RESOUCES_FAILED)   \
		OP(NVMEIBC_DISK_DISCOVER_NET_ALLOCATION_FAILURE) \
		OP(NVMEIBC_DISK_DISCOVER_MEM_ALLOCATION_FAILURE) \
		OP(NVMEIBC_DISK_DISCOVER_LOCK_DEV_NOT_RECHABLE) \
		OP(NVMEIBC_DISK_DISCOVER_DMA_MAP_FAILED) \
		OP(NVMEIBC_DISK_DISCOVER_TEST_ATOMICS_FAILED) \
		OP(NVMEIBC_DISK_DISCOVER_LOCK_CHANNEL_CONNECTION_FAILED) \
		OP(NVMEIBC_DISK_DISCOVER_IOCH_CREATE_FAILED) \
		OP(NVMEIBC_DISK_DISCOVER_NRCH_CREATE_FAILED) \
		OP(NVMEIBC_DISK_DISCOVER_INVALID_TRANSPORT_TYPE) \
		OP(NVMEIBC_DISK_DISCOVER_PAUSE_AT_FIRST_DISCOVER)	\

enum nvmeibc_disk_discover_status {
    FOREACH_DISK_DISCOVER_STATUS(GENERATE_ENUM)
};

__attribute__((used)) static const char *nvmeibc_disk_discover_status_str[] = {
    FOREACH_DISK_DISCOVER_STATUS(GENERATE_STRING)
};

#define FOREACH_ARNIC_DISCOVER_STATUS(OP) \
		OP(NVMEIBC_ARNIC_DISCOVER_UNKNOWN)   \
		OP(NVMEIBC_ARNIC_DISCOVER_OK)   \
		OP(NVMEIBC_ARNIC_DISCOVER_NOT_SKIPPED)   \
		OP(NVMEIBC_ARNIC_DISCOVER_SKIPPED)		  \
		OP(NVMEIBC_ARNIC_DISCOVER_SKIPPED_DIFF_CFG_NODE)   \
		OP(NVMEIBC_ARNIC_DISCOVER_ADMIN_CHAN_CREATION_FAILED)   \
		OP(NVMEIBC_ARNIC_DISCOVER_NO_PATH_FROM_LOCAL)   \
		OP(NVMEIBC_ARNIC_DISCOVER_TARGET_VERSION_CHANGED) \
		OP(NVMEIBC_ARNIC_DISCOVER_LOGIN_FAILED)   \
		OP(NVMEIBC_ARNIC_DISCOVER_LOGIN_REMOTE_TOMA_DOWN)   \
		OP(NVMEIBC_ARNIC_DISCOVER_SHARE_CONFIG_FAILED)   \
		OP(NVMEIBC_ARNIC_DISCOVER_READ_IO_FAILED)   \
		OP(NVMEIBC_ARNIC_DISCOVER_READ_IO_NO_DISKS)   \
		OP(NVMEIBC_ARNIC_DISCOVER_ACCESS_IORNICS_FAILED)   \
		OP(NVMEIBC_ARNIC_DISCOVER_ACCESS_MAP_CREATE_FAILED)   \
		OP(NVMEIBC_ARNIC_DISCOVER_JOURNAL_RANGE_GET_FAILED) \
		OP(NVMEIBC_ARNIC_DISCOVER_DISK_RDDA_RESOURCES_GET_FAILED) \
		OP(NVMEIBC_ARNIC_DISCOVER_TOMA_CREATE_FAILED) \
		OP(NVMEIBC_ARNIC_DISCOVER_TOMA_REREG_FAILED) \
		OP(NVMEIBC_ARNIC_DISCOVER_START_IOCH_WORK_FAILED) \
		OP(NVMEIBC_ARNIC_DISCOVER_ENCODE_CONTAINER_FAIL) \
		OP(NVMEIBC_ARNIC_DISCOVER_ACCESS_MAP_GET_RDMA_FAILED) \
		OP(NVMEIBC_ARNIC_DISCOVER_ACCESS_MAP_PARSING_FAILED) \
		OP(NVMEIBC_ARNIC_DISCOVER_NO_FREE_MESSAGES) \
		OP(NVMEIBC_ARNIC_DISCOVER_LOCK_MEM_MSG_FAILED) \
		OP(NVMEIBC_ARNIC_DISCOVER_IB_IO_CHANNEL_CREATE_FAILED) \
		OP(NVMEIBC_ARNIC_DISCOVER_NRCH_CREATE_FAILED) \


enum nvmeibc_arnic_discover_status {
    FOREACH_ARNIC_DISCOVER_STATUS(GENERATE_ENUM)
};

__attribute__((used)) static const char *nvmeibc_arnic_discover_status_str[] = {
    FOREACH_ARNIC_DISCOVER_STATUS(GENERATE_STRING)
};
#endif
