FROM rockylinux:8

WORKDIR /nvmesh

RUN yum groupinstall -y "Development Tools"
RUN yum install -y rsync rdma-core rdma-core-devel kernel kernel-devel kernel-headers
RUN yum install -y which elfutils-libelf-devel
RUN yum install -y systemd-devel
RUN yum install -y rpmdevtools
RUN yum install -y python2

ADD confluent8.repo /etc/yum.repos.d

RUN yum install -y librdkafka1-2.1.1 librdkafka-devel-2.1.1

RUN yum install -y wget
RUN wget https://www.mellanox.com/downloads/DOCA/DOCA_v3.2.0/host/doca-host-3.2.0-125000_25.10_rhel8.x86_64.rpm
RUN rpm -i doca-host-3.2.0-125000_25.10_rhel8.x86_64.rpm
RUN dnf clean all
RUN dnf install epel-release -y
RUN dnf -y install dkms
RUN dnf -y install doca-ofed
RUN dnf -y install mlnx-ofa_kernel-source
RUN dkms build -m mlnx-ofa_kernel -v 25.10 -k $(basename $(rpm -ql kernel-devel | head -1))


