# Use Ubuntu 24.04 (Noble Numbat) as the base image
FROM ubuntu:24.04

ENV DIRPATH /nvmesh
WORKDIR $DIRPATH

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Fix segfault on libc-bin
RUN rm /var/lib/dpkg/info/libc-bin.*
RUN apt-get clean
RUN apt-get update
RUN apt-get install libc-bin

# Update apt package list and install build essentials and other useful tools
RUN apt update && apt install -y \
    build-essential \
    git \
    curl \
    wget \
    vim \
    rsync

RUN apt install -y \
    rdma-core \
    librdmacm1 \
    librdmacm-dev \
    rdmacm-utils

RUN apt install -y \
     libelf1 \
     elfutils \
     libudev1 \
     libudev-dev \
     alien

RUN apt install -y \
	linux-image-unsigned-6.11.0-1016-nvidia-64k \
	linux-headers-6.11.0-1016-nvidia-64k

RUN apt install -y \
    librdkafka1 \
    librdkafka-dev

# Add python3.10 for poetry compilation
# Use deadsnakes PPA to get python3.10
RUN apt install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings

RUN curl -fsSL https://keyserver.ubuntu.com/pks/lookup?op=get\&search=0x6A755776 \
  | gpg --dearmor \
  | tee /etc/apt/keyrings/deadsnakes.gpg > /dev/null

RUN echo "deb [signed-by=/etc/apt/keyrings/deadsnakes.gpg] \
https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu noble main" \
> /etc/apt/sources.list.d/deadsnakes.list

RUN apt update
RUN apt install -y \
  python3.10 \
  python3.10-venv \
  python3.10-distutils \
  python3.10-dev

RUN curl -sSL https://install.python-poetry.org | python3.10 -

# Set the default command for the container
#CMD ["/bin/bash"]

