# Use Ubuntu 22.04 (Jammy Jellyfish) as the base image
FROM ubuntu:22.04

ENV DIRPATH /nvmesh
WORKDIR $DIRPATH

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Update apt package list and install build essentials and other useful tools
RUN apt update && apt install -y \
    build-essential \
    git \
    curl \
    wget \
    vim \
    rsync \
    rdma-core \
    librdmacm1 \
    librdmacm-dev \
    rdmacm-utils \
    libelf1 \
    elfutils \
    libudev1 \
    libudev-dev \
    alien \
    linux-image-5.15.0-164-generic \
    linux-headers-5.15.0-164-generic \
    librdkafka1 \
    librdkafka-dev \
    python3

RUN apt install -y \
  python3-venv \
  python3-distutils \
  python3-dev

RUN curl -sSL https://install.python-poetry.org | python3.10 -


# Set the default command for the container
#CMD ["/bin/bash"]

