FROM rockylinux/rockylinux:10

WORKDIR /nvmesh

RUN dnf groupinstall -y "Development Tools"
RUN dnf install -y rsync kernel kernel-devel kernel-headers
RUN dnf install -y which elfutils-libelf-devel
RUN dnf install -y systemd-devel
RUN dnf install -y rpmdevtools
RUN dnf install -y python3

RUN dnf install -y dnf-plugin-config-manager
RUN dnf config-manager --set-enabled crb
RUN dnf install -y librdkafka librdkafka-devel

RUN dnf install -y wget
RUN wget https://www.mellanox.com/downloads/DOCA/DOCA_v3.2.2/host/doca-host-3.2.2-035000_25.10_rhel10.x86_64.rpm
RUN rpm -i doca-host-3.2.2-035000_25.10_rhel10.x86_64.rpm
RUN dnf clean all
RUN dnf install epel-release -y
RUN dnf -y install dkms
RUN dnf -y install doca-ofed
RUN dnf -y install mlnx-ofa_kernel-source
RUN dkms build -m mlnx-ofa_kernel -v $(ls /var/lib/dkms/mlnx-ofa_kernel | head -1) -k $(basename $(rpm -ql kernel-devel | head -1))


