#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

echo "NVMESH.KUNIT.BEGIN"
#running our tests
insmod /opt/nvmesh/nvmeibc_bio.ko

echo "NVMESH.KUNIT.END"
poweroff -nf # n - do not sync; f - force (don't go through init)
