/*
* SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
* SPDX-License-Identifier: GPL-2.0-only OR Apache-2.0
*/

NVMEIB_EVENT(VOL_STATUS)
NVMEIB_EVENT(DETACH_FINISHED)
NVMEIB_EVENT(DETACH_RETRY)
NVMEIB_EVENT(DETACH_FAILED)
NVMEIB_EVENT(BLOCK_STATUS)
NVMEIB_EVENT(RAID_RECOV_STARTED)
NVMEIB_EVENT(RAID_RECOV_REJECTED)
NVMEIB_EVENT(RAID_RECOV_FINISHED)
NVMEIB_EVENT(IOCTL)
NVMEIB_EVENT(GET_TGT_NICS)
NVMEIB_EVENT(UPDATE_TGT)
NVMEIB_EVENT(UPDATE_TGT_NIC)
NVMEIB_EVENT(NEW_NIC)
NVMEIB_EVENT(DEL_NIC)
NVMEIB_EVENT(REMOVE_TARGET)
NVMEIB_EVENT(MODULE_STATE_CHANGE)
NVMEIB_EVENT(DISK_DISCONNECT_VOLUME)
NVMEIB_EVENT(DISK_IO_CONT)
NVMEIB_EVENT(TOPOLOGY_PERMISSION_CHANGE)
