#include <stdio.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <dirent.h>

#include "nvmeibt_debug.h"
#include "nvmeibt_common.h"
#include "nvmeibt_bm.h"
#include "nvmeibt_raft.h"
#include "nvmeibt_disk.h"
#include "nvmeibt_topology.h"
#include "nvmeibt_global.h"
#include "nvmeibt_dumper.h"
#include "nvmeibt_toma.h"

/*
 * TOMA record-replay is a tool for QA to compare the output of different
 * versions/releases given similar input data. The tool records important
 * TOMA events during runtime, and can replay them as input to a separate
 * run possibly of a different version. Recording live systems is useful
 * to generate a collection of real world scenarios for testing.
 *
 * Recording occurs only on the RAFT leader. The recorder collects 4 types
 * of events:
 *
 * . "mgmt": changes to the global configuration reported by the management
 * . "raft": dump of raft persistency (also included latest topology)
 * . "topo": updates to global topology after the leader recalculates it
 * . "peer": updates to local topologies reported by the peer nodes
 * . "disk": disk removals reported by the peer nodes
 *
 * The recorder keeps tracks of events using the raft term, topology
 * version, and event counter (raft#/topo#/event#, respectively).
 *
 * . Recording is logically divided into sessions, defined by the raft#.
 * . Sessions are further divided into sequences, defined by the topo#.
 * . Within a sequence, event# is incremented for each event.
 *
 * Sessions are stored in separate files, and events are stored in order
 * in a single file.
 * The first event in each session is "mgmt" (initial management config),
 * and the second event in each session is "raft" (the raft persistency,
 * including initial global topology).
 * Within each session, the first event in the second sequence onward is
 * "topo" (new calculated topology), and the second event is "raft".
 *
 * A typical example of one session:
 *                                          ratf#     topology  evnt type
 *                                        ---------- ---------- ---- ----
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:31 0x0000000b_0x0a00000a_0000_mgmt
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:31 0x0000000b_0x0a00000a_0001_raft
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:31 0x0000000b_0x0a00000a_0002_peer
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:31 0x0000000b_0x0a00000a_0003_peer
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:32 0x0000000b_0x0b00000b_0000_topo
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:32 0x0000000b_0x0b00000b_0001_raft
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:32 0x0000000b_0x0b00000b_0002_peer
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:32 0x0000000b_0x0b00000b_0003_peer
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:32 0x0000000b_0x0b00000d_0000_topo
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:33 0x0000000b_0x0b00000c_0001_raft
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:33 0x0000000b_0x0b00000c_0002_peer
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:33 0x0000000b_0x0b00000c_0003_peer
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:33 0x0000000b_0x0b00000c_0004_disk
 *   TOMA_TOPO_RECORD 2019-07-28-11:17:33 0x0000000b_0x0b00000d_0000_topo
 *   ...
 *
 */

/*
 * recording default is:
 *   . OFF for "release" (use trace.config to enable)
 *   . ON for "delease", "debug"
 */
#ifdef TOMA_DEBUG
#define DUMPER_ENABLE_DFLT 1
#else
#define DUMPER_ENABLE_DFLT 0
#endif

static BOOL dumper_enabled = DUMPER_ENABLE_DFLT;  /* recording on/off */

static BOOL dumper_did_mgmt = 0;  /* dumped mgmt config at least once? */
static BOOL dumper_did_raft = 0;  /* dumped raft persistency at least once? */
static char dumper_last_type[16]; /* type of last event dumped (string) */

#define DUMPER_ARCHIVE_CNT  100  /* number of log files to trigger archiving */
#define DUMPER_ARCHIVE_OLD  10   /* number of old archives to delete if needed */
#define DUMPER_ARCHIVE_SIZE 100  /* [MB] max storage to be used for archiving */
#define DUMPER_SESSION_SIZE 1    /* [MB] threshold size of single log file */

/*
 * The dumper events are generated by the main TOMA thread, but are written
 * to storage using a separate thread (dumper_wq) to avoid undesired hiccups
 * to TOMA.
 * Thus, all filesystem related operations: mkdir, open/close files, write
 * to files, and test for zip/rotate logs - are done by dumper_wq callbacks.
 */
struct dumper_wq_entry {
	struct nvmeibt_wq_entry wq_entry;
	struct nvmeibt_Str		*csv_ctx;
};

/* These two only manipulated by dumper_wq thread */
static BOOL dumper_inited = 0;  /* dumper ready (reset every new session) */
static int dumper_fd = -1;		/* file descriptor of current log file */

struct nvmeibt_wq *dumper_wq;

/*
 * dumper_count_logs(): count number of existing recording logs
 * (called by dumper_wq thread because involves filesystem operation)
 */
static int dumper_count_logs(const char *prefix, const char *suffix)
{
	int count = 0;
	DIR *dir;
	struct dirent *d;

	int prefix_len = prefix ? strlen(prefix) : 0;
	int suffix_len = suffix ? strlen(suffix) : 0;
	int d_len;

	NFIN;

	dir = opendir(TOMA_DUMPER_DIR);
	if (dir == NULL) {
		N_Wf(warn_dumper_dumper_count_logs, "Failed to open " TOMA_DUMPER_DIR "(@AUTO_ERRNO)");
		goto out;
	}

	while ((d = readdir(dir)) != NULL) {
		d_len = strlen(d->d_name);
		if (prefix) {
			if (strncmp(prefix, d->d_name, prefix_len) != 0)
				continue;
		}
		if (suffix) {
			if (d_len < suffix_len)
				continue;
			else if (strcmp(suffix, &d->d_name[d_len - suffix_len]) != 0)
				continue;
		}
		count++;
	}
	closedir(dir);

out:
	NFOUT;
	return count;
}

/*
 * dumper_maybe_archive_logs(); archive existing (older) logs if too many.
 *
 * Occasionally collect and compress them to reduce storage overhead. The
 * trigger when the number of logs exceeds DUMPER_ARCHIVE_CNT. If total space
 * used by logs exceeds DUMPER_ARCHIVE_SIZE, then delete some oldest logs.
 * Archiving is done by a separate process fork) to avoid blocking TOMA.
 */
static void dumper_maybe_archive_logs(void)
{
	static int count = -1;
	char command[512];
	char timestamp[64];
	struct tm *tm;
	time_t t;

	NFIN;

	/* first call after TOMA starts: initialize with count of existing logs */
	if (count < 0)
		count = dumper_count_logs("topo.", ".log");

	if (count++ < DUMPER_ARCHIVE_CNT)
		goto out;

	t = time(NULL);
	tm = localtime(&t);
	strftime(timestamp, sizeof(timestamp),
			 TOMA_DUMPER_DIR "/topo-tar.%Y-%m-%H.%M.%S.tgz", tm);

	sprintf(command,
			/* go to logs dir */
			"cd " TOMA_DUMPER_DIR "; "
			/* archive last N logs */
			"list=$(ls -tr topo.*.log | head -%d); "
			"file=%s; "
			"echo \"dumper: archiver: creating $file\"; "
			"tar -czf $file $list && rm $list; "
			/* delete some old logs if too big */
			"size=$(du -sm . | cut -f 1); "
			"list=$(ls -tr topo-tar.*.tgz | head -%d); "
			"if [ -n \"$list\" -a $size -gt %d ]; then "
			"  echo \"dumper: archiver: too big ${size}MB\"; "
			"  echo \"dumper: archiver: deleting oldest...\"; "
			"  rm $list; "
			"fi; ",
			DUMPER_ARCHIVE_CNT, timestamp,
			DUMPER_ARCHIVE_SIZE, DUMPER_ARCHIVE_OLD);

	count -= DUMPER_ARCHIVE_CNT;

out:
	NFOUT;
}

/*
 * dumper_init_session(): initialize dumper state for new session;
 * (called by dumper_wq thread because involves filesystem operation)
 */
static int dumper_init_session(void)
{
	static int retries = 0;
	int ret = -1;

	NFIN;

	/* if mkdir fails, do not hit head in the wall endlessly ... */
	if (++retries >= 5) {
		nvmeibt_dumper_enable(0);
		N_Wf(warn_dumper_dumper_init_session, "failed to mkdir 5 times, disabling toma recording");
		goto out;
	}

	if (nvmeibt_recursive_mkdir(TOMA_DUMPER_DIR, 0755) < 0) {
		N_Wf(warn_1_dumper_dumper_init_session, "Failed to mkdir @PATH (@AUTO_ERRNO)", TOMA_DUMPER_DIR);
		goto out;
	}

	dumper_maybe_archive_logs();

	dumper_inited = 1;
	retries = 0;

	ret = 0;

out:
	NFOUT;
	return ret;
}

static BOOL dumper_is_needed(void)
{
	return dumper_enabled && nvmeibt_raft_is_leader();
}

/*
 * dumper_open_file(): opens a new log file for recording;
 * (called by dumper_wq thread because involves filesystem operation)
 */
static int dumper_open_file(void)
{
	static int retries = 0;

	time_t t = time(NULL);
	struct tm *tm = localtime(&t);
	char fname[128];
	int fd = -1;

	NFIN;

	/* if open fails, do not hit head in the wall endlessly ... */
	if (++retries >= 5) {
		nvmeibt_dumper_enable(0);
		N_Wf(warn_dumper_dumper_open_file, "failed to open dump file 5 times, disabling toma recording");
		goto out;
	}

	/* format dump file name (see nvmeibt_dumper.h) */
	strftime(fname, sizeof(fname),
			 TOMA_DUMPER_DIR "/" "topo.%Y-%m-%d-%H.%M.%S.log", tm);

	fd = NNVMEIBT_OPEN(trace_dumper_dumper_open_file, fname,O_RDWR | O_CREAT, 0644);
	if (fd < 0) {
		N_Wf(warn_1_dumper_dumper_open_file, "Failed to open @FNAME (@AUTO_ERRNO)", fname);
		goto out;
	}

	N_Tf(trace_1_dumper_dumper_open_file, "Logging session in file @FNAME", fname);
	retries = 0;

out:
	NFOUT;
	return fd;
}

/*
 * dumper_wq_entry_free(): free a dumper_event data.
 */
static void dumper_wq_callback_free(struct nvmeibt_wq_entry *wq_entry)
{
	struct dumper_wq_entry *de;

	de = container_of(wq_entry, struct dumper_wq_entry, wq_entry);
	NNVMEIBT_STR_FREE(trace_dumper_dumper_wq_callback_free, de->csv_ctx);
	NNVMEIBT_TOMA_FREE(trace_1_dumper_dumper_wq_callback_free, de);
}

/*
 * dumper_wq_callback_reset(): called when the recording needs to be reset
 * to close (and flush) the current log file before subsequent writes.
 */
static void dumper_wq_callback_reset(struct nvmeibt_wq_entry *wq_entry)
{
	NFIN;

	if (dumper_inited) {
		N_Tf(trace_dumper_dumper_wq_callback_reset, "Logging session ended");
		NNVMEIBT_CLOSE(trace_1_dumper_dumper_wq_callback_reset, dumper_fd);
		dumper_inited = 0;
	}

	dumper_wq_callback_free(wq_entry);
	NFOUT;
}

/*
 * dumper_wq_callback_write(): called when a recording entry needs to be
 * written to the log file; will open a new file if needed.
 */
static void dumper_wq_callback_write(struct nvmeibt_wq_entry *wq_entry)
{
	struct dumper_wq_entry	*de;
	const char 				*buf;
	size_t					len;
	int						rv = -1;

	NFIN;

	de = container_of(wq_entry, struct dumper_wq_entry, wq_entry);

	buf = nvmeibt_Str_str(de->csv_ctx);
	len = nvmeibt_Str_strlen(de->csv_ctx);

	/* initialize dumper state if not already */
	if (!dumper_inited) {
		if (dumper_init_session() < 0)
			goto out;
	}

	/* and start a new dump file if necessary */
	if (dumper_fd < 0) {
		dumper_fd = dumper_open_file();
		if (dumper_fd < 0)
			goto out;
	}

	rv = nvmeibt_write(dumper_fd, buf, len);

out:
	if (rv < 0) {
		const char *p;
		struct nvmeibt_Str *traced_buf = NNVMEIBT_STR_ALLOC(trace_dumper_dumper_wq_callback_write);
		p = buf = strchr(buf, '\n') + 1;	// find 2nd line
		p = strchr(p, '\n') + 1;			// find 3rd line
		p = strchr(p, '\n');				// find 3rd line end
		nvmeibt_Str_sprintf(traced_buf, "%.*s", (int)(p ? p - buf : 255), buf);
		N_Wf(warn_dumper_dumper_wq_callback_write, "Failed to write dumper event (@AUTO_ERRNO), header:\n@BUFFER_DUMP", nvmeibt_Str_str(traced_buf));
	}

	dumper_wq_callback_free(wq_entry);
	NFOUT;
}

/*
 * dumper_wq_entry_new(): enqueue a new dumper event in dumper_wq
 */
static void dumper_wq_entry_new(struct nvmeibt_Str *csv_ctx, BOOL is_reset)
{
	struct dumper_wq_entry *de;
	int rv;

	de = NNVMEIBT_TOMA_CALLOC(trace_dumper_dumper_wq_entry_new, 1, sizeof(*de));

	if (is_reset) {
		de->wq_entry.type = "DUMPER_RESET";
		de->wq_entry.execute = dumper_wq_callback_reset;
		de->wq_entry.free = dumper_wq_callback_free;
	} else {
		de->wq_entry.type = "DUMPER_WRITE";
		de->wq_entry.execute = dumper_wq_callback_write;
		de->wq_entry.free = dumper_wq_callback_free;
		de->csv_ctx = csv_ctx;
	}

	rv = nvmeibt_wq_addw(dumper_wq, &de->wq_entry);
	NTOMA_ASSERT(error_dumper_dumper_wq_entry_new, rv == 0, "failed to add event to dumper_wq (@AUTO_ERRNO)");
	if (rv < 0)  /* in 'release' the assert above does nothing */
		dumper_wq_callback_free(&de->wq_entry);
}

/*
 * dumper_reset_session(): reset the dumper state
 * (called when raft version changed, i.e. new leader)
 */
static void dumper_reset_session(void)
{
	NFIN;

	dumper_did_mgmt = 0;
	dumper_did_raft = 0;

	dumper_wq_entry_new(NULL, true);

	NFOUT;
}

static void dumper_put_header(
				struct nvmeibt_Str *csv_ctx,
				size_t size, int raft, int topo, int event, const char *type)
{
	char t[32];
	struct tm *tm;
	time_t ti;
	size_t cnt;

	// FIN;

	ti = time(NULL);
	tm = localtime(&ti);

	/* see format spec in nvmeibt_dumper.h */

	strftime(t, sizeof(t), "%Y-%m-%d-%T", tm);

	cnt = nvmeibt_Str_sprintf(csv_ctx, TOMA_DUMPER_HDR_FORMAT,
					t, raft, topo, event, type, size, raft, topo, event, type);

	NTOMA_ASSERT(error_dumper_dumper_put_header, cnt < 256, "snippet header too large (@CNT_SIZET >= 256)", cnt);

	// FOUT;
}

/*
 * dumper_write(): dump text buffer as a new snippet
 *
 * The raft# and topology# are taken from @cur_topo. If they haven't changed
 * from before, then event# is bumped; otherwise, event# is reset to zero.
 */
static void dumper_write(const char *type, const char *buf, size_t len)
{
	static int event_cnt = 0;
	static unsigned long long last_raft_term = 0;
	static int last_topo_ver = -1;
	static int file_size = 0;

	static BOOL do_not_recurse = 0;  /* see comment below */

	struct nvmeibt_Str *csv_ctx;
	BOOL skip_me = 0;
	unsigned long long raft_term;
	int topo_ver;

	topo_ver = (int)RAFT_COMMIT_LIFECYCLE_VAL(TOPO, leader_calculated);
	raft_term = nvmeibt_raft_get_current_term();

	/*
	 * if raft version changed - a new leader has been elected:
	 * start a new recording session (in a new file).
	 */
	if (last_raft_term != raft_term) {
		dumper_reset_session();
		N_Tf(trace_dumper_dumper_write, "Raft version changed @RAFT_TERM/@RAFT_TERM: start new session",
			raft_term, last_raft_term);
		last_raft_term = raft_term;
		last_topo_ver = -1;
		event_cnt = 0;
	}

	/*
	 * Must begin with global mgmt configuration dump first, followed
	 * by the initial raft (and topology) persistent state.
	 *
	 * Use @skip_me in case the current event is already "mgmt"/"raft" -
	 * to indicate that we already did a recursive call to dump the same
	 * event - which renders the current event redundant and therefore
	 * we skip this event.
	 *
	 * Use @do_not_recurse to indicate that we are in recursive call - to
	 * ensure that "mgmt"/"raft" are dumped first; in this case hold off
	 * and don't recurse again, lest it continue indefinitely.
	 */
	if (!dumper_did_mgmt && !do_not_recurse) {
		do_not_recurse = 1;
		last_topo_ver = topo_ver;
		nvmeibt_dumper_event_mgmt_config();
		if (strcmp(type, NVMEIBT_DUMPER_TYPE_MGMT) == 0)
			skip_me = 1;
		do_not_recurse = 0;
	}
	if (!dumper_did_raft && !do_not_recurse) {
		do_not_recurse = 1;
		nvmeibt_dumper_event_raft_persist();
		if (strcmp(type, NVMEIBT_DUMPER_TYPE_RAFT) == 0)
			skip_me = 1;
		do_not_recurse = 0;
	}

	/* if we already dumped same event (type) right above, then we're done */
	if (skip_me)
		goto out;

	/*
	 * If topo version changed - then reset the event count, and also reset
	 * the dumper_did_raft flags so that raft persistency will be re-dumped
	 * next before anything else (but after the current "toma" event).
	 * This is useful to simplify splitting of long recording session into
	 * smaller sections based on topology changes: each section will begin
	 * with a "mgmt" and then "raft" events.
	 * Note: this test must come after the test of "dumper_did_raft" above
	 * so that the rest of which will take effect upon next dumper_write().
	 */
	if (last_topo_ver != topo_ver) {
		N_Tf(trace_1_dumper_dumper_write, "Topo version changed @TOPO_VER/@LAST_TOPO_VER: reset event counter",
			topo_ver, last_topo_ver);
		if (strcmp(type, NVMEIBT_DUMPER_TYPE_TOPO) != 0)
			N_Tf(trace_2_dumper_dumper_write, "Event type @TYPE_STR with new topology @TOPO_VER (@LAST_TOPO_VER)",
				type, topo_ver, last_topo_ver);
		last_topo_ver = topo_ver;
		dumper_did_raft = 0;
		event_cnt = 0;
	}

	N_Tf(trace_3_dumper_dumper_write, "Generate dump snippet raft/topo/event/type @RAFT_TERM/@TOPO_VER/@EVENT_CNT/@TYPE_STR",
		raft_term, topo_ver, event_cnt, type);

	csv_ctx = NNVMEIBT_STR_ALLOC(trace_4_dumper_dumper_write);
	NNVMEIBT_STR_RESIZE_BUF(error_dumper_dumper_write, csv_ctx, 280);	// Noticed in one log that it was REALLOCED twice to this size.
	dumper_put_header(csv_ctx, len, raft_term, topo_ver, event_cnt, type);
	nvmeibt_Str_strncat(csv_ctx, buf, len);

	file_size += nvmeibt_Str_strlen(csv_ctx);
	event_cnt++;

	/* once added, the dumper_wq will take care of freeing the memory */
	dumper_wq_entry_new(csv_ctx, false);

	/* remember last event type; see nvmeibt_dumper_event_global_topo() */
	NTOMA_ASSERT(error_1_dumper_dumper_write, strlen(type) < 16, "event type \"@TYPE_STR\" too long", type);
	nvmeibt_strlcpy(dumper_last_type, type, sizeof(dumper_last_type));

	/* if session file grew too big - force new session going forward */

	if (file_size > DUMPER_SESSION_SIZE * 1024 * 1024) {
		if (strcmp(type, NVMEIBT_DUMPER_TYPE_TOPO) == 0) {
			N_Tf(trace_5_dumper_dumper_write, "Session grew too big ... force new sesssion");
			dumper_reset_session();
			file_size = 0;
		}
	}

out:
	; /* appease compiler */
}

static void dumper_write_buf(struct nvmeibt_Buf *buf,
							 const char *type)
{
	NFIN;

	if (buf->buf_len == 0) {
		N_Tf(t8sdlq2, "Write dump type \"@TYPE_STR\" with zero length", type);
		goto out;
	}

	dumper_write(type, buf->data_buf, buf->buf_len);

out:
	NFOUT;
}

/*
 * nvmeibt_dumper_apply_mgmt_config(): dump global configuration that
 * comes from the management server.
 */
void nvmeibt_dumper_event_mgmt_config(void)
{
	struct nvmeibt_Str *csv_ctx;
	struct mm_mgmt_conf *conf;
	struct nvmeibt_Buf buf;
	struct nvmeibt_Buf		wire_config;

	NFIN;
	if (!dumper_is_needed())
		goto out;

	csv_ctx = NNVMEIBT_STR_ALLOC(trace_dumper_event_mgmt_config_1);

	wire_config.buf_len = nvmeibt_raft_get_data_from_persist_and_wire_buf_by_tlv_type(nvmeibt_raft_get_my_raft()->follower_to_commit_persist_and_wire_buf_full,
																					  TLV_TYPE_TOPO_CONFIG_FULL, (char **)&(wire_config.data_buf));
	if (wire_config.buf_len == 0) {
		goto out;
	}
	conf = mm_wire_buf_to_mm_mgmt_conf(wire_config.data_buf, 0, NULL);
	if (conf) {
		NNVMEIBT_STR_RESIZE_BUF(trace_dumper_event_mgmt_config_2, csv_ctx, 8192);
		mm_print_conf(conf, (nvmeibt_status_printf_fn_type)&nvmeibt_Str_sprintf, csv_ctx);
		mm_conf_free_tree(conf);
	}
	else {
		nvmeibt_Str_sprintf(csv_ctx, "ERROR: bad packed configuration\n");
	}
	buf.data_buf = (void *)(nvmeibt_Str_str(csv_ctx));
	buf.buf_len = nvmeibt_Str_strlen(csv_ctx);
	dumper_write_buf(&buf, NVMEIBT_DUMPER_TYPE_MGMT);
	NNVMEIBT_STR_FREE(trace_dumper_event_mgmt_config_3, csv_ctx);
	dumper_did_mgmt = 1;  /* at least initial global config dumped */

out:
	NFOUT;
}

/*
 * nvmeibt_dumper_raft_persist(): dump raft (and topo) persistency
 */
void nvmeibt_dumper_event_raft_persist(void)
{
	struct nvmeibt_Buf buf;

	NFIN;
	if (!dumper_is_needed())
		goto out;

	nvmeibt_raft_fill_persistence_buf_for_system_disk(&buf);

	dumper_write_buf(&buf, NVMEIBT_DUMPER_TYPE_RAFT);
	dumper_did_raft = 1;  /* at least initial global topology dumped */
	NNVMEIBT_BM_FREE(gqrp10x, buf.data_buf);

out:
	NFOUT;
}

/*
 * nvmeibt_dumper_global_topology(): dump current global topology
 */
void nvmeibt_dumper_event_global_topo(void)
{
	static int last_topo_ver = -1;
	int topo_ver;

	NFIN;

	if (!dumper_is_needed())
		goto out;

	/*
	 * If the global topology version did not change -and- the last event was
	 * also global topology, then skip this one since nothing has changed.
	 *
	 * However, if the last event was not global topology, e.g. peer update or
	 * disk removal, then we do want to replay the topology regeneration - to
	 * confirm that the global topology remains unchanged given the previously
	 * replayed event.
	 */

	topo_ver = (int)RAFT_COMMIT_LIFECYCLE_VAL(TOPO, leader_calculated);

	if (last_topo_ver == topo_ver) {
		if (strcmp(dumper_last_type, NVMEIBT_DUMPER_TYPE_TOPO) == 0) {
			N_Tf(trace_dumper_nvmeibt_dumper_event_global_topo, "skipping repetitive \"topo\" event");
			goto out;
		}
	} else {
		last_topo_ver = topo_ver;
	}

	dumper_write_buf(&(nvmeibt_raft_get_my_raft()->leader_to_commit_wire_topo), NVMEIBT_DUMPER_TYPE_TOPO);

out:
	NFOUT;
}

/*
 * nvmeibt_dumper_update_from_peer_applied(): dump an applied topology that
 * comes from a peer.
 */
void nvmeibt_dumper_event_peer_applied(const char *config_str)
{
	size_t len;

	NFIN;

	if (!dumper_is_needed())
		goto out;

	len = strlen(config_str);
	if (len == 0)
		N_Wf(warn_dumper_nvmeibt_dumper_event_peer_applied, "update_from_peer with length 0");

	dumper_write(NVMEIBT_DUMPER_TYPE_PEER, config_str, len);

out:
	NFOUT;
}

/*
 * nvmeibt_dumper_remove_disk_from_node(): dump an event of disk removal
 * from a node.
 */

#define DUMPER_DISK_LABEL_MAX 512

void nvmeibt_dumper_event_remove_disk(struct nvmeibt_disk *disk)
{
	char buf[DUMPER_DISK_LABEL_MAX];
	size_t len;

	NFIN;

	if (!dumper_is_needed())
		goto out;

	/*
	 * Removal of disk is an internal event, so there isn't a standardized
	 * CSV representation that we can (re)use.
	 * Instead, dumper generates a string to identify the disk, which replay
	 * will use to locate the disk in its @cur_topo data structure.
	 * Dumper writes: disk id, its original node id, and its node leader id.
	 * Replay reads all three, but only uses the disk id to locate the disk;
	 * The other two ids are used for sanity tests only.
	 * Same comment in toma/nvmeibt_replay.c:replay_event_remove_disk()
	 */

	len = snprintf(buf, sizeof(buf), "%s,%s,%s",
				   disk->urn_uuid.str,
				   nvmeibt_union_uuid_to_urn_uuid(&disk->from_config.its_original_node_id).str,
				   nvmeibt_disk_get_leader_node_name(disk));

	buf[DUMPER_DISK_LABEL_MAX - 1] = '\0';  /* just in case */
	NTOMA_ASSERT(error_dumper_nvmeibt_dumper_event_remove_disk, len < DUMPER_DISK_LABEL_MAX, "disk label too long: @BUF_STR", buf);

	dumper_write(NVMEIBT_DUMPER_TYPE_DISK, buf, len);

out:
	NFOUT;
}

/*
 * nvmeibt_dumper_enable(): enable/disable recording
 */
void nvmeibt_dumper_enable(BOOL enable)
{
	NFIN;

	if (nvmeibt_replay_is_enabled())
		goto skip;

	if (!enable) {
		nvmeibt_wq_flush(dumper_wq);
		dumper_reset_session();
	}

	N_Tf(trace_dumper_nvmeibt_dumper_enable, "Recording of TOMA events turned @STR", enable ? "ON" : "OFF");

skip:
	dumper_enabled = enable;

	NFOUT;
}

void nvmeibt_dumper_change_of_leader(BOOL leader)
{
	static BOOL is_leader = false;

	/*
	 * doing 'disable' then 'enable' ensures that current buffers are flushed,
	 * files get closed, and state is properly reset.
	 */
	if (dumper_enabled && leader != is_leader) {
		nvmeibt_dumper_enable(false);
		nvmeibt_dumper_enable(true);
		is_leader = leader;
	}
}

/*
 * nvmeibt_dumper_init(): initialize recording subsystem
 */
int nvmeibt_dumper_init(void)
{
	NFIN;

	N_Tf(trace_dumper_nvmeibt_dumper_init, "initialize dumper (recording) system");

	dumper_wq = nvmeibt_wq_create("Toma_record_offload");
	if (dumper_wq == NULL) {
		N_Ef(error_dumper_nvmeibt_dumper_init, "failed to create TOMA dumper thread");
		goto out;
	}

out:
	NFOUT;
	return 0;
}

/*
 * nvmeibt_dumper_exit(): cleanup recording subsystem
 */
void nvmeibt_dumper_exit(void)
{
	NFIN;

	N_Tf(trace_dumper_nvmeibt_dumper_exit, "clean up dumper (recording) system");

	if (dumper_wq) {
		nvmeibt_wq_flush(dumper_wq);
		nvmeibt_wq_destroy(dumper_wq);
		dumper_wq = NULL;
	}

	NFOUT;
}

