import json
import uuid
import socket
import hashlib
import struct
import marshal
import traceback

class EmulationModes:
	NONE = 0
	STATIC = 1
	HOTPLUG = 2

class MessagePriorities:
	LOW = 0
	MEDIUM = 1
	HIGH = 2

class Mailbox:
	def __init__(self):
		self.outbox = {}
		self.inbox = {}

def logStackTrace(logger):
	lines = traceback.format_stack()
	for line in lines:
		logger.debug(line)

class Message:
	def __init__(self, senderSocket, jsonObj, priority=MessagePriorities.MEDIUM, opcode=None, type=None, logger=None):
		self.id = uuid.uuid1()
		self.senderSocket = senderSocket
		self.isCacheAllowed = jsonObj["isCacheAllowed"] if "isCacheAllowed" in jsonObj else False
		self.priority = jsonObj["priority"] if "priority" in jsonObj else priority
		self.originType = jsonObj["originType"] if "originType" in jsonObj else "Unknown"
		self.opcode = opcode
		self.type = type
		self.requestMD5 = ''
		self.logger = logger
		self.type = jsonObj["opcode"] if self.type is None and "opcode" in jsonObj else -1

		self.jsonObj = jsonObj
		self.__payload = None

	def __str__(self):
		return json.dumps(self.jsonObj)

	@property
	def payload(self):
		if self.__payload is None:
			# self.logger.debug("building message(%s) payload;", self.__class__.__name__)
			self.__payload = self.prepPayload()
		return self.__payload

	def getProjection(self):
		return {}

	def setAccessToken(self, cookie):
		self.jsonObj["accessToken"] = cookie
		self.rebuildPayload()

	def setSequenceNumbers(self, connectionSeq, messageSeq):
		self.jsonObj["connectionSequence"] = connectionSeq
		self.jsonObj["messageSequence"] = messageSeq

		self.rebuildPayload()

	def rebuildPayload(self):
		self.__payload = None

	def prepPayload(self):
		self.jsonObj["originID"] = self.senderSocket.id
		self.jsonObj["messageID"] = str(self.id)
		hostPostfix = ''
		isAutoGen = hasattr(self.senderSocket, "isAutoGeneratedClientInstance") and self.senderSocket.isAutoGeneratedClientInstance
		if isAutoGen:
			self.jsonObj["isAutoGeneratedClientInstance"] = self.senderSocket.isAutoGeneratedClientInstance

		if hasattr(self.senderSocket, 'hostPostfix'):
			hostPostfix = self.senderSocket.hostPostfix

		if "mcString" in self.jsonObj and self.jsonObj["mcString"]:
			hostPostfix = '_{0}'.format(self.jsonObj["mcString"])

		self.jsonObj["registrant"] = {
			"type": self.originType,
			"id": '{0}{1}'.format(socket.gethostname(), hostPostfix if not isAutoGen else '')
		}

		self.jsonObj["protocolVersion"] = "1.0"

		projection = self.getProjection()

		if projection:
			payload = {}
			jsonObj = self.jsonObj["payload"] if "payload" in self.jsonObj else self.jsonObj

			for key in projection:
				payload[key] = jsonObj[projection[key]]

			self.jsonObj["payload"] = payload

		if not isinstance(self, LoginMessage) and not isinstance(self, SocketDisconnectionMessage):
			try:
				rqst = ( ("messageType", self.jsonObj["messageType"])
						, ("payload", self.jsonObj["payload"])
						, ("type", self.jsonObj["registrant"]["type"]))
				self.requestMD5 = hashlib.md5(marshal.dumps(rqst)).hexdigest()
				self.jsonObj["requestMD5"] = self.requestMD5
			except Exception as e:
				self.logger.exception("Failed to prepPayload; json=%s", self.jsonObj)
				return None

		return bytearray(json.dumps(self.jsonObj), 'utf-8')


class GenericMessage(Message):
	def __init__(self, senderSocket, jsonData, logger, opcode=None):
		Message.__init__(self, senderSocket, jsonData, opcode=opcode, logger=logger)

	def prepPayload(self):
		data = bytearray(json.dumps(self.jsonObj), 'utf-8')
		msgLength = struct.pack("I", len(data))
		return { 'payload': msgLength + data }

class BinaryMessage(Message):
	def __init__(self, senderSocket, opcode, data, logger):
		msgLength = struct.pack("I", len(data))
		Message.__init__(self, senderSocket, {'opcode': opcode, 'payload': msgLength + data},
						 priority=MessagePriorities.HIGH, type=MessageTypes.UPDATE_ATTACHMENT_STATUS, logger=logger)

	def prepPayload(self):
		return self.jsonObj


class AttachmentStatusMessage(Message):
	def __init__(self, senderSocket, jsonObj, logger):
		Message.__init__(self, senderSocket, jsonObj, type=MessageTypes.UPDATE_ATTACHMENT_STATUS, logger=logger)

	def getProjection(self):
		projection = {
			"volumeVersion": "volume_version",
			"volumeStatus": "vol_status",
			"uuid": "volume_uuid"
		}

		return projection

	def prepPayload(self):
		self.jsonObj["route"] = "/updateAttachmentStatus"
		return Message.prepPayload(self)


class LoginMessage(Message):
	def __init__(self, senderSocket, email, password, logger):
		self.email = email
		self.password = password
		self.senderSocket = senderSocket

		Message.__init__(self, senderSocket, {}, type=MessageTypes.MANAGEMENT_LOGIN, logger=logger)

	def prepPayload(self):
		self.jsonObj["email"] = self.email
		self.jsonObj["password"] = self.password
		self.jsonObj["registrant"] = {id: '{0}{1}'.format(
			socket.gethostname(),
			self.senderSocket.hostPostfix if hasattr(self.senderSocket, 'hostPostfix') else ''
		)}

		if hasattr(self.senderSocket, "isAutoGeneratedClientInstance"):
			self.jsonObj["isAutoGeneratedClientInstance"] = self.senderSocket.isAutoGeneratedClientInstance

		return Message.prepPayload(self)


class SocketDisconnectionMessage(Message):
	def __init__(self, senderSocket, jsonObj, logger):
		Message.__init__(self, senderSocket, jsonObj, type=MessageTypes.DISCONNECTION_MESSAGE, logger=logger)

	def setSequenceNumbers(self, connectionSequence, messageSequence):
		connSeq = self.jsonObj["connectionSequence"] if "connectionSequence" in self.jsonObj else connectionSequence
		Message.setSequenceNumbers(self, connSeq, messageSequence)


class MessageTypes:
	ERROR = -1
	MANAGEMENT_LOGIN = 0
	REPORT_TARGET = 1
	UPDATE_ATTACHMENT_STATUS = 2
	REPORT_CLIENT = 3
	GET_CONFIGURATION_VERSION = 4
	GET_TARGET_CSV = 5
	GET_NICS_CSV = 6
	GET_DISKS_CSV = 7
	GET_BLOCK_DEVICES_CSV = 8
	GET_CHUNKS_CSV = 9
	GET_DISK_SEGMENTS_CSV = 10
	GET_VOLUMES = 11
	CHECK_FOR_TARGET_CONTROL_JOBS = 12
	CHECK_FOR_CLIENT_CONTROL_JOBS = 13
	CLEAR_CLIENT_RENEW_CONFIGURATION = 14
	CLEAR_CLIENT_SHUTDOWN = 15
	UPDATE_DISK_SEGMENTS_STATUS = 16
	REGISTER_ON_EVENTS = 17
	UNREGISTER_FROM_EVENTS = 18
	CLIENT_CONFIGURATION = 21
	NEW_NIC_EVENT = 22
	REAPPEAR_NIC_EVENT = 23
	DELETE_NIC_EVENT = 24
	ERROR_RESPONSE = 25
	DISCONNECTION_MESSAGE = 26
	VOLUME_REMOVED_EVENT = 27
	VOLUME_EXTENDED_EVENT = 29
	VOLUME_REMAP_EVENT = 30
	DISK_REAPPEAR_EVENT = 31
	REGISTER_STATS_EVENTS = 53
	END_OF_CACHE = 55
	VOLUME_VERSION_CHANGED = 45
	UPDATE_PRAID_STATUS = 46
	UPDATE_DRIVE_ZEROING_PROGRESS = 47
	SEND_CLIENT_REPORT_EVENT = 49
	CLIENT_KEEP_ALIVE = 50
	AGENT_KEEP_ALIVE = 51
	CSV_ONLY_TRANSLATION = 80
	DELIVERY_DONE = 59
	UNAUTHORIZED_REQUEST = 60
	RESEND_CONF_REQUEST = 61
	UPDATE_KEYS = 62
	CHANGE_NIC = 63
	NODE_CONFIG_PROFILE_UPDATED=64
	NODE_CONFIG_USER_OVERRIDE_UPDATED=65
	SEND_CONFIGURATION=66
	DETACH_VOLUME = 67
	UPDATE_CLIENT_KEEPALIVE_TOKEN = 69
	ATTACH_VOLUMES = 90
	UPDATE_VOLUMES = 91
	DETACH_VOLUMES = 92
	UPDATE_TARGET_NICS = 93
	GET_TARGET_NICS = 94
	UPDATE_VOLUME_EMULATION = 95
	UPDATE_VOLUME_REFERENCE = 96
	CONFIGURATION_MESSAGES = [REGISTER_ON_EVENTS, NEW_NIC_EVENT, REAPPEAR_NIC_EVENT, DELETE_NIC_EVENT,
							  VOLUME_REMOVED_EVENT, VOLUME_EXTENDED_EVENT, VOLUME_REMAP_EVENT, DISK_REAPPEAR_EVENT,
							  CLIENT_CONFIGURATION, UNREGISTER_FROM_EVENTS, CHANGE_NIC]
