# NVMesh configuration file
# This configuration file is utilized by NVMesh(r) applications for various options.

#
# REST Connectivity Options (required for nvmesh cli to communicate to Management)
#
# REQUIRED: Specify the management servers for REST requests.
# If using non-standard REST port <mN> can be specified as mN:port
# _REST_SERVERS="<m1>[,<m2>...]"

_REST_SERVERS="nvmesh-01,nvmesh-02,nvmesh-03"

#
# REQUIRED: Rest Authentication method: either "credentials" for username/password or "MTLS" if using keys
# _REST_AUTH_METHOD="[MTLS|credentials]"
# Example:

_REST_AUTH_METHOD="credentials"

#
# OPTIONAL: Set path to the REST key CA signing certificate
# When using MTLS auth method, key/cert location defaults to ~/.nvmesh/nvmesh.key, ~/.nvmesh/nvmesh.crt and
# ~/.nvmesh/ca_chain.crt
# IF you wish to store ca_chain.crt centrally, you can specify is as:
# _REST_CA="</path/to/ca/certificate>"
# Example:
# _REST_CA="/etc/nvmesh/tls/rest_ca.crt"
# #
# Alternatively, you can store keys for multiple users under /etc/nvmesh/tls where the key and crt files are
# named as /etc/nvmesh/tls/<User>.key and /etc/nvmesh/tls/<User>.crt, where <User> is the userid capitalized.
# The default _REST_CA will be: /etc/nvmesh/tls/ca_chain.crt

# Define the location of the Kafka servers used with NVMesh Management to communicate
# KAFKA_SERVERS="<server name or IP>:<port>,<server name or IP>:<port>,..."
# Example:
# KAFKA_SERVERS="kafka-server1:9092,kafka-server2:9092"

KAFKA_SERVERS="kafka-server:9092"

# Define the nics that will be available for NVMesh Client/Target to work with
# CONFIGURED_NICS="<interface name;interface name;...>"
# To allow all nics to be available leave empty. Example: CONFIGURED_NICS=""
# Examples:
# CONFIGURED_NICS="ib0;eno1;eth0"
# CONFIGURED_NICS="eno1;eth0"

CONFIGURED_NICS=""

# Define the RDMA nics that will not be used for NVMesh
# BLACKLIST_NICS="<interface_name;interface_name;...>"
# To allow all nics to be available leave empty. Example: BLACKLIST_NICS=""
# Examples:
# BLACKLIST_NICS="mlx5_0;mlx5_1"

BLACKLIST_NICS=""

# Define the IP of the nic to use for NVMf target
# NVMF_IP="<nic IP>"
# Must not be empty in case of using NVMf target
# Examples:
# NVMF_IP="12.12.12.48;12.12.12.56"
# NVMF_IP="12.12.12.51"

#NVMF_IP=""

# ACCESS_METHOD should value be either 'nvmf' or 'iscsi'
#ACCESS_METHOD=""

# The IP of ISCSI target node - format: <IP>:<PORT>
#ISCSI_TARGET_IP=""
# The IP of the ISCSI initiator remote node
#ISCSI_INITIATOR_IP=""

