# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Excluded drives description
# Every line should look like:
# nvme,<serial-id>,<vendor>,<model>,<nsid>
# Every device that matches all of the specified fields is excluded by NVMesh
# Examples
# nvme,,XXX,,	# Exclude drives whose vendor is XXX
# nvme,YYY,,,2	# Exclude drive(s) YYY.2
