#!/usr/bin/env python3
import json
import sys

STAT_FILE_BASE_PATH = '/tmp/statistics/nvmeibs/DISK'

def print_usage():
	print("Simple nvme-cli Simulator used by NVMesh Simulator")
	print("usage:")
	print("nvme list\tshow simulated list nvme device")
	print("nvme smart-log <device-path>\tshow simulated device status. example: nvme smart-log /dev/nvme1000n1")

def print_usage_and_exit(exit_code=1):
	print_usage()
	exit(exit_code)

def get_devices_serial_numbers():
	try:
		with open('/tmp/statistics/nvmeibs/diskSerialNumbers.json') as fp:
			serial_numbers = json.load(fp)
			return serial_numbers
	except Exception as ex:
		return []

def print_nvme_list():
	serials = get_devices_serial_numbers()
	device_list = [ get_list_item(i, serial_number) for (i, serial_number) in enumerate(serials) ]
	result_obj = { 'Devices': device_list }
	print(json.dumps(result_obj))

def get_list_item(i, serial_number_with_ns):
	sn_parts = serial_number_with_ns.split('.')
	serial_number = sn_parts[0]
	namespace = sn_parts[1]
	# index start at 1000
	nvme_index = 1000 + i
	device_path = '/dev/nvme{i}n{ns}'.format(i=nvme_index, ns=namespace)
	item = {
		"DevicePath": device_path,
		"Firmware": "GPNA5B3Q",
		"Index": nvme_index,
		"ModelNumber": "SAMSUNG MZWLL800HEHP-00003",
		"ProductName": "Unknown Device",
		"SerialNumber": serial_number,
		"UsedBytes": 800166076416,
		"MaximiumLBA": 195353046,
		"PhysicalSize": 800166076416,
		"SectorSize": 4096
	}

	return item

def print_nvme_smart_log(device_path):
	file_path = '{base}/{dev}/iostats.json'.format(base=STAT_FILE_BASE_PATH, dev=device_path)

	with open(file_path, 'r') as f:
		file_contents = f.read()
		print(file_contents)

### MAIN ###
if len(sys.argv) < 2:
	print("no option given")
	print_usage_and_exit()

if sys.argv[1] == 'list':
	print_nvme_list()
elif sys.argv[1] == "smart-log":
	if len(sys.argv) < 3:
		print("missing device path")
		print_usage_and_exit()

	device_path = sys.argv[2]
	print_nvme_smart_log(device_path)
else:
	print("unknown option {}".format(sys.argv[1]))
	print_usage_and_exit()
