# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

#

obj-m += pcie_atom_test.o
pcie_atom_test-y := atom_test.o


