/*
* SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
* SPDX-License-Identifier: GPL-2.0-only OR Apache-2.0
*/

#ifndef __MACRO_UTILS_H
#define __MACRO_UTILS_H

// This files privdes the following interfaces:
// 
// NVMEIB_ISEMPTY
// NVMEIB_FOREACH
// NVMEIB_VA_STRINGIFY
// 
// Is empty usage: NVMEIB_ISEMPTY(arg1, arg2, ...)
// NVMEIB_NVMEIB_ISEMPTY() yields 1
// NVMEIB_NVMEIB_ISEMPTY(some non empty args list) yields 0
// Then, you can do, for example:
// #define TEST_0(name, ...) printf(#name " %d\n", NVMEIB_NUM_ARGS(__VA_ARGS__) )
// #define TEST_1(name) printf(#name " - no args\n")
// #define TEST(name, ...) NVMEIB_CONCAT2(TEST_, NVMEIB_ISEMPTY(__VA_ARGS__)) (name, ## __VA_ARGS__)
// TEST(name) ==> printf("name - no args")
// TEST(name, arg, arg, arg) ==> printf("name - %d", 3)
// 
// For each usage: NVMEIB_FOREACH(MACRO, (arg1, arg2, arg3, ...))
// This set of macros can be used to apply a macro on a varadic macro arguments list.
// It will generate a sequence of form MACRO(arg1) MACRO(arg2) MACRO(arg3) ...
//
// For example, in order to convert a varadic list of arguments into strings, use
// NVMEIB_FOREACH(NVMEIB_STRINGIFY, (hello, wonderful, world)) which will generate:
// >>> "hello""wonderful""world"
// This will be interpreted as a single string, in COMPILATION time
// 
// Stringify usage: NVMEIB_VA_STRINGIFY( ## __VA_ARGS__ )
// This macro is an alias for foreach which turns varadic list to list of strings


#define _NVMEIB_NUM_ARGS(X100, X99, X98, X97, X96, X95, X94, X93, X92, X91, X90, X89, X88, X87, X86, X85, X84, X83, X82, X81, X80, X79, X78, X77, X76, X75, X74, X73, X72, X71, X70, X69, X68, X67, X66, X65, X64, X63, X62, X61, X60, X59, X58, X57, X56, X55, X54, X53, X52, X51, X50, X49, X48, X47, X46, X45, X44, X43, X42, X41, X40, X39, X38, X37, X36, X35, X34, X33, X32, X31, X30, X29, X28, X27, X26, X25, X24, X23, X22, X21, X20, X19, X18, X17, X16, X15, X14, X13, X12, X11, X10, X9, X8, X7, X6, X5, X4, X3, X2, X1, N, ...)   N

#define NVMEIB_NUM_ARGS(...) _NVMEIB_NUM_ARGS(dummy, ##__VA_ARGS__, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)

#define NVMEIB_HAS_COMMA(...) _NVMEIB_NUM_ARGS(__VA_ARGS__, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)

#define NVMEIB_IFF_EMPTY(param, ifempty, ifnempty) NVMEIB_CONCAT2(NVMEIB_DEFAULT_PARAM_, NVMEIB_NUM_ARGS(param))(ifempty, ifnempty)
#define NVMEIB_DEFAULT_PARAM_1(ifempty, ifnempty) ifnempty
#define NVMEIB_DEFAULT_PARAM_0(ifempty, ifnempty) ifempty

#define NVMEIB_HAS_ARGS(...) NVMEIB_HAS_COMMA(dummy, ##__VA_ARGS__)

#define _NVMEIB_TRIGGER_PARENTHESIS_(...) ,

#define NVMEIB_CONCAT5(_0, _1, _2, _3, _4) _0 ## _1 ## _2 ## _3 ## _4
#define NVMEIB_CONCAT2(x, y) _NVMEIB_CONCAT2(x, y)
#define _NVMEIB_CONCAT2(x, y) x ## y

#define _NVMEIB_IS_EMPTY_CASE_0001 ,
#define _NVMEIB_ISEMPTY(_0, _1, _2, _3) NVMEIB_HAS_COMMA(NVMEIB_CONCAT5(_NVMEIB_IS_EMPTY_CASE_, _0, _1, _2, _3))

#define NVMEIB_ISEMPTY(...) \
_NVMEIB_ISEMPTY( \
	NVMEIB_HAS_COMMA(__VA_ARGS__), \
	NVMEIB_HAS_COMMA(_NVMEIB_TRIGGER_PARENTHESIS_ __VA_ARGS__), \
	NVMEIB_HAS_COMMA(__VA_ARGS__ (/*empty*/)), \
	NVMEIB_HAS_COMMA(_NVMEIB_TRIGGER_PARENTHESIS_ __VA_ARGS__ (/*empty*/)) \
)

#define NVMEIB_EXPAND(X)       X
#define NVMEIB_FIRSTARG(X, ...)    (X)
#define NVMEIB_RESTARGS(X, ...)    (__VA_ARGS__)
#define NVMEIB_FOREACH(MACRO, LIST)    NVMEIB_FOREACH_(NVMEIB_NUM_ARGS LIST, MACRO, LIST)
#define NVMEIB_FOREACH_(N, M, LIST)    NVMEIB_FOREACH__(N, M, LIST)
#define NVMEIB_FOREACH__(N, M, LIST)   NVMEIB_FOREACH_##N(M, LIST)
#define NVMEIB_FOREACH_1(M, LIST)  M LIST
#define NVMEIB_FOREACH_2(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_1(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_3(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_2(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_4(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_3(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_5(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_4(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_6(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_5(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_7(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_6(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_8(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_7(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_9(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_8(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_10(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_9(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_11(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_10(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_12(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_11(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_13(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_12(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_14(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_13(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_15(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_14(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_16(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_15(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_17(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_16(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_18(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_17(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_19(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_18(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_20(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_19(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_21(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_20(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_22(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_21(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_23(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_22(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_24(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_23(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_25(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_24(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_26(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_25(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_27(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_26(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_28(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_27(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_29(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_28(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_30(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_29(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_31(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_30(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_32(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_31(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_33(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_32(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_34(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_33(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_35(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_34(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_36(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_35(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_37(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_36(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_38(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_37(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_39(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_38(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_40(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_39(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_41(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_40(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_42(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_41(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_43(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_42(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_44(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_43(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_45(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_44(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_46(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_45(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_47(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_46(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_48(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_47(M, NVMEIB_RESTARGS LIST)
#define NVMEIB_FOREACH_49(M, LIST)  NVMEIB_EXPAND(M NVMEIB_FIRSTARG LIST) NVMEIB_FOREACH_48(M, NVMEIB_RESTARGS LIST)


#define _NVMEIB_STRINGIFY1(x) #x
#define NVMEIB_STRINGIFY1(x) _NVMEIB_STRINGIFY1(x)

#define NVMEIB_STRINGIFY(X)      #X,
#define NVMEIB_VA_STRINGIFY(...)   NVMEIB_FOREACH(NVMEIB_STRINGIFY, (__VA_ARGS__))

#define NVMEIB_CAT_PAIRS(...) NVMEIB_CONCAT2(NVMEIB_CAT_PAIRS_, NVMEIB_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)

#define NVMEIB_CAT_PAIRS_2(a1, a2) a1 a2
#define NVMEIB_CAT_PAIRS_4(a1, a2, a3, a4) a1 a2, a3 a4
#define NVMEIB_CAT_PAIRS_6(a1, a2, a3, a4, a5, a6) a1 a2, a3 a4, a5 a6
#define NVMEIB_CAT_PAIRS_8(a1, a2, a3, a4, a5, a6, a7, a8) a1 a2, a3 a4, a5 a6, a7 a8
#define NVMEIB_CAT_PAIRS_10(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) a1 a2, a3 a4, a5 a6, a7 a8, a9 a10

#define NVMEIB_EVEN_ARGS(...) NVMEIB_CONCAT2(NVMEIB_EVEN_ARGS_, NVMEIB_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)

#define NVMEIB_EVEN_ARGS_2(a1, a2) a2
#define NVMEIB_EVEN_ARGS_4(a1, a2, a3, a4) a2, a4
#define NVMEIB_EVEN_ARGS_6(a1, a2, a3, a4, a5, a6) a2, a4, a6
#define NVMEIB_EVEN_ARGS_8(a1, a2, a3, a4, a5, a6, a7, a8) a2, a4, a6, a8
#define NVMEIB_EVEN_ARGS_10(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) a2, a4, a6, a8, a10

/*
 * calculates memory size occupied by the arr;
 * Also check that we are using static array and not some pointer via ARRAY_SIZE
 */
#define ARRAY_MEM_SIZE(arr) ARRAY_SIZE(arr)*sizeof((arr)[0])

#ifndef __FILE_NAME__
#define __FILE_NAME__ __FILE__ /* introduced on gcc 12.x, for older compliers use the path-ed version */
#endif

#endif /* __MACRO_UTILS_H */
