[project]
name = "nvmeib-pet"
version = "0.1.0"
description = "NVMesh PET (Per Entity Traces) tool"
authors = [
    {name = "Roman Yakovenko",email = "ryakovenko@nvidia.com"}
]
readme = "README.md"
requires-python = ">3.9"
dependencies = [
    "pydantic (>=2.12.5)",
    "pyelftools (>=0.32)",
    "kaitaistruct (>=0.11)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
