obj-m += dclib.o
dclib-y += requests.o
dclib-y += wth.o
dclib-y += poller.o
dclib-y += utils.o
dclib-y += rdma_dev.o
dclib-y += manager.o
dclib-y += main.o
dclib-y += server_tester.o
dclib-y += client_tester.o

ccflags-y += -DDEBUG

