#
# nvmesh.conf - ensure to override built-in kernel
#

override siw * extra/nvmesh/common/softiwarp/kernel
override rdma_cm * extra/nvmesh/ib_core
override iw_cm * extra/nvmesh/ib_core
search extra/nvmesh

