# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

#options nvmeibs min_local_nvmeqs=32
#options nvmeibs max_local_nvmeqs=32
options nvmeibs nr_max_channels_per_path_tcp=32
options nvmeibc nr_max_channels_per_path_tcp=16
options nvmeibc nr_max_channels_per_disk=32
options nvmeibc nr_max_used_reqs_per_channel=8
options siw notify_on_wq=N panic_on_rx_err=N debug_level=1 tx_flags_from_upstream=Y tx_flags_use_eor=Y comp_vector_cpu0=0

