#!/bin/bash
# Assume we are in project directory

if declare -F NVMESH_help > /dev/null; then
	echo "help scripts already exist";
else
	source ../../tools/block_team_bashrc.sh;	# Load the bashrc
fi
EXE_NAME="nvmeibt_toma";
function __run_cmd() {	cmd=("$@"); echo -e "\e[1;33m************************ ${cmd}\e[0;39m"; eval ${cmd}; }
function _print_wait() { cmd=("$@"); echo -en "\e[1;33m************************ ${cmd}\e[0;39m"; read -p ", Press Enter..." -r; echo; }

function __cleanup_prev_run_state() {
	make clean_run;
	kill_process;
}

function kill_process() {
	pgrep "${EXE_NAME}" > /dev/null || return 0;
	echo "process is already running - terminating it; PID: $(pgrep "${EXE_NAME}")"
	# First try to send SIGTERM to the process as regular user - avoid sudo unless necessary.
	if ! pkill "${EXE_NAME}"; then
		echo "unable to send SIGTERM to ${EXE_NAME} as regular user, trying with sudo";
		sudo pkill ${EXE_NAME} || { echo_red "failed to sudo pkill"; exit 1; }
	else
		# Sent SIGTERM successfully as user
		echo "previously running process was terminated"
	fi
}

function __force_rebuild() {
	echo "Rebuilding project...";
	make clean;
	local compile_cmd="make all -j $@";
	__run_cmd "$compile_cmd";
}

function __build_if_needed() {
	__cleanup_prev_run_state;
	if [[ ! -f "${EXE_NAME}" ]]; then
		__force_rebuild;
	fi
	local compile_cmd="make all -j $@";
	__run_cmd "$compile_cmd";
}

function __abort_ci_on_failure_silent() {
	[ $? -eq 0 ] || { echo_red "FAILED - status=$?" && exit 4; }
}

function __abort_ci_on_failure() {
	[ $? -eq 0 ] && echo_green "SUCCESS!\n\n" || { echo_red "FAILED - status=$?" && exit 1; }
}

function T_SANDBOX_gpt_util_self_unit_test() {
	__build_if_needed;
	local disks_csv_file="_root/proc/nvmeibs/disks.csv";
	echo_title "Creating ${disks_csv_file}";
	echo -e "id,blocks,hw_blocks,block_size,max_request_size,seq,nsid,dev_name,metadata,status,vendor,model,native_serial\nNVMD_SN_002.1,10240,10240,4096,32,1,1,/dev/nvme1001n1,0,Ok,5122,NVMD_NN_002,NVMD_SN_002\nNVMD_SN_003.1,10240,10240,4096,32,2,1,/dev/nvme1002n1,8,Ok,5123,NVMD_NN_003,NVMD_SN_003" > ${disks_csv_file};
	./${EXE_NAME} gpt_util -T;
	local test_rv=$?;
	rm ${disks_csv_file};
	[ ${test_rv} -eq 0 ] && echo_green "SUCCESS!\n\n" || { echo_red "FAILED - status=$?" && exit 1; }
}

function T_SANDBOX_toma_persist_json_test() {
	echo_title "Generating Toma persistency JSON";
	local persist="_root/var/opt/nvmesh/toma/toma_persistence_2_8_0_raft_and_topo.0";
	local bin_orig="z.bin";
	local orig_json="z.json";
	#./${EXE_NAME} --convert-to-json --input-file ${persist} --output-file ${orig_json};
	cp ${persist} ${bin_orig};
	../scripts/toma_persistence_to_JSON.sh <<< "$(printf '%s\n%s\n%s\n' "${bin_orig}" "${orig_json}" "./${EXE_NAME}")";
	__abort_ci_on_failure_silent;

	echo_title "Encoding Toma Persistency j2bin";
	local bin_1="${orig_json}.bin";
	../scripts/JSON_to_toma_persistence.sh <<< "$(printf '%s\n%s\n%s\n' "${orig_json}" "${bin_1}" "./${EXE_NAME}")";
	__abort_ci_on_failure_silent;

	echo_title "Toma persistency j2bin2j";
	local json_1="${bin_1}.json";
	../scripts/toma_persistence_to_JSON.sh <<< "$(printf '%s\n%s\n%s\n' "${bin_1}" "${json_1}" "./${EXE_NAME}")";
	__abort_ci_on_failure_silent;

	echo_title "Encoding Toma Persistency j2bin2j2bin";
	local bin_2="${json_1}.bin";
	../scripts/JSON_to_toma_persistence.sh <<< "$(printf '%s\n%s\n%s\n' "${json_1}" "${bin_2}" "./${EXE_NAME}")";
	__abort_ci_on_failure_silent;

	echo_title "Toma persistency j2bin2j2bin2j";
	local json_2="${bin_2}.json";
	../scripts/toma_persistence_to_JSON.sh <<< "$(printf '%s\n%s\n%s\n' "${bin_2}" "${json_2}" "./${EXE_NAME}")";
	__abort_ci_on_failure_silent;

	echo_title "Toma persistency Results";
	ls -l z.*;
	cmp -s ${json_1} ${json_2} || { echo_red "FAILED - json not identical" && exit 4; }
	cmp -s ${bin_1}  ${bin_2}  || { echo_red "FAILED - bins not identical" && exit 4; }
	__run_cmd "cat ${orig_json} | jq .";
	__run_cmd "cat ${json_2} | jq .";
	sudo rm ${bin_orig}* ${orig_json}*;
	__abort_ci_on_failure;
}

function T_SANDBOX_test_framework() {
	__build_if_needed;
	./${EXE_NAME} test_framework;
	__abort_ci_on_failure;
}

function T_SANDBOX_topo_merge_test() {
	__build_if_needed;
	./${EXE_NAME} topo_merge_test;
	__abort_ci_on_failure;
}

function T_SANDBOX_main_self_unit_test() {
	__cleanup_prev_run_state;
	__build_if_needed;
	./${EXE_NAME};
	__abort_ci_on_failure;
	_root/var/log/nvmesh/trace_daemon/pager _root/var/log/nvmesh/trace_daemon --toma --color  > z.txt;
}

function T_SANDBOX_unit_test_frame_work_self_check() {
	__build_if_needed;
	./${EXE_NAME} test_framework
	__abort_ci_on_failure;
}

function T_SANDBOX_main_self_reuse_persistency_unit_test() {
	./${EXE_NAME};
	__abort_ci_on_failure;
}


function T_SANDBOX_main_live_run() {
	echo_red "Todo: Test, Not supported yet";
}

# ---------------------------------------------------------------------
case "$1" in
  rebuild*)		__force_rebuild;;
  framework*)	T_SANDBOX_test_framework;;
  topo*)		T_SANDBOX_topo_merge_test;;
  main*)		T_SANDBOX_main_self_unit_test ${@:2};;
  live*)		T_SANDBOX_main_live_run;;
  gpt*)			T_SANDBOX_gpt_util_self_unit_test;;
  persi*)		T_SANDBOX_toma_persist_json_test;;
  ci*)
	clear;
	#__force_rebuild BUILD_RELEASE=1;
	T_SANDBOX_unit_test_frame_work_self_check;
	T_SANDBOX_main_self_unit_test;
	T_SANDBOX_main_self_reuse_persistency_unit_test;
	T_SANDBOX_toma_persist_json_test;
	T_SANDBOX_gpt_util_self_unit_test;
	T_SANDBOX_test_framework;
	T_SANDBOX_topo_merge_test;
	date;
	echo_green "************************ CI Done";
	;;
  *)
	echo $"Usage: $0 {1 of the options below}";
	echo_yellow "  ------------ Unit-tests of sub components:";
	echo "    main              - Self test of toma main executable";
	echo "    gpt_util          - Self test of gpt utility";
	echo "    persistency       - Self test of Toma persistency utility";
	echo "    framework         - Test framework smoke test";
	echo "    topo_merge        - Topo merge unit tests";
	echo_yellow "  ------------ Debug, development tests:";
	echo "    rebuild           - Fully recompile Toma. Pass additional make params like release compilation"
	echo "    live              - Launch Toma to be able to manually play with it, RPC and others";
	echo "    ci                - Nightly/CI run";
	exit 2
esac
RETVAL=$?
echo
exit $RETVAL
