#!/bin/bash
# Assume we are in project directory

if declare -F NVMESH_help > /dev/null; then
	echo "help scripts already exist";
else
	source ../../tools/block_team_bashrc.sh;	# Load the bashrc
fi
EXE_NAME="nvmeibt_toma";
function __run_cmd() {	cmd=("$@"); echo -e "\e[1;33m************************ ${cmd}\e[0;39m"; eval ${cmd}; }
function _print_wait() { cmd=("$@"); echo -en "\e[1;33m************************ ${cmd}\e[0;39m"; read -p ", Press Enter..." -r; echo; }

function __cleanup_prev_run_state() {
	make clean_run;
	sudo pkill ${EXE_NAME};
}

function __force_rebuild() {
	make clean;
	local compile_cmd="make all -j $@";
	__run_cmd "$compile_cmd";
}

function __build_if_needed() {
	__cleanup_prev_run_state;
	if [[ ! -f "${EXE_NAME}" ]]; then
		__force_rebuild;
	fi
	local compile_cmd="make all -j $@";
	__run_cmd "$compile_cmd";
}

function T_SANDBOX_gpt_util_self_unit_test() {
	__build_if_needed;
	./${EXE_NAME} gpt_util -T;
	[ $? -eq 0 ] && echo_green "SUCCESS!" || echo_red "FAILED - status=$?";
}

function T_SANDBOX_main_self_unit_test() {
	__cleanup_prev_run_state;
	__build_if_needed;
	./${EXE_NAME};
	[ $? -eq 0 ] && echo_green "SUCCESS!" || echo_red "FAILED - status=$?";
}

function T_SANDBOX_main_live_run() {
	echo_red "Todo: Test, Not supported yet";
}

function T_SANDBOX_persistency_to_from_json() {
	echo_red "Todo: Test, Not supported yet";
}

# ---------------------------------------------------------------------
case "$1" in
  rebuild*)		__force_rebuild;;
  main*)		T_SANDBOX_main_self_unit_test ${@:2};;
  live*)		T_SANDBOX_main_live_run;;
  gpt*)			T_SANDBOX_gpt_util_self_unit_test;;
  persi*)		T_SANDBOX_persistency_to_from_json;;
  ci*)
	clear;
	__force_rebuild BUILD_RELEASE=1;
	T_SANDBOX_main_self_unit_test clean;
	T_SANDBOX_gpt_util_self_unit_test;
	#T_SANDBOX_persistency_to_from_json;
	date;
	echo_green "************************ CI Done";
	;;
  *)
	echo $"Usage: $0 {1 of the options below}";
	echo_yellow "  ------------ Unit-tests of sub components:";
	echo "    main              - Self test of toma main executable";
	echo "    gpt_util          - Self test of gpt utility";
	echo "    persistency       - Self test of Toma persistency utility";
	echo_yellow "  ------------ Debug, development tests:";
	echo "    rebuild           - Fully recompile Toma. Pass additional make params like release compilation"
	echo "    live        	    - Launch Toma to be able to manually play with it, RPC and others";
	echo "    ci        	    - Nightly/CI run";
	exit 2
esac
RETVAL=$?
echo
exit $RETVAL
